### ISSUE TITLE
新版界面让人困惑！

### ISSUE THREAD

**Issue by CodingOctocat** [YerongAI/Office-Tool#105]
1. 比如以下界面，如果我点部署，那到底是什么情况？我会安装那些版本及组件？
2. 右侧栏的设置和左边的设置有什么联系？（如：右侧栏的更新通道和左侧的更新通道设置有什么区别？）
3. 如果我点击卸载选中的产品，是卸载整个Office还是能卸载部分组件？
4. 如何删除已下载的产品？

![Snipaste_2020-02-20_09-41-08](https://user-images.githubusercontent.com/7220248/74892657-2d2fee00-53c5-11ea-9573-ccd46116d713.png)

**Comment by chiyi4488** [comment]
1. 你會安裝 Office 專業增強版的 Word, Excel, PowerPoint。
2. 從右側滑出的選單中的是修改「已安裝的 Office」；右側邊沒有滑出的選單是與左側設定搭配的，因此修改該設定後會影響部署設定。
3. 你將卸載左側邊勾選的產品，如果是要單獨卸載某個應用程式，只要將該應用程式的勾勾解除，點選「開始部署」，即可單獨卸載應用程式。
4. 同 3.。

**Comment by chiyi4488** [comment]
如有任何問題，請再次建立新 issues，或者告知重新開啟此 issues
