### ISSUE TITLE
[BUG]设置组织名称闪退

### ISSUE THREAD

**Issue by LuxferreX** [YerongAI/Office-Tool#107]
高级设置--常规设置
设置组织名首字母L，再输入，界面冻结后闪退。

**Comment by chiyi4488** [comment]
了解，之后会修复的。

**Comment by LuxferreX** [comment]
辛苦了，感谢！

获取 Outlook for Android<https://aka.ms/ghei36>
________________________________

**Comment by chiyi4488** [comment]
已於第八版修復：）
