### ISSUE TITLE
请问本软件开源吗？

### ISSUE THREAD

**Issue by 1357310795** [YerongAI/Office-Tool#109]
蓝点网的鸭子哥说otp开源。但是我在此并没有看到开源代码。
![Snipaste_2020-03-31_10-01-14](https://user-images.githubusercontent.com/35869804/77979245-af052680-7336-11ea-853a-a4328d0164fc.png)

**Comment by chiyi4488** [comment]
**暫停開源**，詳情請問 @YerongAI 。

如需再次開啟 issues，請通知。
