### ISSUE TITLE
希望能够支持 .Net Core 3.1 x64

### ISSUE THREAD

**Issue by lvzhenbo** [YerongAI/Office-Tool#113]
现在大部分用OTP的应该都是64位系统了，但新版还基于x86运行库有点让人难以理解

**Comment by YerongAI** [comment]
只要 Office 还有 32 位版本的，Office Tool Plus 就永远不会使用 64 位架构去开发。
以及迅雷下载引擎无法在 64 位环境下运行，这也是必须要考虑的，除非有新的引擎可选。

**Comment by lvzhenbo** [comment]
哦，这样啊。下载引擎的话aria2挺不错的，不知道这个可不可以

**Comment by YerongAI** [comment]
> 哦，这样啊。下载引擎的话aria2挺不错的，不知道这个可不可以

由于一些特殊原因，Aria2c 已从 V7 版本中移除，并且不会在后续版本中考虑添加。
