### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by HookSafe** [YerongAI/Office-Tool#128]
![image](https://user-images.githubusercontent.com/31431797/84622865-99080a80-af10-11ea-83d4-4602f0b8ce4c.png)
我不知道为什么这个软件要强制更新，原来版本用的好好的一直强制更新。现在我想装一个2016都装不上 我不知道这个提示有什么意思。我下的plus版本 居然提示我要plus模块？？？ 

求求你下个版本别搞强制更新行不行。18年那段时间的版本最好用，又整合了kms激活 下的office版本又全。现在不知道怎么回事 越来越难用。 如果你要明确收费，你可以正大光明搞一个收费版，好好的提供服务，我可以支付给你相应费用。别整这种强制更新 关键更新了office2016不让安装了。。。。。。。。。。

**Comment by YerongAI** [comment]
1. 强制更新多数是为了修复 bug，而不是给你推广告或者是弹窗，更不是给你删掉功能做限制。
2. 就你的截图来说，你只需要把右边的安装模块改为 Office Tool Plus 即可，这个东西早就有了，不是新版本才添加的。
3. 从 18 年开始，Office Tool Plus 的功能越来越完善，支持的版本、通道越来越多，以及 KMS 三年以来基本功能一直没变化，请问又如何得出 KMS 不好用的理由？
4. 每一次大版本的更新，都代表着一种尝试和努力，而且我也做不到每个人都喜欢的样子，我只能说，7 版本已经定了，不会再改了，新的 8 版本大局已定，也只会做小修改，如果问题不是很大的话，这些东西是不会随便就改的。

如果有什么想说的，欢迎随时评论，否则24小时后关闭此 issue

**Comment by HookSafe** [comment]
我没有说kms不好用。真心感觉18年下半年那段时间的版本很好用，你修复bug完全可以弹出一个更新提示。新版本解决了什么问题，而不是强制更新。只是我已经建议，刚刚我的语气不是太好，因为要急着用2016。给你道个歉，对不起。
这个软件你免费做了那么久 还是很感谢你。

**Comment by chiyi4488** [comment]
@HookSafe 那你2016有安裝成功嗎？

**Comment by chiyi4488** [comment]
> 如果有什么想说的，欢迎随时评论，否则24小时后关闭此 issue ( @YerongAI )

關閉 Issue
