### ISSUE TITLE
请问这是什么情况啊

### ISSUE THREAD

**Issue by lfscqk67** [YerongAI/Office-Tool#129]
![image](https://user-images.githubusercontent.com/37235589/85223428-b5ff7a80-b3f5-11ea-9197-a4a49b1c5c68.png)

**Comment by YerongAI** [comment]
请通过邮件、群组等任意方式，将此注册表导出并发送给我们：计算机\HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Office\ClickToRun

**Comment by YerongAI** [comment]
已测试，确定这是 V7 版本才有的问题，V8 暂未发现问题，按照维护计划，需要较长时间才会针对 V7 修复此问题，但这问题不影响 Office 的安装与激活，如有需要，可以去工具箱内清除一遍 Office 再执行部署操作。

如无其他疑问，此 issue 将于 24 小时后关闭。
