### ISSUE TITLE
[ASK]otp的下载网站打不开了，error 522

### ISSUE THREAD

**Issue by H-WU** [YerongAI/Office-Tool#134]
otp的下载网站打不开了，error 522

**Comment by YerongAI** [comment]
请提供一下您的地理位置（大概）以及网络服务提供商信息

**Comment by H-WU** [comment]
> 请提供一下您的地理位置（大概）以及网络服务提供商信息

广州，网络这方面不是很清楚，是校园网

**Comment by YerongAI** [comment]
可以通过百度搜索“IP”即可获得您的网络信息情况。

**Comment by H-WU** [comment]
> 可以通过百度搜索“IP”即可获得您的网络信息情况。

是我这边的问题。我切换到香港节点，就可以下载了。非常感谢！！
