### ISSUE TITLE
Windows10 2004版本 officeTool无法打开

### ISSUE THREAD

**Issue by Johnny5826** [YerongAI/Office-Tool#144]
如题

**Comment by chiyi4488** [comment]
請詳述問題。例如出現了什麼畫面？還是沒有出現任何畫面？

**Comment by Johnny5826** [comment]
> 請詳述問題。例如出現了什麼畫面？還是沒有出現任何畫面？

没有任何界面弹出，鼠标只是转圈，没有其他的现象

**Comment by chiyi4488** [comment]
請問你用的是哪個版本？v7? v8?

**Comment by Johnny5826** [comment]
> 請問你用的是哪個版本？v7? v8?

V7和V8版本都不行，都试过。
![image](https://user-images.githubusercontent.com/17289530/93038482-b4052a80-f677-11ea-8018-077bcb27a739.png)

**Comment by chiyi4488** [comment]
@YerongAI

**Comment by YerongAI** [comment]
这个问题我，我觉得只能是 .Net 框架本身的问题，程序在其他的计算机上都能很好的运行，偶尔有几个不行，我也不清楚。
