### ISSUE TITLE
[IDEA] 帮助页面在哪里可以翻译多国语

### ISSUE THREAD

**Issue by yaeyaya** [YerongAI/Office-Tool#146]
**Is your feature request related to a problem? Please describe.**
帮助页面目前只有中文和英文，没有其它多国语

**Describe the solution you'd like**
提供一个能翻译多国语的方法

**Describe alternatives you've considered**

**Additional context**
![image](https://user-images.githubusercontent.com/9144748/93666442-d69ca680-fab0-11ea-9a16-2b0c77e0eb5c.png)

**Comment by yaeyaya** [comment]
木有人响应么。。。

**Comment by chiyi4488** [comment]
（我有按讚啊😂😅😅

**Comment by YerongAI** [comment]
已将帮助文档放置于 GitHub 源代码中
