### ISSUE TITLE
[BUG] Windows 7上已无法安装

### ISSUE THREAD

**Issue by LittleDeng1** [YerongAI/Office-Tool#149]
**Describe the bug / 描述错误**
Windows 7系统下无法安装 报30201-39
32位 64都试过了
版本 16.0.13127.20408 / 20508
早期版本(近几个月的)似乎正常 但是都随着版本更新删掉了

**To Reproduce / 重现步骤**
Steps to reproduce the behavior / 重现步骤 :
1 全新安装原版系统 进入审核模式 跳过oobe
2 安装各种运行库
3 按截图选择安装office

**Expected behavior / 预期行为**
本该屁事没有

**Screenshots / 屏幕截图**
![IMG_20200928_130531](https://user-images.githubusercontent.com/62782358/94393098-be054e00-018c-11eb-8af3-3750b4b55dfa.jpg)
![IMG_20200928_130757](https://user-images.githubusercontent.com/62782358/94393105-c2316b80-018c-11eb-8103-d6808a27dce4.jpg)

**Version (please complete the following information) / 版本 (请填写以下信息):**
7.6.1.0 / 8.0.3.3

**Additional context / 备注、加以描述**

**Comment by YerongAI** [comment]
不慌，先看看[这个文章](https://www.coolhub.top/archives/11)，或许看完你就知道了。如果还有问题，再问。

**Comment by LittleDeng1** [comment]
@YerongAI 旧版确实能装
但是"otp的独特之处"说到 otp不检查当前系统 那么还有没有办法绕过限制装新版

**Comment by YerongAI** [comment]
啊忘了修改了，很早之前微软就修改过策略不允许 Win 7 安装了

**Comment by LittleDeng1** [comment]
@YerongAI 那这就是最后一个支持的版本了¿

**Comment by YerongAI** [comment]
博客里面提到的版本就是
