### ISSUE TITLE
使用office tool plus 单单安装project，导致原本office都消失了（被卸载？）

### ISSUE THREAD

**Issue by yangge8522424** [YerongAI/Office-Tool#154]
如题，华为magicbook主板自带19家庭版office（word，ppt，excel，OneNote），其实就是送了一个缩水版的office365。使用本工具选择安装2019版project，结果发现安装完成后，原本的office没有了。由于现在我已经重置电脑，无法没有之前的截图了，附上一张自带office的图，和使用工具的图。不知是我使用工具不对，还是确实存在这个问题。
![1](https://user-images.githubusercontent.com/52028119/97801978-56ef2380-1c7b-11eb-8077-4216188056c0.png)
![2](https://user-images.githubusercontent.com/52028119/97802001-7be39680-1c7b-11eb-97a9-b814041a32e4.png)

**Comment by yangge8522424** [comment]
> 如题，华为magicbook主板自带19家庭版office（word，ppt，excel，OneNote），其实就是送了一个缩水版的office365。使用本工具选择安装2019版project，结果发现安装完成后，原本的office没有了。由于现在我已经重置电脑，无法没有之前的截图了，附上一张自带office的图，和使用工具的图。不知是我使用工具不对，还是确实存在这个问题。
> ![1](https://user-images.githubusercontent.com/52028119/97801978-56ef2380-1c7b-11eb-8077-4216188056c0.png)
> ![2](https://user-images.githubusercontent.com/52028119/97802001-7be39680-1c7b-11eb-97a9-b814041a32e4.png)

使用的工具版本是v7.6

**Comment by YerongAI** [comment]
先给出我的判断：我认为这个跟 Office Tool Plus 是无关系的

1. Project 与 Office 是产品之间的关系，即类似于一个软件与另一个软件的关系，安装 Project 并不会直接将 Office 卸载。
2. Office Tool Plus V7 版本如果要卸载单个产品，其操作流程有点复杂，且不能与安装同时进行，因此基本上排除是由于使用不当导致误卸载的问题。

如果是笔记本自带的 Office 2019 学生版，建议前往 [Microsoft 订阅管理网站](https://stores.office.com/myaccount/home.aspx) 查看自己的产品，若没有，则代表没有赠送或绑定未成功。

如果笔记本并没有自带 Office，或绑定未成功，则您之前打开的 Office 应该和 [Office 在线版](https://portal.office.com/) 差不多，这是个免费版本，谁都可以使用。

若您认为您电脑上的 Office 订阅没有成功绑定，建议您联系华为客服处理。

若您觉得此事无关紧要，要继续使用 Office 和 Project，请导航至 [Yerong の小窝](https://coolhub.top/) 查阅相关教程。

**Comment by yangge8522424** [comment]
> 先给出我的判断：我认为这个跟 Office Tool Plus 是无关系的
> 
> 1. Project 与 Office 是产品之间的关系，即类似于一个软件与另一个软件的关系，安装 Project 并不会直接将 Office 卸载。
> 2. Office Tool Plus V7 版本如果要卸载单个产品，其操作流程有点复杂，且不能与安装同时进行，因此基本上排除是由于使用不当导致误卸载的问题。
> 
> 如果是笔记本自带的 Office 2019 学生版，建议前往 [Microsoft 订阅管理网站](https://stores.office.com/myaccount/home.aspx) 查看自己的产品，若没有，则代表没有赠送或绑定未成功。
> 
> 如果笔记本并没有自带 Office，或绑定未成功，则您之前打开的 Office 应该和 [Office 在线版](https://portal.office.com/) 差不多，这是个免费版本，谁都可以使用。
> 
> 若您认为您电脑上的 Office 订阅没有成功绑定，建议您联系华为客服处理。
> 
> 若您觉得此事无关紧要，要继续使用 Office 和 Project，请导航至 [Yerong の小窝](https://coolhub.top/) 查阅相关教程。

了解。我的office是正版已激活的，这个应该是随电脑主板绑定的那种。已附图。
我感觉是工具使用不当，误卸了自带的office。我再试试安装project看看。

**Comment by yangge8522424** [comment]
> > 先给出我的判断：我认为这个跟 Office Tool Plus 是无关系的
> > 
> > 1. Project 与 Office 是产品之间的关系，即类似于一个软件与另一个软件的关系，安装 Project 并不会直接将 Office 卸载。
> > 2. Office Tool Plus V7 版本如果要卸载单个产品，其操作流程有点复杂，且不能与安装同时进行，因此基本上排除是由于使用不当导致误卸载的问题。
> > 
> > 如果是笔记本自带的 Office 2019 学生版，建议前往 [Microsoft 订阅管理网站](https://stores.office.com/myaccount/home.aspx) 查看自己的产品，若没有，则代表没有赠送或绑定未成功。
> > 如果笔记本并没有自带 Office，或绑定未成功，则您之前打开的 Office 应该和 [Office 在线版](https://portal.office.com/) 差不多，这是个免费版本，谁都可以使用。
> > 若您认为您电脑上的 Office 订阅没有成功绑定，建议您联系华为客服处理。
> > 若您觉得此事无关紧要，要继续使用 Office 和 Project，请导航至 [Yerong の小窝](https://coolhub.top/) 查阅相关教程。
> 
> 了解。我的office是正版已激活的，这个应该是随电脑主板绑定的那种。已附图。
> 我感觉是工具使用不当，误卸了自带的office。我再试试安装project看看。

![3](https://user-images.githubusercontent.com/52028119/97802846-3b871700-1c81-11eb-81b7-52adecb68664.png)

**Comment by yangge8522424** [comment]
![4](https://user-images.githubusercontent.com/52028119/97803005-3e363c00-1c82-11eb-97d1-eb5f7e340faf.png)

**Comment by YerongAI** [comment]
若无其他疑问，请关闭此 issue，或者等待三天后自动关闭。
