### ISSUE TITLE
Office Tools Plus Licence Install [BUG]

### ISSUE THREAD

**Issue by KrinalPatel889** [YerongAI/Office-Tool#157]
Office Tools Plus Latest Beta version Released on Date 07-11-2020 Does't show any Licenses to install.

I have attached screenshot.

![123](https://user-images.githubusercontent.com/74134574/98461974-b480f400-21d6-11eb-9de9-d082dde10307.jpg)

**Comment by YerongAI** [comment]
Do you have Office installed on your computer?

**Comment by KrinalPatel889** [comment]
Yes office 2019 is installed on windows 7 64 bit.

On Sunday, November 8, 2020, Yerong <notifications@github.com> wrote:
> Do you have Office installed on your computer?
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub, or unsubscribe.<
https://ci6.googleusercontent.com/proxy/93W0PxEERbD3GgmChveAhuEPAP0qAyny8TLMIiBQHaVkELLzbSTrLgAvGLcndEvir_V3BsZ5mvwTsJI33x1uvIJ_N6i8R5n62BwULylgnvLxplezHdtkEjBA6QbChCCdozeLDU1a6whXzrx8W3_olyJz21NzgEtg-8aVuEyVR2kgtxEKj5u9Qu-u-MFgHUtjv30Jg-jUAFemRIyFENS0Iyons2VZeLqCFOPf6nLHCA=s0-d-e1-ft#https://github.com/notifications/beacon/ARVTILVP5IQ4UJP5QLBL6XDSOZTTHA5CNFSM4TOG5JGKYY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOFMQJCSY.gif>

**Comment by KrinalPatel889** [comment]
The Office tools plus v8.0.3.3 shows different licenses. But latest version
do not.

On Sunday, November 8, 2020, Krinal Patel <krinalpatel889@gmail.com> wrote:
> Yes office 2019 is installed on windows 7 64 bit.
>
> On Sunday, November 8, 2020, Yerong <notifications@github.com> wrote:
>> Do you have Office installed on your computer?
>>
>> —
>> You are receiving this because you authored the thread.
>> Reply to this email directly, view it on GitHub, or unsubscribe.<
https://ci6.googleusercontent.com/proxy/93W0PxEERbD3GgmChveAhuEPAP0qAyny8TLMIiBQHaVkELLzbSTrLgAvGLcndEvir_V3BsZ5mvwTsJI33x1uvIJ_N6i8R5n62BwULylgnvLxplezHdtkEjBA6QbChCCdozeLDU1a6whXzrx8W3_olyJz21NzgEtg-8aVuEyVR2kgtxEKj5u9Qu-u-MFgHUtjv30Jg-jUAFemRIyFENS0Iyons2VZeLqCFOPf6nLHCA=s0-d-e1-ft#https://github.com/notifications/beacon/ARVTILVP5IQ4UJP5QLBL6XDSOZTTHA5CNFSM4TOG5JGKYY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOFMQJCSY.gif>

**Comment by YerongAI** [comment]
Try to press F5 on Office Tool Plus, it work?

**Comment by KrinalPatel889** [comment]
Error Reading office information.

Object references not set to an instance of object.

On Sunday, November 8, 2020, Yerong <notifications@github.com> wrote:
> Try to press F5 on Office Tool Plus, it work?
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub, or unsubscribe.<
https://ci5.googleusercontent.com/proxy/xWMd5OEnqXB1ixO2koBrLzBLGWcHBcbSBoKEog4AvYeab3lAL2UFMTinzuwZ8VJiS7atypLFMd8GVTYnchqtktanpSxl18rB7K0P-iOnslxLH4dNwl90-OPGSZ_Cc6S_2_mFkpiPI8hpqKpqa6JBC9e5E-pT-nJ_NN5Ef9F96-wGumcEPaP6yEXxSjVrcMtHrPNmYplFq3z6FJDVk-oLWxkcJ5XW60p38LrqqbBUgQ=s0-d-e1-ft#https://github.com/notifications/beacon/ARVTILXIVOCULUTLYHTV52DSOZUQFA5CNFSM4TOG5JGKYY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOFMQJITI.gif>

**Comment by YerongAI** [comment]
Please export and send the registry key `HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Office\ClickToRun` to my [email](mailto:yerong@coolhub.top), thank you!

**Comment by YerongAI** [comment]
Issues fixed, the new version will release at next month.
There is a temporarily solution for you:

Change `HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Office\ClickToRun\Configuration\ClientCulture` value to `en-us` (lowercase).

Thanks for your feedback.
