### ISSUE TITLE
[ASK] 本项目可否支持 Chocolatey？

### ISSUE THREAD

**Issue by Sciencmine** [YerongAI/Office-Tool#172]
[Chocolatey](https://www.chocolatey.org/) 是一个 Windows 下的包管理器，里面的包主要是社区维护的。
可以像使用 `apt-get` 一样使用 `choco` 命令来管理软件。

本项目可否作为 Chocolatey 包发布？

**Comment by YerongAI** [comment]
Office Tool Plus 软件偏向于绿色便携，并且设计上并未兼容本地安装使用，可能存在卸载后有数据残留或自动更新无法工作的问题，如果不是很需要，不必上架 Chocolatey
