### ISSUE TITLE
[疑似BUG]无法正常下载/部署 office/project/visio 2016 批量授权版

### ISSUE THREAD

**Issue by fuchanghao** [YerongAI/Office-Tool#176]
使用OTP部署office/project/visio 2016 批量授权版时无法正确下载文件。

一度怀疑是网络问题但是在法国服务器上进行测试问题依旧，服务器DNS为google dns。

同样网络环境下载/部署 office 2019 批量授权版则没有这个问题。

这是我的配置：

[![rnyu8K.png](https://s3.ax1x.com/2020/12/14/rnyu8K.png)](https://imgchr.com/i/rnyu8K)
[![rn6iJP.png](https://s3.ax1x.com/2020/12/14/rn6iJP.png)](https://imgchr.com/i/rn6iJP)

部署版本为16.0.5095.1000 (2020年12月的更新版)

更新信息：https://support.microsoft.com/en-us/help/4583521/december-2020-updates-for-microsoft-office

不知道这个是不是我的设置问题，我切换了所有的通道都试过了，依旧是无法下载文件。

**Comment by YerongAI** [comment]
Office 更新信息[在此处](https://docs.microsoft.com/zh-cn/officeupdates/update-history-microsoft365-apps-by-date)，您所提供的 Office 更新日志是针对 MSI 版本的，并非 C2R 版本。

其次 Office 2016/2019/365 共用一个安装包，除了在通道上有点小差别之外。

目前最新的稳定版为 `16.0.13426.20332` (当前通道)

如果你不了解 Click To Run 版本的 Office，建议前往[微软官方网站](https://aka.ms/odt)了解学习，避免下次再提问这种问题。

**Comment by fuchanghao** [comment]
了解完毕了C2R的区别了，不过ODT是支持office 2013 C2R的下载的，而且2013还在支持中，但是我用OTP没看到2013的选项，是因为某些原因选择了刻意不支持吗？

**Comment by YerongAI** [comment]
> 了解完毕了C2R的区别了，不过ODT是支持office 2013 C2R的下载的，而且2013还在支持中，但是我用OTP没看到2013的选项，是因为某些原因选择了刻意不支持吗？

Office 2013 所使用的 Office Deployment Tool (部署工具) 与最新版的并非同一个版本，并且由于某些 API 无法获得，暂时做不到完美的支持。某些功能的支持与目前最新的 ODT 有所区别，因此并没有打算支持 2013.

**Comment by fuchanghao** [comment]
> > 了解完毕了C2R的区别了，不过ODT是支持office 2013 C2R的下载的，而且2013还在支持中，但是我用OTP没看到2013的选项，是因为某些原因选择了刻意不支持吗？
> 
> Office 2013 所使用的 Office Deployment Tool (部署工具) 与最新版的并非同一个版本，并且由于某些 API 无法获得，暂时做不到完美的支持。某些功能的支持与目前最新的 ODT 有所区别，因此并没有打算支持 2013.

OK，了解了。
