### ISSUE TITLE
[BUG] 已安装提示的 runtime 还是提示需要安装

### ISSUE THREAD

**Issue by Vixb1122** [YerongAI/Office-Tool#177]
**Describe the bug / 描述错误**
已安装提示的 runtime 还是提示需要安装

**To Reproduce / 重现步骤**
Steps to reproduce the behavior / 重现步骤 :
1. 打开 Office Tool Plus
2. 按提示跳转到 https://aka.ms/dotnet-core-applaunch?missing_runtime=true&arch=x86&rid=win10-x86&apphost_version=5.0.0&gui=true 安装运行时
3. 安装成功后，重新打开 Office Tool Plus
4. 依旧提示未安装

**Expected behavior / 预期行为**
安装成功后正常运行

**Screenshots / 屏幕截图**
![image](https://user-images.githubusercontent.com/17810492/103050277-e9060f00-45ce-11eb-93d6-dd11504375ed.png)
![image](https://user-images.githubusercontent.com/17810492/103050378-223e7f00-45cf-11eb-8104-18efd19c55b5.png)

**Version (please complete the following information) / 版本 (请填写以下信息):**
 - Version 8.1.1.1

**Comment by YerongAI** [comment]
您好
根据你所提供的反馈，您安装的是 .NET 5 的 64 位，程序需要的是 32 位，并非 64 位，请重新下载并安装。

与此同时，您是否使用 Visual Studio 进行 .NET 的开发？

`如果是，请卸载您所安装的 Desktop Runtime，该 Runtime 会与 Visual Studio 自带的开发组件冲突。`

如果不是，您可以忽略此条建议。

**Comment by Vixb1122** [comment]
你意思是 OTP 和 VS 不能同时用吗？

**Comment by YerongAI** [comment]
> 你意思是 OTP 和 VS 不能同时用吗？

如果您使用 Visual Studio 进行 .NET 5 的开发，则您不需要额外安装 .NET Desktop Runtime 框架，VS 开发环境自带此框架。

这是我们的建议：

1. 尝试卸载您安装的 Desktop Runtime，检查是否可以打开 Office Tool Plus
2. 如果遵循步骤一后无法打开 Office Tool Plus，请使用[此链接](https://dotnet.microsoft.com/download/dotnet/thank-you/runtime-desktop-5.0.1-windows-x86-installer)下载并安装 .NET 5 Desktop Runtime

如果有其他问题，欢迎您的反馈。
