### ISSUE TITLE
[BUG] Win7虚拟机中双击主程序无反应；已安装所需framework，双击主程序后弹出UAC，点击“是”后程序没有正常运行；Ver8.1

### ISSUE THREAD

**Issue by Minecrafter-Pythoner** [YerongAI/Office-Tool#181]
**Describe the bug / 描述错误**
清楚地描述错误的样子(错误讯息)

**To Reproduce / 重现步骤**
Steps to reproduce the behavior / 重现步骤 :

**Expected behavior / 预期行为**
清楚地描述它正常执行时应有的反应

**Screenshots / 屏幕截图**
如果可以，请将该画面截图下来、上传。

**Version (please complete the following information) / 版本 (请填写以下信息):**
 - Version [e.g. 6.0.0]

**Additional context / 备注、加以描述**
你可以在这里填写你还想要说的话。

**Comment by YerongAI** [comment]
您好

针对 Windows 7，微软已停止其主流支持，因此我们的软件也不再以 Windows 7 为主要的兼容目标。

建议迁移到 Windows 10 以获得更好的使用体验。
