### ISSUE TITLE
[BUG] 无法侦测到 Scoop 安装的 dotnet Core SDK

### ISSUE THREAD

**Issue by SettingDust** [YerongAI/Office-Tool#182]
**Describe the bug / 描述错误**
无法侦测到 Scoop 安装的 dotnet Core SDK

**Screenshots / 屏幕截图**
![image](https://user-images.githubusercontent.com/19922286/103458774-3fe5b400-4d46-11eb-8ab0-87cf6c5e780d.png)
![image](https://user-images.githubusercontent.com/19922286/103458797-79b6ba80-4d46-11eb-8a5e-527946ce9714.png)

**Version (please complete the following information) / 版本 (请填写以下信息):**
 -  8.1.1.1

**Comment by YerongAI** [comment]
为了避免可能的错误，请勿使用包管理工具安装 SDK 或 Runtime 等重要文件，避免出现错误。

针对您的问题，请卸载并使用传统方式安装 [.NET Desktop Runtime x86](https://dotnet.microsoft.com/download/dotnet/thank-you/runtime-desktop-5.0.0-windows-x86-installer)

**Comment by panda361** [comment]
本软件需要的是X86（32位）的.Net Desktop 5.0 Runtime。如果安装64位的.Net SDK则不能使用，麻烦检查一下（我刚才用winget发现装的是64位的😮）

**Comment by YerongAI** [comment]
> 本软件需要的是X86（32位）的.Net Desktop 5.0 Runtime。如果安装64位的.Net SDK则不能使用，麻烦检查一下（我刚才用winget发现装的是64位的😮）

软件基于 32 位的 SDK 制作，故需要 32 位的运行库，并且由于某些技术上的原因，Office Tool Plus 暂时只提供 32 位版本，不提供 64 位版本。

**Comment by DongDong-Guo** [comment]
> > 本软件需要的是X86（32位）的.Net Desktop 5.0 Runtime。如果安装64位的.Net SDK则不能使用，麻烦检查一下（我刚才用winget发现装的是64位的😮）
> 
> 软件基于 32 位的 SDK 制作，故需要 32 位的运行库，并且由于某些技术上的原因，Office Tool Plus 暂时只提供 32 位版本，不提供 64 位版本。
我的win10 安装不了运行库啊，系统找不到路径
