### ISSUE TITLE
[BUG] Cropped string "Microsoft Office профессиональный плюс 2019"

### ISSUE THREAD

**Issue by iDolmatov** [YerongAI/Office-Tool#190]
**Describe the bug / 描述错误**
清楚地描述错误的样子(错误讯息)

Check long string for first setup (deploy) menu. %ProPlus2019Retail% translated name out of string.

**To Reproduce / 重现步骤**
Steps to reproduce the behavior / 重现步骤 :
1. Open OTP and select Russian (русский) language
2. Click on 'Установить Office'
3. Read "Microsoft Office профессиональный плюс 201"

**Expected behavior / 预期行为**
清楚地描述它正常执行时应有的反应
"Microsoft Office профессиональный плюс 2019"

**Screenshots / 屏幕截图**
如果可以，请将该画面截图下来、上传。

![image](https://user-images.githubusercontent.com/19782385/104973246-ef44ab00-5a15-11eb-8727-96556d4d0562.png)

**Version (please complete the following information) / 版本 (请填写以下信息):**
 - Version [e.g. 6.0.0]
8.1.1.3

**Additional context / 备注、加以描述**
你可以在这里填写你还想要说的话。

Not broken language string (as see). 
There are some minor translation flaws, but they are not relevant to this line.

**Comment by YerongAI** [comment]
Issue fixed, thank you for your report.
