### ISSUE TITLE
[BUG]刚下载的安装包，显示安装文件错误。

### ISSUE THREAD

**Issue by 937802505** [YerongAI/Office-Tool#192]
**Describe the bug / 描述错误**
清楚地描述错误的样子(错误讯息)

**To Reproduce / 重现步骤**
Steps to reproduce the behavior / 重现步骤 :

**Expected behavior / 预期行为**
清楚地描述它正常执行时应有的反应

**Screenshots / 屏幕截图**
如果可以，请将该画面截图下来、上传。

**Version (please complete the following information) / 版本 (请填写以下信息):**
 - Version [e.g. 6.0.0]

**Additional context / 备注、加以描述**
你可以在这里填写你还想要说的话。

**Comment by 937802505** [comment]
![image](https://user-images.githubusercontent.com/17605759/105273877-11d1f200-5bd7-11eb-92b3-9a23072ab482.png)

**Comment by YerongAI** [comment]
这可能是由于 Office CDN 问题导致的文件不匹配问题，您可以更换一个 DNS 后重试，或者从 [其他下载站点](https://otp.landian.vip/zh-cn/download.html) 下载 Office ISO 安装文件。

**Comment by YerongAI** [comment]
由于您长时间未有任何活动，我们将关闭该 issue，如有其他任何问题，欢迎再次反馈。
