### ISSUE TITLE
能否加入安装商店版本的office？

### ISSUE THREAD

**Issue by realcirno** [YerongAI/Office-Tool#194]
Win10商店版本的office感觉用起来相对较纯净，且卸载速度很快，现在从商店下载office自动跳转到网页，从网页下载的是C#桌面版本，能否通过软件安装商店版本的呢？

**Comment by YerongAI** [comment]
因为技术性问题，不能

**Comment by YerongAI** [comment]
[Wiki](https://github.com/YerongAI/Office-Tool/wiki) 中已更新教程，您现在可以手动安装应用商店版本的 Office.
