### ISSUE TITLE
[BUG] WD检测为病毒

### ISSUE THREAD

**Issue by tasty0tomato** [YerongAI/Office-Tool#205]
**Describe the bug / 描述错误**
WD将Office Tool Plus.exe Office Tool Plus.lnk 检测为病毒

**To Reproduce / 重现步骤**
病毒库版本：1.341.3580.0

**Expected behavior / 预期行为**
之前并没有被检测为病毒，可以正常使用，可能是新的软件版本或者新的病毒库版本触发了病毒误判？

**Version (please complete the following information) / 版本 (请填写以下信息):**
 - Version 8.2.2.3 升级至 8.2.2.5

**Comment by YerongAI** [comment]
您好

感谢您的反馈，我们已知晓此问题，将会尽快给微软提交误报反馈。

**Comment by tasty0tomato** [comment]
> 您好
> 
> 感谢您的反馈，我们已知晓此问题，将会尽快给微软提交误报反馈。

十分荣幸能够提供帮助，希望在问题解决后能关闭这个issue来提醒一下我。

**Comment by YerongAI** [comment]
微软已答复，此问题已解决。

这已经是第三次误报，之前都是主动发现并处理，因此并没有影响太多用户。

**Comment by YerongAI** [comment]
尽管上次我们已提交申请，微软答复已解决，但至今仍然报毒。

因此我们仍然需要几天时间去解决此问题，待问题真正解决后再关闭此 issue.

**Comment by ATAKing1023** [comment]
最新版下载提示木马：Trojan:Win32/Zpevdo.B，同样是Microsoft Defender，希望能解决

**Comment by YerongAI** [comment]
> 最新版下载提示木马：Trojan:Win32/Zpevdo.B，同样是Microsoft Defender，希望能解决

已发布最新 8.1.4.0 版本，此版本目前没有问题，可以下载使用。

**Comment by tasty0tomato** [comment]
病毒库版本：1.331.2162.0
问题已解决。

**Comment by chiyi4488** [comment]
事件記錄：台使用者(*@st.tc.edu.tw)於2021/2/25回報 Windows Defender 報毒(洛伊特木馬)。

**Comment by chiyi4488** [comment]
事件記錄：台使用者(*@st.tc.edu.tw)於2021/2/25回報 Windows Defender 報毒(洛伊特木馬)。

Office Tool Plus Taiwan<chiyi4488>

**Comment by chiyi4488** [comment]
Office Tool Plus Taiwan<chiyi4488>

**Comment by tasty0tomato** [comment]
之后如果有WD误报，我会更新这个issue，信息都在首条comment。

**Comment by YerongAI** [comment]
> 之后如果有WD误报，我会更新这个issue，信息都在首条comment。

您好，提交文件给 WD 需要一定的时间检查，并且病毒库更新也会有延迟，因此新版本刚发布的不久基本上都会被定义为病毒，如果需要，添加软件至白名单即可运行。

**Comment by YerongAI** [comment]
在此之前，请尝试更新 WD 的病毒库，然后取消白名单，再次检测看看。

**Comment by tasty0tomato** [comment]
8.2.2.5版本消失了。
