### ISSUE TITLE
[IDEA] Auto Shutdown/Sleep

### ISSUE THREAD

**Issue by imiimiimi** [YerongAI/Office-Tool#206]
Please add Auto Shutdown/Sleep feature like version 7.x

**Comment by YerongAI** [comment]
We will check and add it if possible. When finished, we will let you know.

Thanks for your suggestion.

**Comment by YerongAI** [comment]
Hello, we are pleased to inform you that the new features you have suggested will release in the next few days, thank you for your feedback.

**Comment by imiimiimi** [comment]
that's great 👌🏻
thanks a lot.
