### ISSUE TITLE
[IDEA] 增加修复0x80080005错误的功能

### ISSUE THREAD

**Issue by binsee** [YerongAI/Office-Tool#216]
**Feature description:**
> 目前发现 `服务器运行失败 (0x80080005)` 是由于KMS工具劫持 `SppExtComObj.exe` 程序，而未能正确运行导致，因此可以在Office Tool 中增加对此劫持的检测，并进行修复。
如运行 `C:\WINDOWS\system32\SppExtComObj.exe`，正常情况应会无任何提示的返回，失效的KMS劫持会导致弹窗报错如下图
![image](https://user-images.githubusercontent.com/5285894/111882547-34269700-89f1-11eb-81ab-072ca2f2bd0d.png)

**How it work?**
> 1. 检测注册表是否存在配置项 `HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows NT\CurrentVersion\Image File Execution Options\SppExtComObj.exe`
> 2. 如存在，则将其删除
> 3. 运行 `C:\WINDOWS\system32\SppExtComObj.exe`，如正常则会立刻返回，退出码应为`0`
> 4. 提示用户尝试再次激活

Technical Reference (if possible):
>

**Comment by YerongAI** [comment]
新版已添加此功能，将于不久后发布更新。

**Comment by YerongAI** [comment]
已发布更新

**Comment by SadPencil** [comment]
补充一下信息：HEU KMS Activator 会设置这个映像劫持
