### ISSUE TITLE
[BUG] 打不开

### ISSUE THREAD

**Issue by ss-buyi** [YerongAI/Office-Tool#217]
![Lily_1616540386](https://user-images.githubusercontent.com/54034316/112229886-c38cae00-8c6e-11eb-980c-d7352264df9d.png)

**Comment by iDolmatov** [comment]
Are the variables on your PC ok?
![image](https://user-images.githubusercontent.com/19782385/112230196-4f461080-8c56-11eb-9011-e8a86325c8de.png)

**Comment by ss-buyi** [comment]
Thanks, issue was settled. It's my own reason
