### ISSUE TITLE
Activation errors

### ISSUE THREAD

**Issue by Garfield69117** [YerongAI/Office-Tool#231]
Hi,
I get errors when I try to activate Office:
![Capture](https://user-images.githubusercontent.com/78594123/114010204-26339b80-9864-11eb-9e51-9381c3864e21.PNG)
Would you know how to fix them?
Many thanks for your help!

**Comment by iDolmatov** [comment]
As I understood, the wrong licenses for the activation method (Retail vs Volume).
Use second menu to check licenses and key.
![image](https://user-images.githubusercontent.com/19782385/114011840-1ecdbb80-987f-11eb-92f8-1586e3f41820.png)


See also https://github.com/YerongAI/Office-Tool/wiki/Office-Tool-Plus-Quick-Start#activate-office

**Comment by Garfield69117** [comment]
Thanks for your answer.

I have followed quick start step by step with no success :(

Both view installation ID and display license information return error:
![Capture2](https://user-images.githubusercontent.com/78594123/114017176-fdaf9f80-986b-11eb-96fa-141411da5640.PNG)

**Comment by YerongAI** [comment]
> Thanks for your answer.
> 
> I have followed quick start step by step with no success :(
> 
> Both view installation ID and display license information return error:
> ![Capture2](https://user-images.githubusercontent.com/78594123/114017176-fdaf9f80-986b-11eb-96fa-141411da5640.PNG)

Hi, do you using Windows Insider version?

**Comment by Garfield69117** [comment]
I'm giving assistance to somebody, how can I check?

**Comment by Garfield69117** [comment]
I'm afraid...
![Capture3](https://user-images.githubusercontent.com/78594123/114024393-48cdb080-9874-11eb-89be-cc2a83353273.PNG)
What should I do?

**Comment by YerongAI** [comment]
> I'm giving assistance to somebody, how can I check?

If he/she is using Windows Insider, there should be a info in the bottom right corner of the screen.

**Comment by Garfield69117** [comment]
Nothing on the desktop

**Comment by YerongAI** [comment]
> Nothing on the desktop

OK, I've had this problem before，, I tried everything on Office Tool Plus but keeping failed.

I have a quicker and safer way, use [KMS-VL-ALL](https://forums.mydigitallife.net/posts/838808/) instead at this time. 

Solving this problem is a bit of a hassle and I don't recommend wasting time with your friend.

**Comment by Garfield69117** [comment]
Seems activated with KMS-VL-ALL, many thanks!!

**Comment by YerongAI** [comment]
If no problems, you can close the issue.
