### ISSUE TITLE
[BUG] 当产品选择专业增强版-批量版时，安装模块选择 Office 部署工具则无法部署

### ISSUE THREAD

**Issue by DustinWin** [YerongAI/Office-Tool#232]
**Office Tool Plus 版本：** 8.1.5.3
**复现步骤：**
1. “产品”选择 “Office 专业增强版 2016/2019 - 批量版”，“安装模块”选择“Office 部署工具”，查看“开始部署”按钮显示效果；
2. “产品”选择 “Office 专业增强版 2016/2019”，“安装模块”选择“Office 部署工具”，查看“开始部署”按钮显示效果；
**预期结果：**
两种情况，“开始部署”按钮都能正常点击。
**实际结果：**
1. “开始部署”按钮为置灰状态，无法点击；
![QQ截图20210409014604](https://user-images.githubusercontent.com/45238096/114073110-80207980-98d5-11eb-8e69-3a49cbaa3fc3.png)
2. “开始部署”按钮可以正常点击。
![QQ截图20210409014646](https://user-images.githubusercontent.com/45238096/114073172-92021c80-98d5-11eb-9563-ce18ca227400.png)

**Comment by YerongAI** [comment]
Office Deployment Tool 并不支持部署 2016 所有批量版系列产品，此类产品必须通过 Office Tool Plus 安装模块部署。

**Comment by DustinWin** [comment]
> Office Deployment Tool 并不支持部署 2016 所有批量版系列产品，此类产品必须通过 Office Tool Plus 安装模块部署。

而且 2019 也是这样。

**Comment by YerongAI** [comment]
> > Office Deployment Tool 并不支持部署 2016 所有批量版系列产品，此类产品必须通过 Office Tool Plus 安装模块部署。
> 
> 而且 2019 也是这样。

Office 2019 需要使用专属通道部署。

**Comment by DustinWin** [comment]
> > > Office Deployment Tool 并不支持部署 2016 所有批量版系列产品，此类产品必须通过 Office Tool Plus 安装模块部署。
> > 
> > 
> > 而且 2019 也是这样。
> 
> Office 2019 需要使用专属通道部署。

好的，谢谢解答！
