### ISSUE TITLE
[BUG] Bugs on version 8.1.5.6 and 8.1.5.7

### ISSUE THREAD

**Issue by YerongAI** [YerongAI/Office-Tool#235]
**Office Tool Plus Version, e.g. 8.1.0.0 (20/12/2020)**
> 8.1.5.5 - 8.1.5.7

**Operating System, e.g. Windows 10 20H2 or Windows 7 SP1**
> Any

**Error description (required):**
> Can't deploy proofing tools or partial languages. Can't deploy Visio 2019 or Project 2019 on Office 2019 channel. Can't get the correct Office version for Windows 7.

*Reproduction steps (suggested):*
Add language and set to deploy proofing tool only, click "start deploy".

*Screenshot (suggested):*
None.

*Additional information (optional):*
These issues was solved in version 8.1.5.13.

**Comment by iDolmatov** [comment]
Check after automatic update.
Alternative: https://otp.landian.vip/en-us/download.html 

> V8.1.5.14
> 
> Note: please download and install .NET 5.0 Desktop Runtime x86 before upgrade Office Tool Plus from V8.0 to V8.1!
> 
> So sorry to make an big mistake for the version 8.1.5.7, now we have fixed a lot of issues, please upgrade to the latest version! Thanks for your understanding and supporting! If the new version still has bugs, please send a feedback to us.
> 
> 1. Support new Office 2021 channel.
> 2. Modify Office 2021 applications.
> 3. Support to check exist products when adding a new product.
> 4. Support to set fallback language when using MatchOS.
> 5. Other issues fixed and performance improvement.
> 
> Recent update:
> 1. Fixed that Visio 2019 can not deploy at Office 2019 Preprtual Enterprise channel.
> 2. Fixed that Office Tool Plus can not get the correct Office version for Windows 7 users.
> 3. Fixed that Office Tool Plus can not deploy proofing tool or partial languages correctly.
