### ISSUE TITLE
[BUG] Create ISO file, replacing an in-use/mounted ISO, will cause application to crash

### ISSUE THREAD

**Issue by asheroto** [YerongAI/Office-Tool#236]
**Office Tool Plus Version, e.g. 8.1.0.0 (20/12/2020)**
8.1.5.6

**Operating System, e.g. Windows 10 20H2 or Windows 7 SP1**
Windows 10 20H2

**Error description (required):**
If you already have an ISO file, such as `Example.iso`, and it is in-use, such as being mounted as a drive (Open with -> Windows Explorer), and then you try to `Create ISO file`, answering `Yes` to replacing the file, then `Office Tool Plus.exe` will crash.

***Reproduction steps (suggested):***
see above

***Screenshot (suggested):***
no error message - just crashes and terminates process

***Additional information (optional):***

**Comment by YerongAI** [comment]
Issue fixed. Thank you.
