### ISSUE TITLE
[BUG] Display pictures and external content - settings are opposite of what they should be

### ISSUE THREAD

**Issue by asheroto** [YerongAI/Office-Tool#238]
**Office Tool Plus Version, e.g. 8.1.0.0 (20/12/2020)**
8.1.5.6

**Operating System, e.g. Windows 10 20H2 or Windows 7 SP1**
Windows 10 20H2

**Error description (required):**
See the screenshot below.

The title of the setting is "Display pictures and external content in HTML e-mail".  That means that if it's _Enabled_, then it _should_ display pictures and external content.  However, the description gives the opposite explanation.  I think the title is fine, but the description needs to be switched around.  You could change the title, but then it's confusing, because the **default** Outlook configuration has that DWORD value = 1.  So the description should read...

```
If you enable this policy setting, Outlook will display pictures and external content in HTML e-mail automatically.

If you disable this policy setting, Outlook will not automatically download content from external servers unless the sender is included in the Safe Senders list. Recipients can choose to download external content from untrusted senders on a message-by-message basis.
```

Currently, when enabled, the config returns:
```
<User Key="software\microsoft\office\16.0\outlook\options\mail" Name="blockextcontent" Value="1" Type="REG_DWORD" App="outlk16" Id="L_Blockexternalcontent" />
```

Currently, when disabled, the config returns:
```
<User Key="software\microsoft\office\16.0\outlook\options\mail" Name="blockextcontent" Value="0" Type="REG_DWORD" App="outlk16" Id="L_Blockexternalcontent" />
```

But the DWORD value needs to be = 0 when it's enabled, because the key is to "block external content".

*Reproduction steps (suggested):*
See above.

***Screenshot (suggested):***
![image](https://user-images.githubusercontent.com/49938263/114951670-7f7a6c80-9e1a-11eb-882f-5990fb1d6f85.png)

**Comment by YerongAI** [comment]
Actually I don't know too, application preferences are data provided by Microsoft.
See [Office Customize Tool](https://config.office.com/deploymentsettings)

I think you are right, But I'm not sure what to do about it.
