### ISSUE TITLE
[BUG] CreateShortcuts no longer an option in ODT

### ISSUE THREAD

**Issue by asheroto** [YerongAI/Office-Tool#239]
**Office Tool Plus Version, e.g. 8.1.0.0 (20/12/2020)**
8.1.2.6

**Operating System, e.g. Windows 10 20H2 or Windows 7 SP1**
Windows 10 20H2

**Error description (required):**
This option, at least with Office 2019, is not available with ODT anymore.

![image](https://user-images.githubusercontent.com/49938263/114952802-ae91dd80-9e1c-11eb-84e5-8105044372e1.png)

Although it adds it to the config, it has no effect.  No icons are created on the desktop.

It's no longer an option on the [official configuration guide](https://docs.microsoft.com/en-us/deployoffice/office-deployment-tool-configuration-options).  And [according to some search results](https://www.google.com/search?q=office+deployment+tool+CreateShortcuts), it appears this setting did exist but for some reason MS removed it.

**Comment by iDolmatov** [comment]
https://docs.microsoft.com/en-us/deployoffice/office-deployment-tool-configuration-options#piniconstotaskbar-property-part-of-property-element

> Defines whether shortcut icons for Office products are added to the Windows taskbar in Windows 7 and 8.1.

**Comment by YerongAI** [comment]
It creates desktop shortcuts from Office Tool Plus, not ODT, so when you install Office using ODT from the command line, nothing happens. You will need to install Office using Office Tool Plus to make it work.

**Comment by asheroto** [comment]
Ahh. Got it.

**Comment by YerongAI** [comment]
I am working on the other questions and will get back to you soon.

**Comment by iDolmatov** [comment]
Will it be blocked for ODT and unblocked if OTP is selected?

**Comment by YerongAI** [comment]
> Will it be blocked for ODT and unblocked if OTP is selected?

No matter what installation module you selected, just install using Office Tool Plus application, the option will work.

**Comment by iDolmatov** [comment]
Thanks.
