### ISSUE TITLE
[IDEA] 【许可证】建议增加删除指定许可证的功能

### ISSUE THREAD

**Issue by lc6464** [YerongAI/Office-Tool#244]
**Feature description:**
1. 增加删除指定许可证的功能（如指定 `SKU ID` 删除对应许可证）。
2. 最好还能增加一个删除全部未激活（`NOTIFICATIONS`）或不可用的许可证的功能。

**How it work?**
1. I don't know...
2. 删除 `NOTIFICATIONS` 的许可证可以通过分析 ospp.vbs 的输出来解决，但可能导致误删需要但尚未激活的许可证，删除不可用的许可证我就不清楚了。

Technical Reference (if possible):
> [Tools to Manage Volume Activation of Office](https://docs.microsoft.com/zh-cn/DeployOffice/vlactivation/tools-to-manage-volume-activation-of-office)

**Comment by YerongAI** [comment]
删除许可证功能在 C2R Installer 中有提供。
我之前就分析过，删除指定许可证是不可能的事情，于是我查看了 C2R Installer 的工作原理，发现其是删除所有许可证，再安装用户需要的许可证。

因此从技术角度上来说，删除指定许可证这个功能是不可能开发出来的。
但可以做出来安装指定许可证的功能。

**Comment by lc6464** [comment]
> 删除许可证功能在 C2R Installer 中有提供。
> 我之前就分析过，删除指定许可证是不可能的事情，于是我查看了 C2R Installer 的工作原理，发现其是删除所有许可证，再安装用户需要的许可证。
> 
> 因此从技术角度上来说，删除指定许可证这个功能是不可能开发出来的。
> 但可以做出来安装指定许可证的功能。

NOTIFICATIONS 状态的许可证可被删除，但 `0xC004F014` 我也确实没找到解决方案，我目前的解决方案如同您所描述的一样，清除全部许可证，安装需要的许可证，重新授权。
麻烦的点就在于真的很耗时。

**Comment by YerongAI** [comment]
除此之外，还有就是安装更多许可证从普通使用来说并不会增加 Office 的启动时间，不会使其运行变得缓慢，也不会占用额外的储存空间。相反的是，这类【没有被激活的许可证】并不会出现在 Office 的账户页面，即使在 Office Tool Plus 中查看激活信息时，也不会全部显示，只有点击查看许可证信息才会全部显示。

**Comment by lc6464** [comment]
主要问题就是如果哪个许可证出现了什么问题，那么多许可证找起来很麻烦。

**Comment by YerongAI** [comment]
许可证问题？我感觉这不是重点。一般情况下，出现激活问题的许可证通过【查看激活信息】时能直接显示出来，并且可以通过卸载其密钥将其置于隐藏（闲置）状态。

**Comment by lc6464** [comment]
有一个点不是很明白，为什么安装许可证时会安装那么多东西，都是一个系列的吗？还是说必须的，或者是别的原因？

**Comment by YerongAI** [comment]
> 有一个点不是很明白，为什么安装许可证时会安装那么多东西，都是一个系列的吗？还是说必须的，或者是别的原因？

按照微软设计，许可证是对应产品安装的，并且每个产品的许可证数量是不一样的。通常情况下，许可证不会全部使用到，但为了确保用户能顺利激活 Office，会直接将所有可能的许可证全部安装。

**Comment by lc6464** [comment]
> 按照微软设计，许可证是对应产品安装的，并且每个产品的许可证数量是不一样的。通常情况下，许可证不会全部使用到，但为了确保用户能顺利激活 Office，会直接将所有可能的许可证全部安装。

噢噢，原来如此，那这样安装多余的许可证确实是不可避免的了，感谢您的耐心答复。

**Comment by YerongAI** [comment]
> > 按照微软设计，许可证是对应产品安装的，并且每个产品的许可证数量是不一样的。通常情况下，许可证不会全部使用到，但为了确保用户能顺利激活 Office，会直接将所有可能的许可证全部安装。
> 
> 噢噢，原来如此，那这样安装多余的许可证确实是不可避免的了，感谢您的耐心答复。

是可以避免的，只是需要有一定的技术和知识，否则可能导致 Office 无法正常激活，但只要是正常使用的，这类问题不必过于关心。

**Comment by lc6464** [comment]
那您可以指导一下如何避免安装不必要的许可证吗？

**Comment by YerongAI** [comment]
> 那您可以指导一下如何避免安装不必要的许可证吗？

这个问题的答案你自己已经回答：
> 我目前的解决方案如同您所描述的一样，清除全部许可证，安装需要的许可证，重新授权。

**Comment by lc6464** [comment]
但经过测试还是出现了不可用的许可证。

**Comment by YerongAI** [comment]
![01](https://user-images.githubusercontent.com/44803668/115112954-6e686180-9fba-11eb-9986-2183404b4c49.png)
![02](https://user-images.githubusercontent.com/44803668/115112957-70322500-9fba-11eb-8468-514eb8c31d7b.png)

实际上这是可以的。清理后重新安装所需即可。

**Comment by lc6464** [comment]
![image](https://user-images.githubusercontent.com/64722907/115113079-036b5a80-9fbb-11eb-9857-b8d2d988d3d4.png)

**Comment by YerongAI** [comment]
使用安装指定许可证功能，而不是通过选择产品然后进行安装。

**Comment by lc6464** [comment]
> 使用安装指定许可证功能，而不是通过选择产品然后进行安装。

具体如何操作？

**Comment by YerongAI** [comment]
![04](https://user-images.githubusercontent.com/44803668/115113183-a2905200-9fbb-11eb-9b23-cae0dad99a86.png)
![03](https://user-images.githubusercontent.com/44803668/115113184-a3c17f00-9fbb-11eb-9f0e-d349e50e203d.png)

就这些

**Comment by lc6464** [comment]
感谢您，成功解决了。
