### ISSUE TITLE
[BUG] 重置指定许可证状态报文件不存在，实际上文件存在

### ISSUE THREAD

**Issue by lc6464** [YerongAI/Office-Tool#245]
**Office Tool Plus Version, e.g. 8.1.0.0 (20/12/2020)**
`8.1.5.15`

**Operating System, e.g. Windows 10 20H2 or Windows 7 SP1**
```
版本	Windows 10 企业版
版本号	21H1
操作系统内部版本	19043.906
体验	Windows Feature Experience Pack 120.2212.3530.0
```

**Error description (required):**
`{FileNotFound}OSPPREARM.EXE`

*Reproduction steps (suggested):*
1. 激活
2. 许可证管理
3. 重置指定许可证的状态

*Screenshot (suggested):*
![Bug 截图](https://user-images.githubusercontent.com/64722907/115112046-192a5100-9fb6-11eb-8078-1e1b7f93a615.png)

*Additional information (optional):*
![文件存在](https://user-images.githubusercontent.com/64722907/115112082-542c8480-9fb6-11eb-9b0e-8b43936fcb00.png)

**Comment by YerongAI** [comment]
Fixed，下个版本的更新已解决此问题。
