### ISSUE TITLE
[ASK] Windows10 x64系统安装使用问题

### ISSUE THREAD

**Issue by DoveBoy** [YerongAI/Office-Tool#246]
**Question:**
> Write down here
`Windows10 x64`系统下安装`OfficeToolPlus`，打开后提示需要安装`dotnet-desktop-runtime`，根据使用的操作系统下载的`dotnet-desktop-runtime-x64`却无法使用，必须下载`dotnet-desktop-runtime-x86`才能正常打开`OfficeToolPlus`，通过`scoop install`方式安装`OfficeToolPlus`和`dotnet-desktop-runtime-x64`也是同样的问题。下个版本中能否将`OfficeToolPlus`的`dotnet`依赖同时支持`x64`的？

**Comment by YerongAI** [comment]
由于微软的限制，x64 与 x86 的 Runtime 并不能互相兼容。

同时为了兼容 x86 设备，暂不打算迁移至 x64 平台。

**Comment by DoveBoy** [comment]
@YerongAI 能否同时增加x64和x86的支持

**Comment by YerongAI** [comment]
64 位版本无法使用迅雷下载引擎，这会直接降低 Office Tool Plus 的使用体验，因此不打算发布 x64 版本。
