### ISSUE TITLE
[BUG] 批量版无法开始部署

### ISSUE THREAD

**Issue by falomsc** [YerongAI/Office-Tool#253]
批量版开始部署按钮无法点击
![01](https://user-images.githubusercontent.com/56512990/119259974-4dbba900-bc03-11eb-95f3-2106cef5be78.jpg)
![02](https://user-images.githubusercontent.com/56512990/119259977-50b69980-bc03-11eb-91dc-b8c68a9994d3.jpg)

**Comment by YerongAI** [comment]
此问题已知晓。

新版本发布之前，请使用 Ctrl + Shift + D 强制部署。
