### ISSUE TITLE
無法選擇許可證

### ISSUE THREAD

**Issue by Fareeha-Takanashi** [YerongAI/Office-Tool#257]
沒有辦法選擇許可證來安裝。
OFFICE已經安裝了
![image](https://user-images.githubusercontent.com/51232545/119352548-68118780-bcd4-11eb-8ff2-a117f016ebeb.png)
![image](https://user-images.githubusercontent.com/51232545/119352572-6d6ed200-bcd4-11eb-8fc3-2d947ec2d3c6.png)
![image](https://user-images.githubusercontent.com/51232545/119352579-719aef80-bcd4-11eb-8c6f-cedef20b0587.png)
![image](https://user-images.githubusercontent.com/51232545/119352653-85465600-bcd4-11eb-830e-e4edfc5f631d.png)

**Comment by YerongAI** [comment]
由于使用 MSDN 下载的 Office 镜像为过旧版本，因此无法读取配置文件。

请卸载此版本的 Office，并通过 Office Tool Plus 来安装并激活 Office.
