### ISSUE TITLE
语言设置为外语时，说明按钮打开空白窗口，中文时有很多说明内容

### ISSUE THREAD

**Issue by yaeyaya** [YerongAI/Office-Tool#26]
测试选择了韩语和日语，均为空白。
![image](https://user-images.githubusercontent.com/9144748/61014403-da677000-a3b9-11e9-934c-e71d4e50afe4.png)

**Comment by chiyi4488** [comment]
因為沒人寫文檔

![image](https://user-images.githubusercontent.com/30853081/61020899-df381e00-a3d1-11e9-86f6-9aff2ca8f8fe.png)

**Comment by chiyi4488** [comment]
你可以跟 Yerong 問問說是否可以為韓語進行程式內的文檔翻譯。當然他答不答應我就不知道了。

此問題我先關閉囉!
