### ISSUE TITLE
[BUG] 

### ISSUE THREAD

**Issue by xiaofan007** [YerongAI/Office-Tool#262]
**Office Tool Plus Version, e.g. 8.1.0.0 (20/12/2020):**
> 8.2.2.3（2021/5/28）

**Operating System, e.g. Windows 10 20H2 or Windows 7 SP1:**
> Windows 10 20H2

**Error description (required):**

安装了office2021专业批量版 和 Visio2021专业批量版。 激活的时候，office2021激活成功，但是Visio2021激活失败

> ![image](https://user-images.githubusercontent.com/55171182/119950089-18310a00-bfcd-11eb-8b8b-c86ed072dba0.png)

> ![image](https://user-images.githubusercontent.com/55171182/119950022-064f6700-bfcd-11eb-9db2-1471caa54218.png)

*Reproduction steps (suggested):*

*Screenshot (suggested):*

*Additional information (optional):*

**Comment by YerongAI** [comment]
首先我想确认一下你的学校真的是清大吗？

**Comment by xiaofan007** [comment]
> 首先我想确认一下你的学校真的是清大吗？

清华附中
