### ISSUE TITLE
[BUG] 最新版Office Tool Plus v8.2.2.6卡巴斯基报毒

### ISSUE THREAD

**Issue by neo-he** [YerongAI/Office-Tool#267]
**Office Tool Plus Version, e.g. 8.1.0.0 (20/12/2020):**
> Office Tool Plus v8.2.2.6

**Operating System, e.g. Windows 10 20H2 or Windows 7 SP1:**
> Windows 10 21H1

**Error description (required):**
> Write down here

*Reproduction steps (suggested):*

*Screenshot (suggested):*

*Additional information (optional):*

**Comment by YerongAI** [comment]
已经通知 卡……卡巴了呢！
