### ISSUE TITLE
[BUG]运行程序报错没有.net运行时

### ISSUE THREAD

**Issue by wujinyi521** [YerongAI/Office-Tool#268]
**Office Tool Plus Version, e.g. 8.1.0.0 (20/12/2020):**
> Write down here

**Operating System, e.g. Windows 10 20H2 or Windows 7 SP1:**
> Write down here

**Error description (required):**
> 用Runme.bat可以运行，运行中也出现了此报错，并不影响部署。 

*Reproduction steps (suggested):*

*Screenshot (suggested):*
![image](https://user-images.githubusercontent.com/81548804/121785325-c3f07180-cbeb-11eb-86e5-520339d51f0b.png)

*Additional information (optional):*

**Comment by YerongAI** [comment]
如果使用 RunMe.bat 能运行，那就没什么大事；如果运行结果没什么问题的话，那大概应该也没什么事了，是吧？o ni jiang~

**Comment by wujinyi521** [comment]
> 如果使用 RunMe.bat 能运行，那就没什么大事；如果运行结果没什么问题的话，那大概应该也没什么事了，是吧？o ni jiang~

yysy,qs
thanks,imouto
