### ISSUE TITLE
语言设置为外语，更新检查仍然是中文

### ISSUE THREAD

**Issue by yaeyaya** [YerongAI/Office-Tool#27]
![image](https://user-images.githubusercontent.com/9144748/61197170-00687980-a706-11e9-948e-76268c78dea4.png)

**Comment by chiyi4488** [comment]
這是因為OTU跟OTP是兩個不同的程式。是這樣的OTP連結到伺服器後，就會確認是否有更新或檔案遺失，若有遺失、更新將會下載OTU。所以語言選項是沒有干係的。(我記得是這樣的)

因此，如果要讓OTU有其它語言的話，必須提交字串。但現在有個大問題，@YerongAI 好像遺失了OTU源代碼了....所以可想而知...................

此問題將關閉，如果對於OTU字串有任何問題，可以在下面回覆。
