### ISSUE TITLE
[ASK] msdn下载的office2019 pro plus版激活报错：0xC004F074

### ISSUE THREAD

**Issue by muse117** [YerongAI/Office-Tool#271]
**Question:**
> 激活的时候将零售版转成了vl版，安装了许可证和密钥，点击激活报错。请问这个该如何激活呢？
![微信截图_20210620164653](https://user-images.githubusercontent.com/9733486/122667960-45e22b00-d1e8-11eb-93bb-8c8b8bb5316d.png)

**Comment by YerongAI** [comment]
[点击查看解决办法（￣︶￣）↗　](https://www.coolhub.top/archives/13)

**Comment by muse117** [comment]
> [点击查看解决办法（￣︶￣）↗　](https://www.coolhub.top/archives/13)

修复之后，激活成功了，然后说许可证不是正版，这是什么原因呢？
![微信截图_20210620215200](https://user-images.githubusercontent.com/9733486/122676954-c74eb300-d212-11eb-9777-7436af74710c.png)

**Comment by YerongAI** [comment]
[点击此处查看原因和解决办法](https://www.coolhub.top/archives/122)

**Comment by muse117** [comment]
> [点击此处查看原因和解决办法](https://www.coolhub.top/archives/122)

重新安装了office2021批量版，已成功激活，无弹框了，果然是神器啊！加了一颗星，谢谢
![微信截图_20210621195449](https://user-images.githubusercontent.com/9733486/122758427-5d461480-d2cb-11eb-819c-795d15b8b7b5.png)
