### ISSUE TITLE
首页问候语多国语必须在更新检查完成后才会变更

### ISSUE THREAD

**Issue by yaeyaya** [YerongAI/Office-Tool#28]
每次更换语言，会自动检查更新，但是在更新完成之前，问候语都是沿用之前的语言，其它语言已经更换，等更新检查完成后，才会更新成新语言。

![image](https://user-images.githubusercontent.com/9144748/61197347-e67b6680-a706-11e9-8e96-21aa69f3dd9a.png)

![image](https://user-images.githubusercontent.com/9144748/61197354-fbf09080-a706-11e9-9e30-3ecb1200f18c.png)

**Comment by chiyi4488** [comment]
我之前也有遇過這個問題，當時是因應節慶，有使用OTA進行語言文件線上更新，但該字串也是類同這個狀況，會等很久後才會更新。

**Comment by YerongAI** [comment]
Issue fixed.
