### ISSUE TITLE
Office 21, Office21ProPlus2021VL_KMS_Client_AE edition 许可证说明: Office 21, VOLUME_KMSCLIENT channel 产品密钥的最后五个字符: 6F7TH 错误代码: 0xC004E015 错误信息: 软件授权服务报告许可证使用失败。[BUG] 

### ISSUE THREAD

**Issue by ViewWay** [YerongAI/Office-Tool#282]
**Office Tool Plus Version, e.g. 8.1.0.0 (20/12/2020):**
> Write down here

**Operating System, e.g. Windows 10 20H2 or Windows 7 SP1:**
> Write down here

**Error description (required):**
> Write down here

*Reproduction steps (suggested):*

*Screenshot (suggested):*

*Additional information (optional):*

**Comment by YerongAI** [comment]
https://www.coolhub.top/archives/13
