### ISSUE TITLE
无法定位程序输入点

### ISSUE THREAD

**Issue by BoBppy** [YerongAI/Office-Tool#283]
Windows8.1
打开程序或bat会显示

无法找到入口

'''
无法定位程序输入点 _invalid-parameter_noinfo_noreturn 于动态链接库 （程序释放目录）\ Office Tool Plus.exe
'''

由于这个动态链接库不是某dll而是exe所以我暂且蒙在古里（.net已装

**Comment by BoBppy** [comment]
先用v7苟一下了

**Comment by YerongAI** [comment]
8.1 就是这么多毛病，反正我也不知道怎么解决。建议 Windows Update 打满补丁

**Comment by BoBppy** [comment]
> 8.1 就是这么多毛病，反正我也不知道怎么解决。建议 Windows Update 打满补丁

装的是with update版，然后我测试7.6可以打开，8.0就不行啦（悲

**Comment by YerongAI** [comment]
此问题无法解决，归档处理。
