### ISSUE TITLE
[IDEA] 批量转换兼容性模式文件

### ISSUE THREAD

**Issue by lc6464** [YerongAI/Office-Tool#287]
**Feature description:**
- 批量转换兼容性模式的文件。

**How it work?**
- 就文件转换功能嘛，兼容性模式的就批量转换。

Technical Reference (if possible):
- 转换文件格式的 API 我倒是很熟了，但是这个转换兼容性模式的 API 是否存在我其实都不清楚。

**Comment by YerongAI** [comment]
那不就是把 doc 转换成 docx 吗？

**Comment by lc6464** [comment]
这还真不一样，.doc 文件是兼容性模式，.docx 有可能是兼容性模式，别人 WPS 创建的文件多半都是兼容性模式的（WPS 默认设置就是这样，要取消兼容性模式还得自己设置）。

**Comment by YerongAI** [comment]
那我还真不知道来着

**Comment by lc6464** [comment]
> 那我还真不知道来着

你可以用 WPS 创建一个文件，再用 Microsoft Office 打开试试，上面会显示兼容性模式。
或者你也可以创建一个 .doc 文件，上面也会显示兼容性模式。

**Comment by lc6464** [comment]
Microsoft Office 2010 到 Microsoft 365 均支持显示兼容性模式，并且可在“文件”选项卡下一键转换。
如果是 .doc，就转换为非兼容的 .docx，如果是兼容的 .docx，也是转换为非兼容的 .docx，如果 .doc 文件中包含 VBA 代码的话我暂时不是很清楚 Microsoft Office 的行为，还没有测试过（因为需要 VBA 的我都是保存为 .docm 等的）
.xls，.ppt 同理。

**Comment by YerongAI** [comment]
在经过多此尝试后依然无法成功，遂放弃此 IDEA，如果你有任何新的想法或者思路欢迎再次讨论。
