### ISSUE TITLE
[IDEA] IDM - like feature to resume paused downloads

### ISSUE THREAD

**Issue by Hidetoshi6721** [YerongAI/Office-Tool#290]
**Feature description:**
> An IDM - like feature to resume downloads even after closing of the app.

**How it work?**
> Open the app, download 1 GB of the Office setup files. Next day, on reopening, the download is available for resuming after 1 GB. 

I would like to thank the devs for creating this amazing utility. I would be really obliged if this feature is taken into consideration.

**Comment by YerongAI** [comment]
Hi, do you means the resume downloads? This feature is always available, for more information you can [view this](https://help.coolhub.top/deploy/#download-settings). You can have a try by yourself.

If any questions, please let me know.

**Comment by Hidetoshi6721** [comment]
> Hi, do you means the resume downloads? This feature is always available, for more information you can [view this](https://help.coolhub.top/deploy/#download-settings). You can have a try by yourself.
> 
> If any questions, please let me know.

No, I know that exists when using the Thunder engine.
Here's a better explanation :

What currently happens:
If I download some files, pause it and close the app. Next day when I resume, it restarts the download (as of now).

What should happen:
What I want it to do is remember how much files it downloaded, and resume from where it stopped, instead of starting over again (i.e. redownloading the files it already downloaded in Day 1).

**Comment by YerongAI** [comment]
Hi, I do the following things and no problem was found:

- Download Office with a config (Channel, architecture and version).
- Cancel download and close app.
- Reopen app and use the same config to start download.
- Office Tool Plus continue downloading the files.

Any problems? I tested it and nothing went wrong.
You can speak English, I can understand it. :)

**Comment by Hidetoshi6721** [comment]
Oh yes, it works. I'm sorry.
I think it didn't work previously because of an incorrect configuration the second day.
Thank you for your assistance.
