### ISSUE TITLE
请问office 部署工具在下载安装文件时，怎么显示进度条呢？ 

### ISSUE THREAD

**Issue by devount** [YerongAI/Office-Tool#294]
**Question:**
我在使用Office部署工具使用setup.exe /download XXXX.xml 命令时要怎么怎么获得下载的进度条呢？我看您的office-tool软件是可以显示下载进度条的，但我在官网未找到相关的配置。

**Comment by YerongAI** [comment]
你这不就是相当于问我苹果手机怎么运行安卓应用吗？

[窝只能给你这个](https://help.coolhub.top/zh-cn/deploy/#%E4%B8%8B%E8%BD%BD%E8%AE%BE%E7%BD%AE)

**Comment by devount** [comment]
> 你这不就是相当于问我苹果手机怎么运行安卓应用吗？
> 
> [窝只能给你这个](https://help.coolhub.top/zh-cn/deploy/#%E4%B8%8B%E8%BD%BD%E8%AE%BE%E7%BD%AE)
不好意思，我以为您的进度条是office部署工具的，那这么说，这个下载不是调用部署工具做的是吗？

**Comment by YerongAI** [comment]
> > 你这不就是相当于问我苹果手机怎么运行安卓应用吗？
> > [窝只能给你这个](https://help.coolhub.top/zh-cn/deploy/#%E4%B8%8B%E8%BD%BD%E8%AE%BE%E7%BD%AE)
> > 不好意思，我以为您的进度条是office部署工具的，那这么说，这个下载不是调用部署工具做的是吗？

正常的下载不会调用 Office 部署工具，用迅雷，这个当然有进度显示，除非你自己去选择 Office 部署工具，那必然没有进度。

**Comment by devount** [comment]
好的，明白了，多谢大佬



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2021年7月9日(周五) 下午5:27
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [YerongAI/Office-Tool] 请问office 部署工具在下载安装文件时，怎么显示进度条呢？  (#294)




   
你这不就是相当于问我苹果手机怎么运行安卓应用吗？
 窝只能给你这个
 不好意思，我以为您的进度条是office部署工具的，那这么说，这个下载不是调用部署工具做的是吗？
   
正常的下载不会调用 Office 部署工具，用迅雷，这个当然有进度显示，除非你自己去选择 Office 部署工具，那必然没有进度。
