### ISSUE TITLE
[BUG] 为啥8.xx版的运行要什么.net 5.0啥的啊,麻烦不麻烦.而且office安装时开发版Dogfood频道也没了

### ISSUE THREAD

**Issue by wutongskype** [YerongAI/Office-Tool#297]
[BUG] 为啥8.xx版的运行要什么.net 5.0啥的啊,麻烦不麻烦.而且office安装时开发版Dogfood频道也没了.整的人很懵逼...

**Comment by YerongAI** [comment]
1. 这是应用程序组件，是必须的。
2. Dogfood 通道需要前往设置开启高级选项以使用。
3. 建议前往[官方文档](https://help.coolhub.top/zh-cn/)学习更多信息

**Comment by YerongAI** [comment]
此问题已超过三天未有新回复，因此进行关闭处理。
