### ISSUE TITLE
[IDEA] Office-Tool如何使用代理服务器下载部署?能否添加个使用代理服务器的设置?

### ISSUE THREAD

**Issue by wutongskype** [YerongAI/Office-Tool#298]
[IDEA] Office-Tool如何使用代理服务器下载部署?能否添加个使用代理服务器的设置?

**Comment by YerongAI** [comment]
您好，迅雷支持设置代理服务器，除此之外，其他功能使用系统指定的代理服务器进行连接。

**Comment by YerongAI** [comment]
此问题已超过三天未有新回复，因此进行关闭处理。
