### ISSUE TITLE
我想用该工具更新office,该如何操作

### ISSUE THREAD

**Issue by ShayCormac1963** [YerongAI/Office-Tool#30]

**Comment by yaeyaya** [comment]
这个应该是Windows系统自带的更新吧，自动更新打开就好了呀

**Comment by chiyi4488** [comment]
基本上OTP是沒辦法為office更新的，但如果你真的想「強制更新」的話，你可以在［安裝］頁面中好像有個「移除現有的msi....」，勾選並進行安裝，工具將自動解除舊版本，安裝新版本

**Comment by YerongAI** [comment]
> 基本上OTP是沒辦法為office更新的，但如果你真的想「強制更新」的話，你可以在［安裝］頁面中好像有個「移除現有的msi....」，勾選並進行安裝，工具將自動解除舊版本，安裝新版本

你说的只是从 MSI 更新到 Click To Run 版本，而人家说的是 Click To Run 版本就地更新，这是两个完全不一样的概念。

**Comment by chiyi4488** [comment]
噢噢噢噢，我一直以為是一樣的
