### ISSUE TITLE
[ASK] 无法启动此程序，因为计算机中丢失 api-ms-win-crt-runtime-l1-1-0.dll。

### ISSUE THREAD

**Issue by PikuZheng** [YerongAI/Office-Tool#305]
**Question:**
> Write down here

全新安装 Windows Server 2012 R2 Datacenter且已安装Microsoft Windows Desktop Runtime 5.0.8 (x86) （注意不是X64）
运行otp8.2.3.3（包含框架）时报错：无法启动此程序，因为计算机中丢失 api-ms-win-crt-runtime-l1-1-0.dll。

**Comment by YerongAI** [comment]
请前往 Windows Update 将补丁打满

**Comment by PikuZheng** [comment]
在试了在试了（哭

**Comment by PikuZheng** [comment]
部署好了，但点击“激活”会卡住，过会儿程序崩溃。可能的原因：System.OutOfMemoryException
可以排除物理内存或虚拟内存不足。

**Comment by YerongAI** [comment]
> ~部署好了，但点击“激活”会卡住，过会儿程序崩溃。可能的原因：System.OutOfMemoryException 可以排除物理内存或虚拟内存不足。~
> 发现系统更新好并重启后，打开otp在主页加载了一会儿图标后，程序即崩溃。在加载完成前可以进具体功能。
> ![剪贴板01](https://user-images.githubusercontent.com/12579522/126570510-c689dd01-ab97-4dea-acf8-e551b94c5f44.jpg)
> ![剪贴板02](https://user-images.githubusercontent.com/12579522/126570524-5ba9e700-afce-4cb4-900d-01222c42ea64.jpg)

关于这个问题，把网络断开，然后打开程序即可，开完再恢复网络。

**Comment by YerongAI** [comment]
以及这个问题之前修复过一遍，具体就是背景图不再加载，但没有想到的是那些小图标也会引发问题，所以下一个版本还会继续优化这个问题。
