### ISSUE TITLE
[ASK] 能不能离线安装

### ISSUE THREAD

**Issue by danaquentin** [YerongAI/Office-Tool#307]
**Question:**
> Write down here
内网不能连互联网，能不能实现离线安装。
在外网下载好打包成iso镜像，但还是没法部署。

**Comment by YerongAI** [comment]
请查看[教程](https://help.coolhub.top/zh-cn/deploy/create-iso.html)并注意细节。

要完全离线安装，你需要添加语言并下载安装包，仅下载主体安装包是无法离线安装的。
