### ISSUE TITLE
[ASK] Win7 執行OTP&RunMe 無反應無報錯

### ISSUE THREAD

**Issue by Alex6357** [YerongAI/Office-Tool#309]
win7运行RunMe.bat和Office Tool Plus.exe都无反应，无报错，已安装net ，之前运行过一次，中间可能重装过系统

**Comment by Alex6357** [comment]
补充一下，上网找了个v7，安装net4，也打不开

**Comment by YerongAI** [comment]
建议使用 Windows Update 将系统更新到最新。

**Comment by Alex6357** [comment]
由于网络问题无法更新（无奈）

**Comment by YerongAI** [comment]
请至下载站点[下载文件](https://download.coolhub.top/Extensions/Win7_UpdatePack/)使用

**Comment by YerongAI** [comment]
此问题长期未收到回复，将做关闭处理，如有需要，请重新打开此 issue。如有其他问题，欢迎再次 open issue.
