### ISSUE TITLE
[BUG] Spanish language does not work

### ISSUE THREAD

**Issue by SkylarAstarot** [YerongAI/Office-Tool#314]
**Office Tool Plus 8.2.4.0 (27/7/2021)**

**Windows 10**

**Error description (required):**
> Spanish language does not work, the other languages do work.

*Reproduction steps (suggested):*
> Open Office Tools Plus, in Settings I try to choose Español (España) in Language Menu, but nothing happens.

*Screenshot (suggested):*
> https://i.imgur.com/Nu7gDBb.png

*Additional information (optional):*
> In the source code, from GitHub there is the file es-es.xaml, but it seems that the compilation does not take the file.

**Comment by YerongAI** [comment]
OK, I will fix it as fast as possible.

**Comment by YerongAI** [comment]
Fixed, please re-download Office Tool Plus. Thanks for your feedback!
