### ISSUE TITLE
[BUG] App does not detect DotNet versions after 5.0.0

### ISSUE THREAD

**Issue by asheroto** [YerongAI/Office-Tool#316]
**Office Tool Plus Version, e.g. 8.1.0.0 (20/12/2020):**
8.2.4.1

**Operating System, e.g. Windows 10 20H2 or Windows 7 SP1:**
Win 10 20H2

**Error description (required):**
I have DotNet 5.0.8.  The app does not detect versions after 5.0.0.

*Reproduction steps (suggested):*
Open app

*Screenshot (suggested):*
![image](https://user-images.githubusercontent.com/49938263/127763827-f9051fad-51e3-4a44-96ed-5d371e189858.png)

*Additional information (optional):*
![image](https://user-images.githubusercontent.com/49938263/127763847-2b8b351a-7e0b-4b59-bb6d-89bf360f29b2.png)

**Comment by pzhlkj6612** [comment]
Hi.

> ### .NET Runtime 5.0.8
> The .NET Runtime contains just the components needed to run a console app. Typically, you'd also install either the ASP.NET Core Runtime or **.NET Desktop Runtime**.

https://dotnet.microsoft.com/download/dotnet/5.0

**Comment by asheroto** [comment]
Ah, I installed the SDK version which includes the runtime.

**Comment by pzhlkj6612** [comment]
Is "Microsoft Windows Desktop Runtime - 5.0.8 (x86)" in the list of installed software?

**Comment by asheroto** [comment]
Yes, see "additional information" in first post.

**Comment by asheroto** [comment]
Oh, it doesn't say "desktop" but does say "runtime".

**Comment by YerongAI** [comment]
On our [official web page](https://otp.landian.vip/en-us/download.html), we marked that you can run Office Tool Plus using RunMe.bat if you download the runtime version. What's more, we explain which runtime we needed in the ReadMe.txt.

**Comment by asheroto** [comment]
I see.

I actually used Chocolatey to install dotnet since I do development as well:

```
choco install dotnet
```

Which installs the SDK + runtime. Guess the desktop runtime is not the same as runtime. 😑

Closing the issue. 😊

**Comment by YerongAI** [comment]
If you use Chocolatey to install runtime or SDK, the environment of path may not correct. To use it safety, it's recommend to use **Runtime version** of Office Tool Plus.

**Comment by pzhlkj6612** [comment]
Also, Chocolatey said in [Chocolatey Software | Microsoft .NET 5.0.8](https://community.chocolatey.org/packages/dotnet/5.0.8):

> ## Description
> ...
> The .NET Runtime is required to run .NET console applications. For running .NET desktop applications, install the [dotnet-desktopruntime](https://chocolatey.org/packages/dotnet-desktopruntime) package. ... For developing .NET applications, install the [dotnet-sdk](https://chocolatey.org/packages/dotnet-sdk) package.

So you may need to run `choco install dotnet-desktopruntime` to install the desktop runtime or run `choco install dotnet-sdk` to install the SDK (as you said, SDK includes runtimes).

And I think you should use the "Office_Tool_**with_runtime**_v8.\*.\*.\*.zip" package to simplify your operations and use OTP safely, as **YerongAI** said.

**Comment by asheroto** [comment]
Ahh, okay.  Thanks for the info! 😊
