### ISSUE TITLE
[ASK] 

### ISSUE THREAD

**Issue by Akane195** [YerongAI/Office-Tool#320]
**Question:**
> 出现错误，找不到所需文件，请检查安装源是否可访问 30183-44（403）

**Comment by YerongAI** [comment]
请使用工具箱收集 Office 安装日志。

**Comment by Akane195** [comment]
[Office_Log.zip](https://github.com/YerongAI/Office-Tool/files/6922010/Office_Log.zip)

**Comment by YerongAI** [comment]
- 请确保使用的是下载后安装。
- 请确保已添加语言。

**Comment by Akane195** [comment]
勾选后v64.cab下载卡0%

**Comment by Akane195** [comment]
提示任务超时

**Comment by YerongAI** [comment]
这是微软 CDN 问题，建议去[下载站点](https://otp.landian.vip/zh-cn/download.html#list)获取 ISO 文件使用。

**Comment by Akane195** [comment]
感谢
