### ISSUE TITLE
[IDEA]Office Online Server

### ISSUE THREAD

**Issue by UMB8998** [YerongAI/Office-Tool#326]
**Feature description:**
I'm looking for the option to have office online server, there is any way to get it?

**Comment by chiyi4488** [comment]
You can install it online without checking the "Install after download." box.
![image](https://user-images.githubusercontent.com/30853081/128438844-7602840d-6951-4dc4-a534-e5d2c2f69872.png)

**Comment by UMB8998** [comment]
@chiyi4488 thank you for the answer, but I think that I don't understand you, there is a type of office for windows server, after you install it you can have a office session on a website. The office is called Online Office Server or OOS.

https://docs.microsoft.com/en-us/officeonlineserver/office-online-server

**Comment by chiyi4488** [comment]
Unfortunately, Office Tool Plus is built on the basis of Office Deployment Tool (ODT) and its function is to facilitate users to deploy Office applications. There is no way to do what you said about Office Online Server.

**Comment by YerongAI** [comment]
> @chiyi4488 thank you for the answer, but I think that I don't understand you, there is a type of office for windows server, after you install it you can have a office session on a website. The office is called Online Office Server or OOS.
> 
> https://docs.microsoft.com/en-us/officeonlineserver/office-online-server

Hello, as I checked your link, I found "Office Online Server can be downloaded from the [Volume Licensing Service Center (VLSC)](https://go.microsoft.com/fwlink/p/?LinkId=256561)."

Maybe you should follow the steps to get your Office Online Server from VLSC. Office Tool Plus is based on Office Deployment Tool and used to deploy Retail and Volume edition of Office.

**Comment by UMB8998** [comment]
Ok, so I guess that I'm going to need to buy a Microsoft office bussines license to be able to download it, Anyway thank you!!
