### ISSUE TITLE
[ASK] 

### ISSUE THREAD

**Issue by AmidoNI2** [YerongAI/Office-Tool#329]
**Question:**
> Would it be possible to do the multiple installation on more than 1 machine on the network using the Office tool?  in what way???

**Comment by YerongAI** [comment]
Do you mean offline installation?

**Comment by AmidoNI2** [comment]
let's say that you download, and at the time of installation this installation can be sent to, for example, 100 to 400 desktop's

**Comment by YerongAI** [comment]
It's suggested to create an ISO file.

**Comment by YerongAI** [comment]
Because we doesn't receive any comments, we are now closing this issue.

If you have any questions, you can re-open it or open a new issue again.
