### ISSUE TITLE
It can't to activate the office

### ISSUE THREAD

**Issue by nomane-HUC** [YerongAI/Office-Tool#331]
thank this a good app , but it cant activate the microsoft 365.there is bug.

**Comment by nomane-HUC** [comment]
if it have the some KMS sever to on the app it better.

**Comment by nomane-HUC** [comment]
Товарищ, привет, ваша водородная бомба прибыла.[doge]

**Comment by chiyi4488** [comment]
microsoft 365 cannow use kms activate.

**Comment by nomane-HUC** [comment]
yes。but on the  one of prewer's KMS sever can't do it on the app.

**Comment by nomane-HUC** [comment]
my tool why is different the other's tool

**Comment by nomane-HUC** [comment]
if my office 2016 VL time it can't too

**Comment by chiyi4488** [comment]
Microsoft 365 is a subscription-based mechanism and cannot be activated in bulk via KMS. To find out which licenses cannot be activated through KMS, please see: https://www.coolhub.top/tech-articles/licenses.html.

If you find that a product that can be activated via KMS is not activated on your computer, it is possible that you have used cracked software.

**Comment by nomane-HUC** [comment]
2016 VL it fitst time can ,but only this time activate office.

**Comment by chiyi4488** [comment]
There is an option here, please click on it, copy the information and send it to me.

![image](https://user-images.githubusercontent.com/30853081/131238183-0f003989-853a-4fb2-8d74-45a1e4aafac7.png)

**Comment by nomane-HUC** [comment]
ok

**Comment by chiyi4488** [comment]
[Display activation infomation]

**Comment by nomane-HUC** [comment]
please wait

**Comment by nomane-HUC** [comment]
Office 激活处理
 

Office 16, Office16O365SmallBusPremR_SubTrial5 edition
许可证说明: Office 16, TIMEBASED_SUB channel
SKU ID: 090506fc-50f8-4c00-b8c7-91982a2a7c99
许可证状态:  ---未许可--- 
错误代码: 0xC004F014
错误信息: 软件许可服务报告产品密钥不可用。
 

Office 16, Office16O365SmallBusPremR_Subscription2 edition
许可证说明: Office 16, TIMEBASED_SUB channel
SKU ID: 0bc1dae4-6158-4a1c-a893-807665b934b2
许可证状态:  ---未许可--- 
错误代码: 0xC004F014
错误信息: 软件许可服务报告产品密钥不可用。
 

Office 16, Office16O365ProPlusR_Subscription1 edition
许可证说明: Office 16, TIMEBASED_SUB channel
SKU ID: 149dbce7-a48e-44db-8364-a53386cd4580
许可证状态:  ---未许可--- 
错误代码: 0xC004F014
错误信息: 软件许可服务报告产品密钥不可用。
 

Office 16, Office16O365SmallBusPremDemoR_BypassTrial365 edition
许可证说明: Office 16, RETAIL(Free) channel
SKU ID: 18c10ce7-c025-4615-993c-2e0c32f38efa
许可证状态:  ---未许可--- 
错误代码: 0xC004F014
错误信息: 软件许可服务报告产品密钥不可用。
 

Office 16, Office16O365SmallBusPremR_SubTrial2 edition
许可证说明: Office 16, TIMEBASED_SUB channel
SKU ID: 2030a84d-d6c7-4968-8cec-cf4737acc337
许可证状态:  ---未许可--- 
错误代码: 0xC004F014
错误信息: 软件许可服务报告产品密钥不可用。
 

Office 16, Office16O365ProPlusE5R_SubTrial edition
许可证说明: Office 16, TIMEBASED_SUB channel
SKU ID: 24fc428e-a37e-4996-ac66-8ea0304a152d
许可证状态:  ---未许可--- 
错误代码: 0xC004F014
错误信息: 软件许可服务报告产品密钥不可用。
 

Office 16, Office16O365ProPlusR_SubTrial2 edition
许可证说明: Office 16, TIMEBASED_SUB channel
SKU ID: 26b6a7ce-b174-40aa-a114-316aa56ba9fc
许可证状态:  ---未许可--- 
错误代码: 0xC004F014
错误信息: 软件许可服务报告产品密钥不可用。
 

Office 16, Office16O365HomePremR_Subscription5 edition
许可证说明: Office 16, TIMEBASED_SUB channel
SKU ID: 28f64a3f-cf84-46da-b1e8-2dfa7750e491
许可证状态:  ---未许可--- 
错误代码: 0xC004F014
错误信息: 软件许可服务报告产品密钥不可用。
 

Office 16, Office16O365EduCloudEDUR_Subscription edition
许可证说明: Office 16, TIMEBASED_SUB channel
SKU ID: 2f5c71b4-5b7a-4005-bb68-f9fac26f2ea3
许可证状态:  ---未许可--- 
错误代码: 0xC004F014
错误信息: 软件许可服务报告产品密钥不可用。
 

Office 16, Office16O365SmallBusPremR_SubTrial3 edition
许可证说明: Office 16, TIMEBASED_SUB channel
SKU ID: 2f756d47-e1b1-4d2a-922b-4d76f35d007d
许可证状态:  ---未许可--- 
错误代码: 0xC004F014
错误信息: 软件许可服务报告产品密钥不可用。
 

Office 16, Office16O365ProPlusDemoR_BypassTrial365 edition
许可证说明: Office 16, RETAIL(Free) channel
SKU ID: 35ec6e0e-2df4-4629-9ee3-d525e806b988
许可证状态:  ---未许可--- 
错误代码: 0xC004F014
错误信息: 软件许可服务报告产品密钥不可用。
 

Office 16, Office16O365ProPlusR_Grace edition
许可证说明: Office 16, RETAIL(Grace) channel
SKU ID: 3ad61e22-e4fe-497f-bdb1-3e51bd872173
许可证状态:  ---通知状态--- 
错误代码: 0xC004F009
错误信息: 软件授权服务报告宽限期已过。
产品密钥的最后五个字符: VMFTK
 

Office 16, Office16O365BusinessR_Grace edition
许可证说明: Office 16, RETAIL(Grace) channel
SKU ID: 3d0631e3-1091-416d-92a5-42f84a86d868
许可证状态:  ---通知状态--- 
错误代码: 0xC004F009
错误信息: 软件授权服务报告宽限期已过。
产品密钥的最后五个字符: 3RQ6B
 

Office 16, Office16O365ProPlusR_SubTrial1 edition
许可证说明: Office 16, TIMEBASED_SUB channel
SKU ID: 46d2c0bd-f912-4ddc-8e67-b90eadc3f83c
许可证状态:  ---未许可--- 
错误代码: 0xC004F014
错误信息: 软件许可服务报告产品密钥不可用。
 

Office 16, Office16O365HomePremR_SubTest5 edition
许可证说明: Office 16, TIMEBASED_SUB channel
SKU ID: 4c1d1588-3088-4796-b3b2-8935f3a0d886
许可证状态:  ---未许可--- 
错误代码: 0xC004F014
错误信息: 软件许可服务报告产品密钥不可用。
 

Office 16, Office16O365SmallBusPremR_Subscription4 edition
许可证说明: Office 16, TIMEBASED_SUB channel
SKU ID: 4cb3d290-d527-45c2-b079-26842762fdd3
许可证状态:  ---未许可--- 
错误代码: 0xC004F014
错误信息: 软件许可服务报告产品密钥不可用。
 

Office 16, Office16O365HomePremR_Subscription2 edition
许可证说明: Office 16, TIMEBASED_SUB channel
SKU ID: 52287aa3-9945-44d1-9046-7a3373666821
许可证状态:  ---未许可--- 
错误代码: 0xC004F014
错误信息: 软件许可服务报告产品密钥不可用。
 

Office 16, Office16O365HomePremR_Subscription1 edition
许可证说明: Office 16, TIMEBASED_SUB channel
SKU ID: 537ea5b5-7d50-4876-bd38-a53a77caca32
许可证状态:  ---未许可--- 
错误代码: 0xC004F014
错误信息: 软件许可服务报告产品密钥不可用。
 

Office 16, Office16O365BusinessR_Subscription edition
许可证说明: Office 16, TIMEBASED_SUB channel
SKU ID: 6337137e-7c07-4197-8986-bece6a76fc33
许可证状态:  ---未许可--- 
错误代码: 0xC004F014
错误信息: 软件许可服务报告产品密钥不可用。
 

Office 16, Office16O365SmallBusPremR_Subscription3 edition
许可证说明: Office 16, TIMEBASED_SUB channel
SKU ID: 65c607d5-e542-4f09-ad0b-40d6a88b2702
许可证状态:  ---未许可--- 
错误代码: 0xC004F014
错误信息: 软件许可服务报告产品密钥不可用。
 

Office 16, Office16O365SmallBusPremR_SubTrial1 edition
许可证说明: Office 16, TIMEBASED_SUB channel
SKU ID: 6ae65b85-e04e-4368-80a7-786d5766325e
许可证状态:  ---未许可--- 
错误代码: 0xC004F014
错误信息: 软件许可服务报告产品密钥不可用。
 

Office 16, Office16O365ProPlusR_Subscription4 edition
许可证说明: Office 16, TIMEBASED_SUB channel
SKU ID: 6e5db8a5-78e6-4953-b793-7422351afe88
许可证状态:  ---未许可--- 
错误代码: 0xC004F014
错误信息: 软件许可服务报告产品密钥不可用。
 

Office 16, Office16O365BusinessR_SubTest edition
许可证说明: Office 16, TIMEBASED_SUB channel
SKU ID: 742178ed-6b28-42dd-b3d7-b7c0ea78741b
许可证状态:  ---未许可--- 
错误代码: 0xC004F014
错误信息: 软件许可服务报告产品密钥不可用。
 

Office 16, Office16O365HomePremR_SubTest2 edition
许可证说明: Office 16, TIMEBASED_SUB channel
SKU ID: 77f47589-2212-4e3b-ad27-a900ce813837
许可证状态:  ---未许可--- 
错误代码: 0xC004F014
错误信息: 软件许可服务报告产品密钥不可用。
 

Office 16, Office16O365ProPlusE5R_Subscription edition
许可证说明: Office 16, TIMEBASED_SUB channel
SKU ID: 7984d9ed-81f9-4d50-913d-317ecd863065
许可证状态:  ---未许可--- 
错误代码: 0xC004F014
错误信息: 软件许可服务报告产品密钥不可用。
 

Office 16, Office16O365HomePremDemoR_BypassTrial365 edition
许可证说明: Office 16, RETAIL(Free) channel
SKU ID: 7ab38a1c-a803-4ca5-8ebb-f8786c4b4faa
许可证状态:  ---未许可--- 
错误代码: 0xC004F014
错误信息: 软件许可服务报告产品密钥不可用。
 

Office 16, Office16O365BusinessR_SubTrial edition
许可证说明: Office 16, TIMEBASED_SUB channel
SKU ID: 812837cb-040b-4829-8e22-15c4919feba4
许可证状态:  ---未许可--- 
错误代码: 0xC004F014
错误信息: 软件许可服务报告产品密钥不可用。
 

Office 16, Office16O365BusinessDemoR_BypassTrial365 edition
许可证说明: Office 16, RETAIL(Free) channel
SKU ID: 81d507d6-e729-436d-ad4d-fed2cbe4e566
许可证状态:  ---未许可--- 
错误代码: 0xC004F014
错误信息: 软件许可服务报告产品密钥不可用。
 

Office 16, Office16O365EduCloudEDUR_Grace edition
许可证说明: Office 16, RETAIL(Grace) channel
SKU ID: 81e676d5-b92c-4253-aa47-36a0ea89f5ed
许可证状态:  ---通知状态--- 
错误代码: 0xC004F009
错误信息: 软件授权服务报告宽限期已过。
产品密钥的最后五个字符: T3CPT
 

Office 16, Office16O365HomePremR_SubTrial3 edition
许可证说明: Office 16, TIMEBASED_SUB channel
SKU ID: 86af9220-9d6f-4575-bef0-619a9a6aa005
许可证状态:  ---未许可--- 
错误代码: 0xC004F014
错误信息: 软件许可服务报告产品密钥不可用。
 

Office 16, Office16O365SmallBusPremR_Subscription5 edition
许可证说明: Office 16, TIMEBASED_SUB channel
SKU ID: 881d148a-610e-4f0a-8985-3be4c0db2b09
许可证状态:  ---未许可--- 
错误代码: 0xC004F014
错误信息: 软件许可服务报告产品密钥不可用。
 

Office 16, Office16O365SmallBusPremR_Grace edition
许可证说明: Office 16, RETAIL(Grace) channel
SKU ID: 8ded1da3-5206-4540-a862-e8473b65d742
许可证状态:  ---通知状态--- 
错误代码: 0xC004F009
错误信息: 软件授权服务报告宽限期已过。
产品密钥的最后五个字符: H499R
 

Office 16, Office16O365HomePremR_SubTrial1 edition
许可证说明: Office 16, TIMEBASED_SUB channel
SKU ID: 951c0fe6-40a8-4400-8003-eec0686ffbc4
许可证状态:  ---未许可--- 
错误代码: 0xC004F014
错误信息: 软件许可服务报告产品密钥不可用。
 

Office 16, Office16O365HomePremR_SubTrial5 edition
许可证说明: Office 16, TIMEBASED_SUB channel
SKU ID: 95820f84-6e8c-4d22-b2ce-54953e9911bc
许可证状态:  ---未许可--- 
错误代码: 0xC004F014
错误信息: 软件许可服务报告产品密钥不可用。
 

Office 16, Office16O365HomePremR_SubTest3 edition
许可证说明: Office 16, TIMEBASED_SUB channel
SKU ID: 96353198-443e-479d-9e80-9a6d72fd1a99
许可证状态:  ---未许可--- 
错误代码: 0xC004F014
错误信息: 软件许可服务报告产品密钥不可用。
 

Office 16, Office16O365ProPlusR_Subscription3 edition
许可证说明: Office 16, TIMEBASED_SUB channel
SKU ID: a8119e32-b17c-4bd3-8950-7d1853f4b412
许可证状态:  ---未许可--- 
错误代码: 0xC004F014
错误信息: 软件许可服务报告产品密钥不可用。
 

Office 16, Office16O365HomePremR_SubTest1 edition
许可证说明: Office 16, TIMEBASED_SUB channel
SKU ID: a96f8dae-da54-4fad-bdc6-108da592707a
许可证状态:  ---未许可--- 
错误代码: 0xC004F014
错误信息: 软件许可服务报告产品密钥不可用。
 

Office 16, Office16O365HomePremR_SubTrial4 edition
许可证说明: Office 16, TIMEBASED_SUB channel
SKU ID: ae9d158f-9450-4a0c-8c80-dd973c58357c
许可证状态:  ---未许可--- 
错误代码: 0xC004F014
错误信息: 软件许可服务报告产品密钥不可用。
 

Office 16, Office16O365ProPlusEDUR_SubTrial edition
许可证说明: Office 16, TIMEBASED_SUB channel
SKU ID: b27b3d00-9a95-4fcd-a0c2-118cbd5e699b
许可证状态:  ---未许可--- 
错误代码: 0xC004F014
错误信息: 软件许可服务报告产品密钥不可用。
 

Office 16, Office16O365EduCloudEDUR_SubTrial edition
许可证说明: Office 16, TIMEBASED_SUB channel
SKU ID: b2f7ad5b-0e90-4ab7-9da5-d829a6ea3f1e
许可证状态:  ---未许可--- 
错误代码: 0xC004F014
错误信息: 软件许可服务报告产品密钥不可用。
 

Office 16, Office16O365HomePremR_SubTest4 edition
许可证说明: Office 16, TIMEBASED_SUB channel
SKU ID: b4af11be-5f94-4d8f-9844-ce0d5e0d8680
许可证状态:  ---未许可--- 
错误代码: 0xC004F014
错误信息: 软件许可服务报告产品密钥不可用。
 

Office 16, Office16O365HomePremR_Subscription4 edition
许可证说明: Office 16, TIMEBASED_SUB channel
SKU ID: b58a5943-16ea-420f-a611-7b230acd762c
许可证状态:  ---未许可--- 
错误代码: 0xC004F014
错误信息: 软件许可服务报告产品密钥不可用。
 

Office 16, Office16O365ProPlusR_SubTrial3 edition
许可证说明: Office 16, TIMEBASED_SUB channel
SKU ID: b6b47040-b38e-4be2-bf6a-dabf0c41540a
许可证状态:  ---未许可--- 
错误代码: 0xC004F014
错误信息: 软件许可服务报告产品密钥不可用。
 

Office 16, Office16O365SmallBusPremR_Subscription1 edition
许可证说明: Office 16, TIMEBASED_SUB channel
SKU ID: bacd4614-5bef-4a5e-bafc-de4c788037a2
许可证状态:  ---未许可--- 
错误代码: 0xC004F014
错误信息: 软件许可服务报告产品密钥不可用。
 

Office 16, Office16O365SmallBusPremR_SubTrial4 edition
许可证说明: Office 16, TIMEBASED_SUB channel
SKU ID: c5a706ac-9733-4061-8242-28eb639f1b29
许可证状态:  ---未许可--- 
错误代码: 0xC004F014
错误信息: 软件许可服务报告产品密钥不可用。
 

Office 16, Office16O365HomePremR_Subscription3 edition
许可证说明: Office 16, TIMEBASED_SUB channel
SKU ID: c85fe025-b033-4f41-936b-b121521ba1c1
许可证状态:  ---未许可--- 
错误代码: 0xC004F014
错误信息: 软件许可服务报告产品密钥不可用。
 

Office 16, Office16O365ProPlusEDUR_Subscription edition
许可证说明: Office 16, TIMEBASED_SUB channel
SKU ID: cbecb6f5-da49-4029-be25-5945ac9750b3
许可证状态:  ---未许可--- 
错误代码: 0xC004F014
错误信息: 软件许可服务报告产品密钥不可用。
 

Office 16, Office16O365HomePremR_Grace edition
许可证说明: Office 16, RETAIL(Grace) channel
SKU ID: d7279dd0-e175-49fe-a623-8fc2fc00afc4
许可证状态:  ---通知状态--- 
错误代码: 0xC004F009
错误信息: 软件授权服务报告宽限期已过。
产品密钥的最后五个字符: KHGM9
 

Office 16, Office16O365ProPlusR_SubTrial5 edition
许可证说明: Office 16, TIMEBASED_SUB channel
SKU ID: dfc5a8b0-e9fd-43f7-b4ca-d63f1e749711
许可证状态:  ---未许可--- 
错误代码: 0xC004F014
错误信息: 软件许可服务报告产品密钥不可用。
 

Office 16, Office16O365ProPlusR_Subscription2 edition
许可证说明: Office 16, TIMEBASED_SUB channel
SKU ID: e3dacc06-3bc2-4e13-8e59-8e05f3232325
许可证状态:  ---未许可--- 
错误代码: 0xC004F014
错误信息: 软件许可服务报告产品密钥不可用。
 

Office 16, Office16O365ProPlusR_SubTrial4 edition
许可证说明: Office 16, TIMEBASED_SUB channel
SKU ID: e538d623-c066-433d-a6b7-e0708b1fadf7
许可证状态:  ---未许可--- 
错误代码: 0xC004F014
错误信息: 软件许可服务报告产品密钥不可用。
 

Office 16, Office16O365HomePremR_SubTrial2 edition
许可证说明: Office 16, TIMEBASED_SUB channel
SKU ID: fb3540bc-a824-4c79-83da-6f6bd3ac6ccb
许可证状态:  ---未许可--- 
错误代码: 0xC004F014
错误信息: 软件许可服务报告产品密钥不可用。
 

Office 16, Office16O365ProPlusR_Subscription5 edition
许可证说明: Office 16, TIMEBASED_SUB channel
SKU ID: ff02e86c-fef0-4063-b39f-74275cddd7c3
许可证状态:  ---未许可--- 
错误代码: 0xC004F014
错误信息: 软件许可服务报告产品密钥不可用。

**Comment by nomane-HUC** [comment]
I can't open office

**Comment by chiyi4488** [comment]
抱歉，我剛剛有傳錯選項圖片，請點擊:查看激活資訊。

**Comment by nomane-HUC** [comment]
where is it

**Comment by chiyi4488** [comment]
![image](https://user-images.githubusercontent.com/30853081/131238701-ec4bfaf9-371e-4b36-8cbc-2682ec2694d0.png)

**Comment by YerongAI** [comment]
Check the [Wiki](https://github.com/YerongAI/Office-Tool/wiki) first.

**Comment by YerongAI** [comment]
There is no comments here, the issue will be closed, if needed please open a new issue.
