### ISSUE TITLE
[BUG] unable to create temporary path please check system variables and try again

### ISSUE THREAD

**Issue by Aholicknight** [YerongAI/Office-Tool#334]
![image](https://user-images.githubusercontent.com/7843719/132527071-d7ba53a8-0cd5-4e58-af94-745da5ad5341.png)

This happens when I try to run the program as admin or not admin. Is there any way that I can fix this? Thank you.

**Comment by YerongAI** [comment]
Normally, the TEMP and TMP variables should be **C:\Users\Username\AppData\Local\Temp**

**Comment by Aholicknight** [comment]
Sorry for the late reply. Here are my system variables. 
![image](https://user-images.githubusercontent.com/7843719/132979306-4997daaf-fb05-4d58-832e-6118ff154a02.png)

**Comment by Aholicknight** [comment]
> Normally, the TEMP and TMP variables should be **C:\Users\Username\AppData\Local\Temp**

![image](https://user-images.githubusercontent.com/7843719/132979332-41056fde-bc46-4884-9f73-fdab205745cf.png)

These are the system TEMP and TMP variables. Should I keep them as it is or change to `C:\Users\Username\AppData\Local\Temp` ?

**Comment by Aholicknight** [comment]
This is the local user temp path.
![image](https://user-images.githubusercontent.com/7843719/132979452-a7d6983b-796c-4fa6-b744-34ede6f2af0d.png)

Is there anything that I should change?

**Comment by Aholicknight** [comment]
Removing everything in the TEMP variables for my user and replacing it with `%USERPROFILE%\AppData\Local\Temp` fixed it.
