### ISSUE TITLE
ㅤ

### ISSUE THREAD

**Issue by byyxx128** [YerongAI/Office-Tool#336]
ㅤ

**Comment by YerongAI** [comment]
1. 在 64 位系统上将 64 位 Office 设置为默认是可行的，但这会导致 Office Tool Plus 内的文档转换无法正常工作，此功能依赖于 32 位的 Office。
2. x64 和 arm 版本是不需要的，arm 系统可以运行 32 位的应用程序，并且在 arm 系统上，安装 64 位的 Office 会自动指定为 arm 版本，微软尚在完善此功能中，还需继续等待。

**Comment by byyxx128** [comment]
咦，为什么文档转换还依赖32位Office呢？这个是无法解决的技术难题，还是暂时不想改呢？

P.S. 我怀着好奇心试了试，发现我64位Office可以正常使用文档转换功能——
![image](https://user-images.githubusercontent.com/20079289/133032772-725308b4-f3a8-4b33-8a88-29740958883e.png)
![image](https://user-images.githubusercontent.com/20079289/133032801-aa01f45d-db45-49f2-98c3-acb9be83ff3e.png)
![image](https://user-images.githubusercontent.com/20079289/133033026-1b419d0d-bea5-42ab-997b-b86a840c6295.png)

其实OTP的文档转换功能，我大概两年前就用过……而我一直就在用64位的Office，所以我还曾经纳闷来着，你们的帮助文件为什么说这个功能要依赖32位Office，很奇怪。不知道是不是您说的不是这个功能……

**Comment by byyxx128** [comment]
另外补充下，ARM可以先不管。不过 OTP 出一个 x64 的版本，这个还是有意义的，不是说 x86 能运行就没必要了，话不是这么说的。我说不出来技术上有什么好处，不过可能会显得 OTP 比较厉害？因为厉害的工具，基本都是32位和64位双版本的，或许为了满足处女座的需求……

当然这个也不是太刚需的东西，我就顺嘴提个建议。

**Comment by YerongAI** [comment]
x64 无法使用迅雷下载引擎，这会导致下载 Office 速度直接大打折扣，失去了最有意义的优势。
