### ISSUE TITLE
关于激活 未知错误 和 无法访问许可

### ISSUE THREAD

**Issue by xingzhenghang** [YerongAI/Office-Tool#34]
> 启动` Software Protection `服务。 提示未知错误 和 无法访问许可，是因为替换了` store `文件夹。 原始` store `文件夹，右键属性的权限列表中有` sppsvc `。 如果仅仅是覆盖其中文件的情况下，由于` Windows `的权限继承问题，` sppsvc `的权限不会被修改，所以` software protection `服务（也就是` sppsvc.exe `）可以正常操作` store `文件夹，从而服务正常启动，激活成功。 而如果直接替换` store `文件夹时，权限列表中是不会有` sppsvc `的，从而` software protection `服务无法对` store `文件夹进行操作，也就出现无法启动的错误，激活失败。

` Software Protection `服务无法启动，错误代码5（拒绝访问）

![avatar](http://s2.sinaimg.cn/bmiddle/671c54fegx6CpnbtOFP11&690)

***

### store文件夹为sppsvc服务增加权限:
store文件夹右键---属性---安全---组或用户名---编辑---添加---输入对象名称来选择（示例）(E)---下面的大方框里， 输入： 
`NT SERVICE\sppsvc`
确定之后，赋予sppsvc完全控制的权限。这样software protection服务就能正常启动，激活成功。
`几天前q里的office`

**Comment by YerongAI** [comment]
所以这个和 OTP 有什么关系呢，你想表达什么？

**Comment by xingzhenghang** [comment]
删3个dat无用

**Comment by xingzhenghang** [comment]
用上述方法解决了

**Comment by xingzhenghang** [comment]
希望加入说明

**Comment by YerongAI** [comment]
为了简化方法，是否可以直接删除文件夹？

**Comment by xingzhenghang** [comment]
尝试不行

**Comment by YerongAI** [comment]
检查过后，发现原来的权限设置中并未存在 sppsvc 的单独权限，因此问题根源可能不是 sppsvc 无权限导致，但为 sppsvc 单独添加权限确实可行，请问是否有其他的更好的解决办法能恢复到原来的权限？

**Comment by xingzhenghang** [comment]
可以尝试上传一个这个文件夹，让大家覆盖原文件夹

**Comment by xingzhenghang** [comment]
或在工具箱一栏修复中集成上述操作

**Comment by xingzhenghang** [comment]
不可以直接复制文件夹

**Comment by xingzhenghang** [comment]
试试这个我编的脚本[下载](www.xingzhenghang.tk/blog/fixoffice.bat)
