### ISSUE TITLE
[BUG] Error handling mechanism during document conversion

### ISSUE THREAD

**Issue by foresee-io** [YerongAI/Office-Tool#355]
**Office Tool Plus Version, e.g. 8.1.0.0 (20/12/2020):**
> 8.2.6.4 (21/09/28)

**Operating System, e.g. Windows 10 20H2 or Windows 7 SP1:**
> Windows 11 21H2 ver 22000.194

**Error description (required):**
> 转换中途出问题时，OTP 直接暂停工作并提示报错信息。有两点不妥之处
> 1. 已完成的转换不会被剔除列表，而且报错信息未指明是在哪个文件出了问题
> 2. 遇到错误直接暂停，需要用户多次干预，自动化效率大打折扣

*Reproduction steps (suggested):*

*Screenshot (suggested):*
![image](https://user-images.githubusercontent.com/32860378/136677945-d23e671f-0090-4a9e-805c-99eb7d0e6b47.png)

*Additional information (optional):*
> 建议
> 1. 将已完成的转换从列表移出（或单独列出“已完成列表”）
> 2. 报错信息指明是处理哪个文件时遇到了问题
> 3. 略过中途遇到的错误。把正常文件处理完后，交给用户集中统一处理。

**Comment by YerongAI** [comment]
由于此问题不再活跃，因此我们将会关闭此 issue。

针对此 issue 中提到的问题将会在后续版本中继续优化。
