### ISSUE TITLE
[BUG] Office 2021 SPLA not installing correctly

### ISSUE THREAD

**Issue by JustinHoeky** [YerongAI/Office-Tool#363]
**Office Tool Plus Version, e.g. 8.1.0.0 (20/12/2020):**
> Tested 8.2.6.4 and 8.2.7.0

**Operating System, e.g. Windows 10 20H2 or Windows 7 SP1:**
> Windows 10 Pro 21H1

**Error description (required):**
> None

**Reproduction steps (suggested):**
Add product
Select "Office LTSC Professional Plus 2021 (SPLA)"
Install
Start Deploy
Install (after download) takes about 10 seconds and something gets installed but it's not functioning
Installation folder is containing 5 files, but that's it

**Screenshot (suggested):**
https://i.imgur.com/bfTgscG.png

**Additional information (optional):**
For some reason the SPLA version of Office 2021 does not get installed correctly.
Tried 32bit and 64bit. Also provided license key with auth activate and accepting EULA

**Comment by YerongAI** [comment]
Hi, during our search, seems like SPLA products can not install now, even using MS official tools.

**Comment by JustinHoeky** [comment]
> As I know, MS does not have perfect installation data for the SPLA products, which is probably why you can't install it. Maybe we need to wait for MS to resolve this issue.

Will do, nothing else we can do then wait for Microsoft to fix it.
Would you mind leaving this "Bug" issue open, might other people come across the same issue?

**Comment by JustinHoeky** [comment]
> Np, just keep it opened if you want.

Great!
FYI, i've also informed our SPLA reseller of this issue. Hope they can contact Microsoft directly for a quicker fix.

**Comment by JustinHoeky** [comment]
Just got a reply from our SPLA reseller.

_"Office SPLA installation are not working at the moment, a lot of our customers are complaining about it. It might even be a far bigger issue then only SPLA installations but we have to wait it out untill Microsoft fixes it."_

**Comment by JustinHoeky** [comment]
Seems like Microsoft has almost fixed the problem after releasing it 1,5 month ago
"I just received the information that the problem is solved and will be included in the next release. The Microsoft support guy will call me when it's available." - [Source](https://docs.microsoft.com/en-us/answers/questions/596247/office-2021-ltsc-and-spla.html)

**Comment by YerongAI** [comment]
> Seems like Microsoft has almost fixed the problem after releasing it 1,5 month ago
> "I just received the information that the problem is solved and will be included in the next release. The Microsoft support guy will call me when it's available." - [Source](https://docs.microsoft.com/en-us/answers/questions/596247/office-2021-ltsc-and-spla.html)

Next release? It's available to download now? Or we still need to wait?

**Comment by JustinHoeky** [comment]
I've tested it a few hours ago, still not working. This time i'm even getting an error code stated in the source link.
Will try it next week and let you know.

**Comment by YerongAI** [comment]
> I've tested it a few hours ago, still not working. This time i'm even getting an error code stated in the source link.
> Will try it next week and let you know.

OK, also I will try by myself.

**Comment by YerongAI** [comment]
I found that Microsoft has fixed the problems, I and testing now. Version 16.0.14332.20190.

**Comment by YerongAI** [comment]
> I found that Microsoft has fixed the problems, I am testing now. Version 16.0.14332.20190.

Tested and everything is working properly.

**Comment by JustinHoeky** [comment]
> > I found that Microsoft has fixed the problems, I am testing now. Version 16.0.14332.20190.
> 
> Tested and everything is working properly.

What version did you install? I still get the same issue when installing Office 2021 SPLA

**Comment by YerongAI** [comment]
> I still get the same issue when installing Office 2021 SPLA For some reason i'm getting 16.0.14332.20176 on both 32 and 64bit versions

I think Microsoft will release the new version at next month.

For now, you can test it by the following steps:

- Open advanced features on settings.
- You will find **another channel** named Office 2021 Perpetual Enterprise,  use it.
- Change Installation module to Office Tool Plus instead Office Deployment Tool.
- Start deploy Office 2021 SPLA.

Everything will work properly.

![02](https://user-images.githubusercontent.com/44803668/143851781-a772ebc5-0827-438f-9933-85d8fb79cb3a.png)

**Comment by JustinHoeky** [comment]
> 

I tried your steps but sadly enough it still gives me the 16.0.14332.20176 version.
![image](https://user-images.githubusercontent.com/38039175/143853798-d7f455f4-bafd-4d6a-9e08-ca501162704e.png)

**Comment by JustinHoeky** [comment]
> 

This worked, thank you! Seems like it installed a Edge version but that's fine for me.
Will leave this open untill Microsoft has fixed it in their normal branch too.

**Comment by YerongAI** [comment]
New version released: 16.0.14332.20204.
