### ISSUE TITLE
[BUG] Windows 8.1 上出现运行错误

### ISSUE THREAD

**Issue by fuchanghao** [YerongAI/Office-Tool#377]
**Office Tool Plus Version, e.g. 8.1.0.0 (20/12/2020):**
> 8.2.8.0

**Operating System, e.g. Windows 10 20H2 or Windows 7 SP1:**
> Windows 8.1 x64 简体中文版

**Error description (required):**

> 在Windows 8.1上无法正常运行Office Tool Plus，已经确保了所说的事项。
> https://www.coolhub.top/archives/42
> 注3：Windows 7/8/8.1 需打满 Windows Update 补丁以确保稳定性和兼容性。
> 测试了无论是使用自带的框架，还是安装.NET 5.0.11 的x86框架，都无法正常运行。

*Reproduction steps (suggested):*

> 运行Office Tool Plus，点击部署按钮后就回出现错误提示框。

*Screenshot (suggested):*

[![IFPd6x.png](https://z3.ax1x.com/2021/11/02/IFPd6x.png)](https://imgtu.com/i/IFPd6x)
[![IFPwX6.png](https://z3.ax1x.com/2021/11/02/IFPwX6.png)](https://imgtu.com/i/IFPwX6)
[![IFPBnK.png](https://z3.ax1x.com/2021/11/02/IFPBnK.png)](https://imgtu.com/i/IFPBnK)

*Additional information (optional):*

**Comment by YerongAI** [comment]
已从云端修复此问题，现在打开 Office Tool Plus 应该不会再崩溃了。

**Comment by fuchanghao** [comment]
> 已从云端修复此问题，现在打开 Office Tool Plus 应该不会再崩溃了。

问题依旧，我特地虚拟机安装了一个全新的windows 8.1企业版并打上更新进行测试，依旧开启后就崩溃。

[![IAZFv4.png](https://z3.ax1x.com/2021/11/03/IAZFv4.png)](https://imgtu.com/i/IAZFv4)

**Comment by YerongAI** [comment]
> > 已从云端修复此问题，现在打开 Office Tool Plus 应该不会再崩溃了。
> 
> 问题依旧，我特地虚拟机安装了一个全新的windows 8.1企业版并打上更新进行测试，依旧开启后就崩溃。
> 
> [![IAZFv4.png](https://z3.ax1x.com/2021/11/03/IAZFv4.png)](https://imgtu.com/i/IAZFv4)
> 
> 
> 
> PS: 顺便使用Office 2013-2021 C2R Install 进行了Office 2021的部署测试，部署成功没有遇到问题。

现在再试试？

**Comment by YerongAI** [comment]
> > 已从云端修复此问题，现在打开 Office Tool Plus 应该不会再崩溃了。
> 
> 问题依旧，我特地虚拟机安装了一个全新的windows 8.1企业版并打上更新进行测试，依旧开启后就崩溃。
> 
> [![IAZFv4.png](https://camo.githubusercontent.com/b412d26dd2542233d63db34a51b36f30877bc6d07593ec7083e02b3bb3e44dcd/68747470733a2f2f7a332e617831782e636f6d2f323032312f31312f30332f49415a4676342e706e67)](https://imgtu.com/i/IAZFv4)
> 
> PS: 顺便使用Office 2013-2021 C2R Install 进行了Office 2021的部署测试，部署成功没有遇到问题。

Office Tool Plus 同样支持在 Windows 8.1 中安装 Office 2019/2021，只需要将安装模块从 Office 部署工具更改为 Office Tool Plus 即可。

**Comment by fuchanghao** [comment]
> > > 已从云端修复此问题，现在打开 Office Tool Plus 应该不会再崩溃了。
> > 
> > 
> > 问题依旧，我特地虚拟机安装了一个全新的windows 8.1企业版并打上更新进行测试，依旧开启后就崩溃。
> > [![IAZFv4.png](https://camo.githubusercontent.com/b412d26dd2542233d63db34a51b36f30877bc6d07593ec7083e02b3bb3e44dcd/68747470733a2f2f7a332e617831782e636f6d2f323032312f31312f30332f49415a4676342e706e67)](https://imgtu.com/i/IAZFv4)
> > PS: 顺便使用Office 2013-2021 C2R Install 进行了Office 2021的部署测试，部署成功没有遇到问题。
> 
> Office Tool Plus 同样支持在 Windows 8.1 中安装 Office 2019/2021，只需要将安装模块从 Office 部署工具更改为 Office Tool Plus 即可。

现在没问题了，能部署了。不过为何部署产品的时候无法直接选择MondoVolume了？只能部署MondoRetail后再添加Mondo Volume的证书？

**Comment by YerongAI** [comment]
> 现在没问题了，能部署了。不过为何部署产品的时候无法直接选择MondoVolume了？只能部署MondoRetail后再添加Mondo Volume的证书？

通常情况下我们不建议安装内部产品（MondoVolume 属于内部产品），但如果你依然需要安装，请从 Office Tool Plus 的设置中启用高级功能。

**Comment by YerongAI** [comment]
此问题标记为“已解决”，如果您还有任何问题，你可以提交新的 issue 或者继续此 issue.
