### ISSUE TITLE
.NET 6已发布，建议OTP使用.NET 6 runtime x64[IDEA] 

### ISSUE THREAD

**Issue by RobertChou** [YerongAI/Office-Tool#383]
**Feature description:**
> Write down here

.NET 6已发布，建议OTP使用.NET 6 runtime x64

**How it work?**
> Write down here

Technical Reference (if possible):
> Write down here

**Comment by YerongAI** [comment]
应用程序稳定性和可靠性还需要进一步测试，暂时不会升级 .NET 6.

**Comment by fuchanghao** [comment]
> 应用程序稳定性和可靠性还需要进一步测试，暂时不会升级 .NET 6.

.NET 6运行库运行office Tool已经测试了，向下兼容性目前没发现新的问题。但是遇到了运行库版本识别问题。

https://github.com/YerongAI/Office-Tool/issues/384

**Comment by byyxx128** [comment]
按照微软官方的说法，.NET 5 到 .NET 6 可以无缝迁移。当然这只是微软的一面之词，本着保险起见，可以先评估一番。
不过，.NET 5 是过渡产品，明年也就停止支持了，而 .NET 6 是 LTS 的，将于2024年停止支持。所以建议尽快评估并尽早迁移到 .NET 6 上。
同时，未来 .NET 7 发布后，也不要着急升级了，因为 .NET 7 又是过渡产品……下一个 LTS 是 .NET 8，将于2023年发布。

**Comment by byyxx128** [comment]
按照微软官方的说法，.NET 5 到 .NET 6 可以无缝迁移。当然这只是微软的一面之词，本着保险起见，可以先评估一番。

　　不过，.NET 5 是过渡产品，明年也就停止支持了，而 .NET 6 是 LTS 的，将于2024年停止支持。所以建议尽快评估并尽早迁移到 .NET 6 上。

　　同时，未来 .NET 7 发布后，也不要着急升级了，因为 .NET 7 又是过渡产品……下一个 LTS 是 .NET 8，将于2023年发布。

**Comment by YerongAI** [comment]
经过讨论后我们决定与今年年底前完成迁移到 .NET 6，届时将会发布相关更新，还请各位耐心等待。

**Comment by RobertChou** [comment]
> 
> 
> 经过讨论后我们决定与今年年底前完成迁移到 .NET 6，届时将会发布相关更新，还请各位耐心等待。

期待。

**Comment by byyxx128** [comment]
我说怎么没动静了……楼上的你怎么把这个 issue 给关了？赶紧打开……迁移完成前不要关闭。

**Comment by YerongAI** [comment]
> 我说怎么没动静了……楼上的你怎么把这个 issue 给关了？赶紧打开……迁移完成前不要关闭。

您好，有关迁移到 .NET 6 的动态还请查看 Discussions 呢。
