### ISSUE TITLE
[BUG] .NET运行库Microsoft.WindowsDesktop.App版本识别问题 

### ISSUE THREAD

**Issue by fuchanghao** [YerongAI/Office-Tool#384]
**Office Tool Plus Version, e.g. 8.1.0.0:**
>8.2.8.0

**Operating System, e.g. Windows 10 20H2 or Windows 7 SP1:**
> Windows 10 IoT 企业版 LTSC 2021

**Error description (required):**
> 安装.NET Desktop Runtime 6.0.0后无法运行，提示找不到运行库。

*Reproduction steps (suggested):*

前往
https://dotnet.microsoft.com/download/dotnet/6.0
下载x86版本安装后，提示运行库不存在

在“C:\Program Files (x86)\dotnet\shared\Microsoft.WindowsDesktop.App”下新建文件夹5.0.0后，将6.0.0下的文件复制到其中，再次运行，Office Tool工作正常。

也就是说，程序上是兼容.NET Desktop Runtime 6.0.0的，但是Office Tool在版本识别时，只识别有没有5.0.X的文件夹。

*Screenshot (suggested):*
报错信息：
[![IYRJjs.png](https://z3.ax1x.com/2021/11/09/IYRJjs.png)](https://imgtu.com/i/IYRJjs)

复制文件就工作正常了
[![IYRtun.png](https://z3.ax1x.com/2021/11/09/IYRtun.png)](https://imgtu.com/i/IYRtun)

*Additional information (optional):*

**Comment by YerongAI** [comment]
这里有两个问题需要理清楚的：

1. .NET 库的使用由 hostfxr.dll 决定，是这个文件决定了该如何查找以及使用哪个 Runtime.
2. 尽管通过这种方式能够让 Office Tool Plus 运行，但由于不确定因素，我们是完全不能保证每一个地方都是 100% 正常的。
3. Office Tool Plus 推荐的下载方式是下载包含 runtime （自带框架）的版本，该版本由于自带框架，与系统上安装的任何版本的框架无关。

尽管 .NET 6 已经发布，但我们仍然需要一点时间去评估并确定何时迁移到 .NET 6.

**Comment by YerongAI** [comment]
- 经最后讨论后，我们决定在今年年底完成从 .NET 5 到 6 的迁移，具体工作将会在晚些时候开展。
- .NET 版本的识别由 .NET Host 负责，因此程序是不能够自主识别并使用.NET Runtime 的。

此问题如果没有别的讨论，将会在 24 小时内关闭，如有别的疑问可以另开 issue 讨论。
