### ISSUE TITLE
[ASK] 为啥这次更新的是带框架的

### ISSUE THREAD

**Issue by lvzhenbo** [YerongAI/Office-Tool#386]
**Question:**
> 我装了.net5的x86框架，不能识别吗，为啥这次更新带了框架

**Comment by YerongAI** [comment]
请确保你安装的是 .NET Desktop Runtime，而不仅仅只是 .NET Runtime

**Comment by RobertChou** [comment]
> 请确保你安装的是 .NET Desktop Runtime，而不仅仅只是 .NET Runtime

我安装了5.12和6.0的desktop runtime，打开OTP自动更新后发现也带了框架。

**Comment by lvzhenbo** [comment]
![image](https://user-images.githubusercontent.com/32427677/141435931-17e977e8-a7f6-4f8a-bc29-926649b43932.png)
![image](https://user-images.githubusercontent.com/32427677/141437223-1efd7a1f-fef8-4dfb-8564-9f9e5bedd5cd.png)

**Comment by lvzhenbo** [comment]
> 请确保你安装的是 .NET Desktop Runtime，而不仅仅只是 .NET Runtime

并没有问题，装的是正确的

**Comment by YerongAI** [comment]
> > 请确保你安装的是 .NET Desktop Runtime，而不仅仅只是 .NET Runtime
> 
> 我安装了5.12和6.0的desktop runtime，打开OTP自动更新后发现也带了框架。

您好，我们调查后发现此功能需要在下个版本中才能生效，这意味着 8.2.8.2 版本以后的升级才会区分带框架与不带框架，此次更新如果误下载了带框架的还麻烦您手动处理一遍。

**Comment by YerongAI** [comment]
> > 请确保你安装的是 .NET Desktop Runtime，而不仅仅只是 .NET Runtime
> 
> 并没有问题，装的是正确的

您好，我们调查后发现此功能需要在下个版本中才能生效，这意味着 8.2.8.2 版本以后的升级才会区分带框架与不带框架，此次更新如果误下载了带框架的还麻烦您手动处理一遍。

**Comment by lvzhenbo** [comment]
OK，谢谢解答
