### ISSUE TITLE
[ASK]Office2021LTSC和VISO2021LTSC没有密钥 

### ISSUE THREAD

**Issue by ax003** [YerongAI/Office-Tool#387]
**Question:**
> Write down here
记得以前哪里能找到，麻烦提供一下

**Comment by YerongAI** [comment]
[点击此处查看](https://www.coolhub.top/tech-articles/products.html)

还有就是在程序的实际操作中不需要手动安装密钥，密钥默认随许可证一起安装。

**Comment by ax003** [comment]
> [点击此处查看](https://www.coolhub.top/tech-articles/products.html)
> 
> 还有就是在程序的实际操作中不需要手动安装密钥，密钥默认随许可证一起安装。

收到，找到命令了
