### ISSUE TITLE
[ASK] office 2021和visio2021 LSTC激活失败

### ISSUE THREAD

**Issue by fjibj** [YerongAI/Office-Tool#388]
Office 21, Office21Standard2021VL_KMS_Client_AE edition
•	许可证说明: Office 21, VOLUME_KMSCLIENT channel
•	产品密钥的最后五个字符: 78VT3
•	错误代码: 0x8007007B
•	错误信息: 文件名、目录名或卷标语法不正确。
 

 
Office 21, Office21VisioPro2021VL_KMS_Client_AE edition
•	许可证说明: Office 21, VOLUME_KMSCLIENT channel
•	产品密钥的最后五个字符: K2HT4
•	错误代码: 0x8007007B
•	错误信息: 文件名、目录名或卷标语法不正确。

**Comment by YerongAI** [comment]
请看教程

**Comment by Unknown78** [comment]
> Please see the tutorial

What does he did that was wrong?

**Comment by neveroldmilk** [comment]
> > Please see the tutorial
> 
> What does he did that was wrong?

There is no wrongdoing here in my opinion. My solution is to clean all the permits and reinstall them, and KMS activation finally works.
