### ISSUE TITLE
文件批量转换报错

### ISSUE THREAD

**Issue by carejoe** [YerongAI/Office-Tool#390]
文件批量转换报错
![11111](https://user-images.githubusercontent.com/66408838/142795630-4273e6ac-b564-44dd-b890-379f41ab8a2d.png)

**Comment by YerongAI** [comment]
您需要确保两个问题：

1. 安装的 Office 是最新版的且是 Click-to-Run 版本。
2. 64 位的 Office 不受支持，你必须要使用 32 位的 Office.

**Comment by YerongAI** [comment]
> 您需要确保两个问题：
> 
> 1. 安装的 Office 是最新版的且是 Click-to-Run 版本。
> 2. 64 位的 Office 不受支持，你必须要使用 32 位的 Office.

请问上述两点是否确认无误？是否有其他问题？

**Comment by YerongAI** [comment]
由于此 issue 长时间无人应答，已将其标记为关闭。

如有需要可以 reopen 或者 open new issue
