### ISSUE TITLE
[IDEA] Features Architectures

### ISSUE THREAD

**Issue by ChibiANUBIS** [YerongAI/Office-Tool#399]
Hello my dear !
For the ISO Deployement, can you add the architecture in the xml name, example : ConfigForISO32.xml and ConfigForISO64.xml for separate the two architecture with OfficeClientEdition=32 or 64
Because I love create ISO with your tool and I download always for x86 and x64 for offline installation.

Thanks for your great work,
Chibi

**Comment by YerongAI** [comment]
Hi,

Usually we suggested to create two ISO files which 32-bit and 64-bit instead of all-in-one.

If we created two config in one file, it's hard to select which one to use and install.

**Comment by ChibiANUBIS** [comment]
OK I see, I think suggest to separate on two folders, x86\Office and x64\Office.
Create a Autorun with this argument shell = InstallNow.cmd.
And the bat are this : check %processor_architecture% and %ARCH%\Office_Pro_Tools.exe /install

I going to try this :)

**Comment by YerongAI** [comment]
> OK I see, I think suggest to separate on two folders, x86\Office and x64\Office. Create a Autorun with this argument shell = InstallNow.cmd. And the bat are this : check %processor_architecture% and %ARCH%\Office_Pro_Tools.exe /install
> 
> I going to try this :)

I think you can create ISO by yourself.

As you know, write down argument shell, or create batch file into ISO. **Note: Office Tool Plus will pack up all files which includes in the Office Tool dictionary.**

Using the command to execute installation:

- For 32-bit: `Office Tool Plus.exe /loadConfig "%~dp0ConfigForISO.xml" /SourcePath "%~dp0" /edition 32`
- For 64-bit: `Office Tool Plus.exe /loadConfig "%~dp0ConfigForISO.xml" /SourcePath "%~dp0" /edition 64`

**Comment by ChibiANUBIS** [comment]
OK thanks :)

**Comment by ChibiANUBIS** [comment]
Something wrong...
![Sans titre](https://user-images.githubusercontent.com/71019664/145675441-a78288a6-991b-44ab-aca1-7cfe5cb0f021.png)

**Comment by ChibiANUBIS** [comment]
Here the cmd I use :

```
@echo OFF
pushd "%~dp0"

"Office Tool Plus.exe" /loadConfig "%~dp0ConfigForISO.xml" /SourcePath "%~dp0" /edition 64
exit``
```

**Comment by YerongAI** [comment]
Could you collect Office installation log and send to me?

**You can collect log with these steps:**

- Open Office Tool Plus on the client.
- Go to Toolbox page.
- Select collect Office installation log.

**Comment by YerongAI** [comment]
Oh I found the problems.

Sorry I had give you the wrong command, the right command is:

```batch
:: For 32-bit
"Office Tool Plus.exe" /loadConfig "%~dp0ConfigForISO.xml" /SourcePath %~dp0 /edition 32

:: For 64-bit
"Office Tool Plus.exe" /loadConfig "%~dp0ConfigForISO.xml" /SourcePath %~dp0 /edition 64
```

Just remove the quotes for **SourcePath**.

**Comment by ChibiANUBIS** [comment]
> Oh I found the problems.
> 
> Sorry I had give you the wrong command, the right command is:
> 
> ```batchfile
> :: For 32-bit
> "Office Tool Plus.exe" /loadConfig "%~dp0ConfigForISO.xml" /SourcePath %~dp0 /edition 32
> 
> :: For 64-bit
> "Office Tool Plus.exe" /loadConfig "%~dp0ConfigForISO.xml" /SourcePath %~dp0 /edition 64
> ```
> 
> Just remove the quotes for **SourcePath**.

Thanks my dear ! All is good now :)
