### ISSUE TITLE
[IDEA] 建议工具箱新增功能：强制开启新UI

### ISSUE THREAD

**Issue by fuchanghao** [YerongAI/Office-Tool#403]
**Feature description:**
> 在Windows 8.1上或者使用微软商店版Microsoft 365的时候，无法在设置中开启新的Ribbon UI。
> 在部署时的应用程序首选项中也没有看到相关选项。

**How it work?**
> 使用注册表强制修改相关数值可以实现开启和关闭UI。

Technical Reference (if possible):
> 开启UI参考的注册表信息如下：

```
Windows Registry Editor Version 5.00

[HKEY_CURRENT_USER\Software\Microsoft\Office\16.0\Common\ExperimentConfigs\ExternalFeatureOverrides]

[HKEY_CURRENT_USER\Software\Microsoft\Office\16.0\Common\ExperimentConfigs\ExternalFeatureOverrides\access]
"Microsoft.Office.UXPlatform.FluentSVRefresh"="true"
"Microsoft.Office.UXPlatform.RibbonTouchOptimization"="true"
"Microsoft.Office.UXPlatform.FluentSVRibbonOptionsMenu"="true"

[HKEY_CURRENT_USER\Software\Microsoft\Office\16.0\Common\ExperimentConfigs\ExternalFeatureOverrides\excel]
"Microsoft.Office.UXPlatform.FluentSVRefresh"="true"
"Microsoft.Office.UXPlatform.RibbonTouchOptimization"="true"
"Microsoft.Office.UXPlatform.FluentSVRibbonOptionsMenu"="true"

[HKEY_CURRENT_USER\Software\Microsoft\Office\16.0\Common\ExperimentConfigs\ExternalFeatureOverrides\onenote]
"Microsoft.Office.UXPlatform.FluentSVRefresh"="true"
"Microsoft.Office.UXPlatform.RibbonTouchOptimization"="true"
"Microsoft.Office.UXPlatform.FluentSVRibbonOptionsMenu"="true"

[HKEY_CURRENT_USER\Software\Microsoft\Office\16.0\Common\ExperimentConfigs\ExternalFeatureOverrides\outlook]
"Microsoft.Office.UXPlatform.FluentSVRefresh"="true"
"Microsoft.Office.UXPlatform.RibbonTouchOptimization"="true"
"Microsoft.Office.UXPlatform.FluentSVRibbonOptionsMenu"="true"

[HKEY_CURRENT_USER\Software\Microsoft\Office\16.0\Common\ExperimentConfigs\ExternalFeatureOverrides\powerpoint]
"Microsoft.Office.UXPlatform.FluentSVRefresh"="true"
"Microsoft.Office.UXPlatform.RibbonTouchOptimization"="true"
"Microsoft.Office.UXPlatform.FluentSVRibbonOptionsMenu"="true"

[HKEY_CURRENT_USER\Software\Microsoft\Office\16.0\Common\ExperimentConfigs\ExternalFeatureOverrides\project]
"Microsoft.Office.UXPlatform.FluentSVRefresh"="true"
"Microsoft.Office.UXPlatform.RibbonTouchOptimization"="true"
"Microsoft.Office.UXPlatform.FluentSVRibbonOptionsMenu"="true"

[HKEY_CURRENT_USER\Software\Microsoft\Office\16.0\Common\ExperimentConfigs\ExternalFeatureOverrides\publisher]
"Microsoft.Office.UXPlatform.FluentSVRefresh"="true"
"Microsoft.Office.UXPlatform.RibbonTouchOptimization"="true"
"Microsoft.Office.UXPlatform.FluentSVRibbonOptionsMenu"="true"

[HKEY_CURRENT_USER\Software\Microsoft\Office\16.0\Common\ExperimentConfigs\ExternalFeatureOverrides\visio]
"Microsoft.Office.UXPlatform.FluentSVRefresh"="true"
"Microsoft.Office.UXPlatform.RibbonTouchOptimization"="true"
"Microsoft.Office.UXPlatform.FluentSVRibbonOptionsMenu"="true"

[HKEY_CURRENT_USER\Software\Microsoft\Office\16.0\Common\ExperimentConfigs\ExternalFeatureOverrides\word]
"Microsoft.Office.UXPlatform.FluentSVRefresh"="true"
"Microsoft.Office.UXPlatform.RibbonTouchOptimization"="true"
"Microsoft.Office.UXPlatform.FluentSVRibbonOptionsMenu"="true"
```

**Comment by YerongAI** [comment]
我很早就知道这个，但其实想了想，加入工具箱的话好像还没有直接提供 REG 文件方便，REG 双击就可导入。

并且根据微软的策略的话，这个功能也是迟早会全部提供的，届时这个注册表就不需要自己导入了。

**Comment by fuchanghao** [comment]
> 我很早就知道这个，但其实想了想，加入工具箱的话好像还没有直接提供 REG 文件方便，REG 双击就可导入。
> 
> 并且根据微软的策略的话，这个功能也是迟早会全部提供的，届时这个注册表就不需要自己导入了。

https://www.coolhub.top/archives/187

这里测试结果有点奇怪，Windows 8.1下的C2R版本测试没有问题。
Windows 11上面的商店版 “将首选项应用于office程序”后并没有改成新的UI，注册表倒是没这个问题。



[![TnBLLR.png](https://s4.ax1x.com/2021/12/20/TnBLLR.png)](https://imgtu.com/i/TnBLLR)
[![TnBXe1.png](https://s4.ax1x.com/2021/12/20/TnBXe1.png)](https://imgtu.com/i/TnBXe1)
[![TnBvo6.png](https://s4.ax1x.com/2021/12/20/TnBvo6.png)](https://imgtu.com/i/TnBvo6)
[![TnBjdx.png](https://s4.ax1x.com/2021/12/20/TnBjdx.png)](https://imgtu.com/i/TnBjdx)


PS：https://www.coolhub.top/archives/115

顺便补充一下商店版本的信息，根据微软官方说明和一些实际测试。
商店版目前是没有x64版本的：https://answers.microsoft.com/en-us/msoffice/forum/all/office-desktop-apps-from-microsoft-store-are-32/f9fd27b9-e63c-4168-a96a-c35ba2b0b6f5
16001 - Office 2016 只有x86版
16031 - Office 2019 有x86和arm64版
16051 - Micorosft 365 有x86和arm64版
不过根据导入的证书不同，微软会在商店更新的时候自动切换版本。

**Comment by YerongAI** [comment]
根据我的猜测，商店版 Office 因为不是基于 C2R 因此不会使用 C2R 的策略设置。

这个策略设置是写入 Local Machine 后再由 Office 自行读取并应用，如果 Office 不认的话也当然不会生效。

**Comment by fuchanghao** [comment]
> 根据我的猜测，商店版 Office 因为不是基于 C2R 因此不会使用 C2R 的策略设置。
> 
> 这个策略设置是写入 Local Machine 后再由 Office 自行读取并应用，如果 Office 不认的话也当然不会生效。
> 
> Edit：我使用的是桌面版 32 位 Office.

你这到说出问题所在了，商店版office只认HKEY_CURRENT_USER中的配置，不认HKEY_LOCAL_MACHINE中的配置的。

**Comment by YerongAI** [comment]
> 你这到说出问题所在了，商店版office只认HKEY_CURRENT_USER中的配置，不认HKEY_LOCAL_MACHINE中的配置的。

新版本已通过别的方式支持直接写入 Current User，预计将会在月底或者下个月月初发布测试版本，正式版将于下个月微软补丁日的后一天发布，还请您耐心等待，感谢您的支持与理解。

**Comment by YerongAI** [comment]
> > 你这到说出问题所在了，商店版office只认HKEY_CURRENT_USER中的配置，不认HKEY_LOCAL_MACHINE中的配置的。
> 
> 新版本已通过别的方式支持直接写入 Current User，预计将会在月底或者下个月月初发布测试版本，正式版将于下个月微软补丁日的后一天发布，还请您耐心等待，感谢您的支持与理解。

测试版鸽了（直接等正式版吧

**Comment by YerongAI** [comment]
正式版已发布，按照正常步骤设置应用程序首选项时，使用 Office Tool Plus 作为安装模块（而不是 Office 部署工具）即可直接将设置应用到 Current User （而不只是 Local Machine）
