### ISSUE TITLE
[BUG] 文档转换失败

### ISSUE THREAD

**Issue by zuotiya** [YerongAI/Office-Tool#410]
**Office Tool Plus Version, e.g. 8.1.0.0:**
> 8.2.9.2

**Operating System, e.g. Windows 10 20H2 or Windows 7 SP1:**
> Win11

**Error description (required):**
> 文档无法转换

*Reproduction steps (suggested):*
> 转换任意文件

*Screenshot (suggested):*
![image](https://user-images.githubusercontent.com/59996739/148065630-e8a4eba8-3516-4c3b-a978-42972b5ca19b.png)

**Comment by zuotiya** [comment]
![image](https://user-images.githubusercontent.com/59996739/148065713-28f78fa7-3b45-4105-9c15-0387c096bd41.png)

**Comment by YerongAI** [comment]
请问你使用的 Office 版本是多少？体系结构是什么？（32 或 64 位）

**Comment by zuotiya** [comment]
2021 企业长期版 32位
![image](https://user-images.githubusercontent.com/59996739/148148290-f3465fe4-3eb8-4627-8771-4531269198ff.png)

**Comment by YerongAI** [comment]
> 2021 企业长期版 32位
> ![image](https://user-images.githubusercontent.com/59996739/148148290-f3465fe4-3eb8-4627-8771-4531269198ff.png)

说我这个我前段时间还刚测试过呢，不我这边是没有问题的。先确定下是不是 Office 本身的问题，可以尝试转换一下其他的文档（不是 word 的），又或者是重装一下 Office，也许某些组件没有成功注册上。

**Comment by zuotiya** [comment]
重新装了一遍同样版本的office，现在可以使用转换功能，谢谢啦
