### ISSUE TITLE
[IDEA] 希望可以在系统命令行内，以参数的形式执行程序内顶部命令框的命令。

### ISSUE THREAD

**Issue by UrielGGs** [YerongAI/Office-Tool#413]
**Feature description:**

​	希望可以在系统命令行内，以参数的形式执行程序内顶部命令框的命令。

**How it work?**

​	程序内的顶部命令框非常方便 	![顶部命令框](https://www.coolhub.top/wp-content/uploads/2021/07/command-box.png)

​	如果可以通过本地的命令提示符以参数形式执行顶部命令框命令，那很多步骤将会变得十分便捷。

![命令提示符](https://github.com/UrielGGs/IMG/raw/main/img/cli.png)

Technical Reference (if possible):

​	在翻看文档[创建 Office ISO](https://help.coolhub.top/zh-cn/deploy/create-iso.html#没有开启自动播放的-windows-如何使用一键安装功能)时发现了类似功能，眼前一亮。

**Comment by UrielGGs** [comment]
用于管理 Office 批量激活的工具：https://docs.microsoft.com/zh-cn/deployoffice/vlactivation/tools-to-manage-volume-activation-of-office

**Comment by YerongAI** [comment]
由于技术问题，此功能实现难度较大，并且不如直接调用 OSPP，这样还方便。

**Comment by YerongAI** [comment]
此功能已在最新的 9.0 测试版中提供，欢迎测试并提供反馈。

_注：我们注意到 deploy 命令目前存在问题无法正常使用，将会在正式版进行修复，目前 ospp 命令一切正常。_

**Comment by YerongAI** [comment]
您好，文档已更新，您可以前往[帮助文档](https://help.coolhub.top/zh-cn/others/#office-tool-plus-%E5%BA%94%E7%94%A8%E5%86%85%E5%91%BD%E4%BB%A4)查看最新的使用方法，如您有任何问题，欢迎与我们继续讨论。
