### ISSUE TITLE
[ASK] 默认状态的Windows Defender会对OTP报告病毒风险

### ISSUE THREAD

**Issue by jigugun** [YerongAI/Office-Tool#414]
刚刚下载解压后，Windows defender就报告病毒风险，并且强制将风险文件删了。以前没有出现这样的情况。今天第一次发现的。
<img width="602" alt="image" src="https://user-images.githubusercontent.com/95335610/149072843-65db82f0-cb31-42e8-a267-96d3a8bd6d0a.png">

**Comment by peafowl-wang** [comment]
我今天也是这个样子

**Comment by YerongAI** [comment]
目前 Windows Defender 已经解除警报，请将 WD 的病毒库更新至最新版本，再次尝试更新或下载，应该就没有问题了。

**Comment by peafowl-wang** [comment]
8.2.92没有问题

**Comment by YerongAI** [comment]
Windows Defender 病毒库已更新至 1.335.1791.0，经测试问题已解决，请更新病毒库后使用，感谢您的报告。

**Comment by YerongAI** [comment]
算了还是搞不过sb WD，最新版又报毒了，与官方联系中，等待结果。

**Comment by byyxx128** [comment]
这WD该不会走上360的路子吧，不交保护费不给过……围观中……

**Comment by byyxx128** [comment]
这WD（其实现在是MD了）该不会走上360的路子吧，不交保护费不给过……围观中……
