### ISSUE TITLE
[BUG] the version in title does not match version in github release

### ISSUE THREAD

**Issue by chemPolonium** [YerongAI/Office-Tool#419]
The version in title is v8.3.0.2
The version in github release page is v8.3.0.1

软件标题中的版本号是 8.3.0.2
GitHub中发布的版本号是8.3.0.1

这导致了scoop安装以及自动检查新版本的失败

![officeToolPlusScreenShot](https://user-images.githubusercontent.com/17716004/149623943-ce3af395-05e5-49ba-8392-be8286d52613.png)

**Comment by YerongAI** [comment]
版本更新太频繁了，至少要再等3天才能发布新版本解决上个版本存在的所有问题，8.3.0.2 也并不完美。

**Comment by YerongAI** [comment]
新版本已发布，应该没有问题了。
