### ISSUE TITLE
[BUG] 选择韩语时，Issue提示消息不会跟着语言设置的变更而同步变更

### ISSUE THREAD

**Issue by jigugun** [YerongAI/Office-Tool#423]
**Office Tool Plus Version, e.g. 8.1.0.0:**
> 8.3.0.2

**Operating System, e.g. Windows 10 20H2 or Windows 7 SP1:**
> Write down here

**Error description (required):**
> 语言变更为韩语，但是Issue提示消息内容是英文，语言变更为中文，Issue提示消息会变成中文

*Reproduction steps (suggested):*
1.启动OTP
2.变更语言为韩语
3.首页的Issue提示消息不会变更为韩语

*Screenshot (suggested):*
<img width="960" alt="image" src="https://user-images.githubusercontent.com/95335610/149900476-37ff8236-3231-411f-9747-66a0e03ef00c.png">

*Additional information (optional):*

**Comment by YerongAI** [comment]
已修正。
