### ISSUE TITLE
[BUG] 

### ISSUE THREAD

**Issue by boromyr** [YerongAI/Office-Tool#440]
**Office Tool Plus Version, e.g. 8.1.0.0:**
 8.3.1.0

**Operating System, e.g. Windows 10 20H2 or Windows 7 SP1:**
 Windows 11 

**Error description (required):**
 The tooltip to the passage of the mouse to choose the update channel closes instantaneously, in the following gif I recorded the problem

*Screenshot (suggested):*
![tooltip bug](https://user-images.githubusercontent.com/52782032/151237851-aa8ef328-2a81-4182-9df4-e5926e9f420e.gif)

*Additional information (optional):*
I also tried it on a second pc where Office Tool had never been used and the result is identical.

**Comment by YerongAI** [comment]
Hello, thanks for your report.

I also noticed that ToolTip can not work properly.

I think there is a problem of .NET 6.0, in the previous version all works fine, I will report it to .NET team.

**Comment by YerongAI** [comment]
I found a problem like that: [ToolTips in popups (or any context where capture is active) #5931](https://github.com/dotnet/wpf/pull/5931), maybe the problem has fixed but the new version of .NET is not published yet, we need to wait for it.

**Comment by boromyr** [comment]
Great, let's wait for the next version!
Would it be possible to add backup and restore of user settings, templates and personal dictionaries to Office Tool as well?

**Comment by YerongAI** [comment]
Another [issue](https://github.com/dotnet/wpf/issues/5716) like you said.

For backup and restore user settings, I need some time to make a plan and do it.

**Comment by YerongAI** [comment]
> Great, let's wait for the next version! Would it be possible to add backup and restore of user settings, templates and personal dictionaries to Office Tool as well?

For your new feature request, please open a new issue. For this issue, you can wait until .NET team fix it or close it as you want.

**Comment by boromyr** [comment]
Okay, thank you very much. I'll close then, thank you.

**Comment by YerongAI** [comment]
Unfortunately, Microsoft still hasn't fixed this issue, and I'm still experiencing it in the latest .NET 6.0.2.
