### ISSUE TITLE
[ASK] 关于触控板滚动修复的咨询

### ISSUE THREAD

**Issue by byyxx128** [YerongAI/Office-Tool#441]
在 [8.3.0.1](https://github.com/YerongAI/Office-Tool/releases/tag/v8.3.0.1) 的更新日志里有这么一条：
>Fixed an issue that can not drag scroll bar by touching.

然后微软旗下的 [PowerToys](https://github.com/microsoft/PowerToys) 也遇到了这么个情况。

不过 PowerToys 的这个情况更严重，它是在包括我电脑的很多设备上，无法通过触控板进行滚动操作。然后这问题挂出来一年多快两年了，依然没人修……

当然我作为一个开发小白，也不好评价这个情况。只是感觉两个基于 .NET 的软件都遇到过这个问题，OTP 这边优先解决了，所以有没有什么经验可以分享，或者作者要是什么时候有空的话过去那边瞅瞅，看能不能帮帮他们。

**Comment by byyxx128** [comment]
补充下，PowerToys 其实至今还在用 .NET Core 3.1，说要升级 .NET 5 一直拖着没升，然后现在要升 .NET 6 还是没升……不过 OTP 的 8.3.0.1 版本恰好是升级到 .NET 6 后的第一个版本，所以我不确定这个问题是因为架构升级修复的，还是作者额外单独修复的。

### 总之，PowerToys 的这个问题详见这里：https://github.com/microsoft/PowerToys/issues/3400

**Comment by YerongAI** [comment]
> 补充下，PowerToys 其实至今还在用 .NET Core 3.1，说要升级 .NET 5 一直拖着没升，然后现在要升 .NET 6 还是没升……不过 OTP 的 8.3.0.1 版本恰好是升级到 .NET 6 后的第一个版本，所以我不确定这个问题是因为架构升级修复的，还是作者额外单独修复的。
> 
> ### 总之，PowerToys 的这个问题详见这里：https://github.com/microsoft/PowerToys/issues/3400

这个问题跟 .NET 架构没啥关系，几行小代码就可以修复。等我有空了再去看看。

**Comment by YerongAI** [comment]
看完了之后发现这个问题跟我想的不太一样，我修复的是滚动条那个 Thumb，就是可以用鼠标拖动的那个条块不能用触摸拖动的问题，PowerToys 看起来像是不能通过触摸板双指滚动的问题，这两个问题还是有点不一样的，我也没特别为这个问题处理过，因此这个问题可能是 PowerToys 的。

**Comment by YerongAI** [comment]
以及我刚尝试了一下，我可以通过触控板进行滚动的。

**Comment by YerongAI** [comment]
此问题不再活跃且与 Office Tool Plus 关系不大，因此进行关闭处理。
