### ISSUE TITLE
[BUG] each time i install a new build of Windows 11, the Office activation gets overwritten, meaning i have to repair it each time, is this the expected behaviour or a bug?

### ISSUE THREAD

**Issue by GitExploraa** [YerongAI/Office-Tool#442]
**Office Tool Plus Version, e.g. 8.1.0.0:**
> 8.3.1.0

**Operating System, e.g. Windows 10 20H2 or Windows 7 SP1:**
> Windows 11 (Dev Builds)

**Error description (required):**
> each time i install a new build of Windows 11, the Office activation gets overwritten, meaning i have to repair it each time, is this the expected behaviour or a bug?

*Reproduction steps (suggested):*

*Screenshot (suggested):*

*Additional information (optional):*

**Comment by YerongAI** [comment]
You should asking Microsoft for help, not us.

**Comment by GitExploraa** [comment]
Microsoft won't be helping with essentially a pirated version of Office x), i just asked here cause this could have been a problem from the Activation process itself (or maybe the OS, like you suggested), doesnt bother me that much to renable it each time ,it takes less than a minute, thought i should report it still, thank you nevertheless

**Comment by YerongAI** [comment]
This is a bug with Windows Insider, we don't and we can't fix it, we can only provide a way to fix the problem. You know, every time.

**Comment by GitExploraa** [comment]
yeah, i'll just stick to that, thanks again and thanks for all your work
