### ISSUE TITLE
[BUG] 

### ISSUE THREAD

**Issue by wisenut2009** [YerongAI/Office-Tool#461]
**Office Tool Plus Version, e.g. 8.1.0.0:**
> 

**Operating System, e.g. Windows 10 20H2 or Windows 7 SP1:**
Windows 7 SP1

**Error description (required):**
PowerPoint2019备注区不能用鼠标拖放文字进行编辑，在已选中的文字上按下鼠标左键时，文字的选中状态就丢失了，非常不方便。检查PowerPoint选项，“允许拖放式文字编辑”是勾选上的。

尝试了16.0.12527.22105和16.0.12527.21504即点即用的专业增强版大客户中文版，都有这样的问题。

另一台Win10电脑的16.0.10384.20023版本（Office365）没有问题，这个版本不是通过Office Tool安装的。

不清楚问题是出在哪里，Office2019与Win7兼容性，或者Office2019自身？

*Reproduction steps (suggested):*

*Screenshot (suggested):*

*Additional information (optional):*

**Comment by chiyi4488** [comment]
此为 Microsoft Office 问题，非 Office Tool Plus问题，请向 Microsoft 提报臭虫。
