### ISSUE TITLE
Importing contacts from gmail

### ISSUE THREAD

**Issue by khoshteep** [YerongAI/Office-Tool#464]
Hi, how are you? I have tried to contact you via email but haven't heard from you. I was wondering if you can please tell me how to import contacts to Outlook 365 from Gmail. I have backed up the contacts as a CSV file and vcard but none works and outlook doesn't give me any error messages. I've tried to look online but they do the same thing. But it doesn't work. Would you tell me how I should do that?
thank you

**Comment by YerongAI** [comment]
Your message was replied on other platform, have you solved the problem?

**Comment by YerongAI** [comment]
We will close this issue due to the long time we have not received a reply.

By the way, this questions can be searched on Google.

If you have any questions, you can reopen this issue or open a new issue.
