### ISSUE TITLE
[ASK] 安装office专业版2019或专业增强版2019问题

### ISSUE THREAD

**Issue by yangchenglin** [YerongAI/Office-Tool#467]
我在使用office tool plus安装office专业版2019或专业增强版2019时发现部署完后只有word，但是我是选择了excel、powerpoint等的，安装过程中也没有出现任何错误，装完重启后也没有出现excel、powerpoint

**Comment by YerongAI** [comment]
是否有尝试过完全清理后再安装呢？

> 您可以在正常卸载后，前往工具箱清理 Office。

**Comment by yangchenglin** [comment]
十分感谢，按您的提示操作后，问题已经解决了
