### ISSUE TITLE
[ASK] 安装office 365提示可能是盗版

### ISSUE THREAD

**Issue by mzy666888** [YerongAI/Office-Tool#480]
Please go to discussions for help.
安装好365后，打开word提示可能是盗版？这个应该怎么做呢？

**Comment by lenewing3** [comment]
> Please go to discussions for help. 安装好365后，打开word提示可能是盗版？这个应该怎么做呢？

你有做激活操作吗?如果没有激活请做激活操作,说明在:[https://www.coolhub.top/archives/14](激活说明)

**Comment by id7371** [comment]
请访问此地址查看帮助：[](https://www.coolhub.top/archives/122)

**Comment by YerongAI** [comment]
由于此问题不再活跃，因此我们将其标记为已解决。

如问题未解决或者有新的问题，欢迎 reopen 或提交新的 issue
