### ISSUE TITLE
[BUG] Not specifying the correct value for obj.name results in a degraded user experience for screen readers

### ISSUE THREAD

**Issue by cary-rowen** [YerongAI/Office-Tool#484]
**Office Tool Plus Version, e.g. 8.1.0.0:**
8.3.8.0

**Operating System, e.g. Windows 10 20H2 or Windows 7 SP1:**
Windows 10 21H2 (x64) build 19044.1645

**Error description (required):**
Not specifying the correct value for obj.name 

*Reproduction steps (suggested):*
1. Install and launch the [NVDA screen reader](https://github.com/nvaccess/nvda)
2. Start Office Tool Plus;
3. Press Tab to move focus between controls(obj);
4. You may hear tts report the following: “安装 Office按钮”、“部署按钮”、“激活按钮”、“工具箱按钮”
5. You may also hear the following: "按钮 创建调查、测验和投票并实时轻松地查看结果"

---
Pay attention to step (4) and step (5):

Because the reporting order for screen readers is obj.name > obj.role > obj.description.

The way step (4) is reported is expected, obj.role should be reported after obj.name.

But step (5) reports obj.role first, This is due to incorrect behavior caused by missing obj.name.

You need to specify the correct string for obj.name .

*Screenshot (suggested):*
n/a
*Additional information (optional):*
n/a

**Comment by cary-rowen** [comment]
Similar problems exist in the controls and drop-down menu items of the main interface, and we hope to optimize them uniformly.

**Comment by cary-rowen** [comment]
Hi 

It should be noted that obj.name often needs to be shortened and clear, such as "install", "cancel" For more detailed information, you need to use obj.description.

Thanks

**Comment by YerongAI** [comment]
The problem of launcher items was fixed, now it will be reported like "Form 按钮 创建调查、测验和投票并实时轻松地查看结果".

If you have any questions or ideas, please let us know.

**Comment by YerongAI** [comment]
All the behavior of buttons and textbox was fixed. Also menus and combo box.

**Comment by cary-rowen** [comment]
Hi @YerongAI 

Thanks for your efforts.
could you provide a build version for me to test?

Thanks again

**Comment by YerongAI** [comment]
> Hi @YerongAI
> 
> Thanks for your efforts. could you provide a build version for me to test?
> 
> Thanks again

Please wait three days. We will release a production version for use.

**Comment by cary-rowen** [comment]
Thanks @YerongAI

**Comment by YerongAI** [comment]
> Thanks @YerongAI

Hi, updates is ready, please click version number on _About_ panel to get the updates.

**Comment by cary-rowen** [comment]
Hi @YerongAI 

Thanks, I got the update and it looks good.
But this following buttons still has the problem:
Command、Contact us、Help、About、Settings、minimize, close,
You might be able to fix it in a future version, btw, minimize, close etc buttons are also missing obj.name.
