### ISSUE TITLE
[ASK] 你好，关于更新的问题

### ISSUE THREAD

**Issue by yhld456** [YerongAI/Office-Tool#488]
使用office tool plus 生成了一个iso文件，如果增量更新这个iso文件到最新版本？还是每次只能重新下载最新版再生成iso文件

**Comment by YerongAI** [comment]
您好。

Office ISO 文件只能重新创建，不能增量更新。

**Comment by YerongAI** [comment]
由于此问题不再活跃，此 issue 将关闭。

如后续有任何需要，您可以重新开启此 issue 或 open new issue.
