### ISSUE TITLE
office 部署工具未正常退出

### ISSUE THREAD

**Issue by jymr92** [YerongAI/Office-Tool#494]
<img width="350" alt="image" src="https://user-images.githubusercontent.com/44893500/165015857-e2fb8b20-19a0-4365-8a02-935ce806c8cd.png">

以前已经安装过word，Visio。今天安装excel，进度一直是0%，我就重启电脑重新安装，结果就这样了。
我已经把所有office都卸载，还是这样。
如何解决？

**Comment by YerongAI** [comment]
请提供有效的错误报告。

错误报告由 Microsoft Office Installer 提供。

**Comment by YerongAI** [comment]
由于此问题不再活跃，此 issue 将关闭。

如后续有任何需要，您可以重新开启此 issue 或 open new issue.
