### ISSUE TITLE
Office tool参数咨询

### ISSUE THREAD

**Issue by wqcblog** [YerongAI/Office-Tool#503]
开发者你好，我通过iso离线下载部署，通过bat调用"Office Tool Plus.exe" /isoInstall进行安装，我想通过紧接着调用静默激活命令达到全自动激活(工具已准备好)，但我的cmd知识有限，我通过Start /wait "Office Tool Plus.exe" /isoInstall进行等待安装结束的过程，但是弹出官方的安装程序，所以我没有办法解决，请问官方有什么解决办法吗，谢谢

<sub>Sent from <a href="https://apps.apple.com/cn/app/id1314212521">PPHub</a></sub>

**Comment by YerongAI** [comment]
您好。

程序在调用安装程序后会立即退出，因此您的等待过程是无效的。

我们将会在以后尝试解决此问题，还请您能够理解和耐心等待。

**Comment by wqcblog** [comment]
谢谢，我想请问这个iso文件创建后，如果部署该iso的话与office tool plus相关性大吗，我想能否直接调用原生的安装程序，这样或许可以等待执行

**Comment by YerongAI** [comment]
> 谢谢，我想请问这个iso文件创建后，如果部署该iso的话与office tool plus相关性大吗，我想能否直接调用原生的安装程序，这样或许可以等待执行

您可以调用官方程序，但这需要您实时根据客户端环境修改参数。

**Comment by YerongAI** [comment]
> 谢谢，我想请问这个iso文件创建后，如果部署该iso的话与office tool plus相关性大吗，我想能否直接调用原生的安装程序，这样或许可以等待执行

您好，新的测试版 9.0.0.0 已经可以做到您的需求，只需编写一个 BAT，然后执行以下命令即可：

```bat
"Office Tool Plus.Console" /isoInstall
"Office Tool Plus.Console" ospp /insLicID ... (自行补充)
```

**Comment by YerongAI** [comment]
您好，文档已更新，您可以前往[帮助文档](https://help.coolhub.top/zh-cn/others/#office-tool-plus-%E5%BA%94%E7%94%A8%E5%86%85%E5%91%BD%E4%BB%A4)查看最新的使用方法，如您有任何问题，欢迎与我们继续讨论。
