### ISSUE TITLE
[ASK] 安装激活不久后提示需要激活是什么原因

### ISSUE THREAD

**Issue by wuyukun-tong** [YerongAI/Office-Tool#504]
您好，我使用你们的产品安装激活后，用一段时间打开word的时候提示我激活，这是什么原因呢！还是说本来就是周期性激活
LSTC专业增强版2021

**Comment by YerongAI** [comment]
只能你自己去调查。
要么是操作不对，要么就是你系统上有别的软件在干扰。

**Comment by zimo-han** [comment]
移除office的时候选了清除激活状态，结果系统预装的office激活状态也没了，请问有什么办法可以修复吗
