### ISSUE TITLE
激活失败是啥原因[ASK] 

### ISSUE THREAD

**Issue by limit123123** [YerongAI/Office-Tool#505]
![5UV%JM ~T1{9Q3FU I)C)A4](https://user-images.githubusercontent.com/50534180/169685999-d8e0c451-9240-4820-868a-52f0dcdf34ee.png)

**Comment by YerongAI** [comment]
[https://www.coolhub.top/archives/13](https://www.coolhub.top/archives/13)

**Comment by limit123123** [comment]
激活成功了，谢谢
