### ISSUE TITLE
[BUG] ODT failing to install with older version of office

### ISSUE THREAD

**Issue by nutterthanos** [YerongAI/Office-Tool#509]
**Office Tool Plus Version, e.g. 8.1.0.0:**
> 8.3.10.7

**Operating System, e.g. Windows 10 20H2 or Windows 7 SP1:**
> Windows 10 21H1

**Error description (required):**
> Trying to install an older version of office 2016 with newer version of ODT fails

*Reproduction steps (suggested):*
Open Office-Tool
Click Deploy
Choose Install Options including the older version in Installation Settings in Version box
click deploy
ODT opens
and then fails with error 2030-30029 or error 4-30034 idk

*Screenshot (suggested):*

i can't screenshot at this stage but if you really need it i'll add it later

*Additional information (optional):*
this only happens when installing a fresh copy of an older version since once you installed an copy of it
installing over it will instead just use the already older installed copy of C:\Program Files\Common Files\microsoft shared\ClickToRun\OfficeClickToRun.exe which does work with older versions on installation just not the ODT program.

**Comment by YerongAI** [comment]
Can you tell me what is the version number of the "older version" you are using?

**Comment by nutterthanos** [comment]
> Can you tell me what is the version number of the "older version" you are using?

like 16.0.4229.1024

**Comment by YerongAI** [comment]
> > Can you tell me what is the version number of the "older version" you are using?
> 
> like 16.0.4229.1024

The version of Office you are using is outdated, please download and install the new version instead.

**Comment by nutterthanos** [comment]
> > > Can you tell me what is the version number of the "older version" you are using?
> > 
> > 
> > like 16.0.4229.1024
> 
> The version of Office you are using is outdated, please download and install the new version instead.

i know so this isn't bug then and intended to be like this?

**Comment by YerongAI** [comment]
Yeah, it's not a bug, and just use the new version instead.

**Comment by nutterthanos** [comment]
Right not an issue then
