### ISSUE TITLE
请问我这个是什么情况，感谢！

### ISSUE THREAD

**Issue by 4EGang** [YerongAI/Office-Tool#510]
激活失败
![image](https://user-images.githubusercontent.com/103100329/170687970-62750a18-82de-428d-a929-b7c974e6df5d.png)

**Comment by 4EGang** [comment]
oh my god！我添加了kms端口后激活成功了！why？
![image](https://user-images.githubusercontent.com/103100329/170688487-aa9f7f0d-f003-4adf-b53b-8a7962748e96.png)

**Comment by YerongAI** [comment]
此类问题多半是由于使用了第三方 KMS 激活程序而导致 Software Protection 的配置出现问题，一般情况下可以添加端口，或者在工具箱内修复 Software Protection 服务以解决。

**Comment by YerongAI** [comment]
由于此问题不再活跃，因此我们将进行关闭处理，如果您有任何其他问题，您可以 reopen 或者提交新的 issue
