### ISSUE TITLE
[BUG] 亚克力效果与VMWare Tools不兼容

### ISSUE THREAD

**Issue by NewbieXvwu** [YerongAI/Office-Tool#511]
**Office Tool Plus Version, e.g. 8.1.0.0:**
> 9.0.0.1 Beta

**Operating System, e.g. Windows 10 20H2 or Windows 7 SP1:**
> Windows 10 Dev 21390.2025（最后一个Windows 10 Dev版）

**Error description (required):**
> 亚克力效果与VMWare Tools不兼容

*Reproduction steps (suggested):*
1.在VMWare WorkStation 16中安装Windows 10 21390.2025（[我从UUPDump上下载的镜像](https://www.123pan.com/s/qMjA-2aQxv)）
2.安装VMWare Tools
3.打开Office Tool Plus，设置打开亚克力效果
4.如下图所示
*Screenshot (suggested):*
![错误截图](https://user-images.githubusercontent.com/87637612/170811327-1569f533-9af1-41b2-ac13-17ccc3a2f294.png)

*Additional information (optional):*
可能是.NET的毛病？还是我的Windows版本问题？调成无效果或必应壁纸可以临时修复
另外可以确定不是我的显卡（1050Ti）毛病，宿主机正常

**Comment by YerongAI** [comment]
亚克力效果从一开始我就没改动过，所以我猜 8.3.10.7 版本可能也会有问题，麻烦您能否同时测试一下这个版本呢？（官网可下载这个版本）

**Comment by fuchanghao** [comment]
> **Office Tool Plus Version, e.g. 8.1.0.0:**
> 
> > 9.0.0.1 Beta
> 
> **Operating System, e.g. Windows 10 20H2 or Windows 7 SP1:**
> 
> > Windows 10 Dev 21390.2025（最后一个Windows 10 Dev版）
> 
> **Error description (required):**
> 
> > 亚克力效果与VMWare Tools不兼容
> 
> _Reproduction steps (suggested):_ 1.在VMWare WorkStation 16中安装Windows 10 21390.2025（[我从UUPDump上下载的镜像](https://www.123pan.com/s/qMjA-2aQxv)） 2.安装VMWare Tools 3.打开Office Tool Plus，设置打开亚克力效果 4.如下图所示 _Screenshot (suggested):_ ![错误截图](https://user-images.githubusercontent.com/87637612/170811327-1569f533-9af1-41b2-ac13-17ccc3a2f294.png)
> 
> _Additional information (optional):_ 可能是.NET的毛病？还是我的Windows版本问题？调成无效果或必应壁纸可以临时修复 另外可以确定不是我的显卡（1050Ti）毛病，宿主机正常

我自己在Windows 11 22H2 (22621.1)中测试没问题，无论是浅色模式还是深色模式。

vmware-tools为12.0.5最新版：https://packages.vmware.com/tools/releases/latest/windows

![屏幕截图 2022-05-30 112221](https://user-images.githubusercontent.com/11471475/170911376-f11a8dbd-18ac-4b90-a052-a1e0b4bf8913.png)

**Comment by YerongAI** [comment]
> > **Office Tool Plus Version, e.g. 8.1.0.0:**
> > > 9.0.0.1 Beta
> > 
> > 
> > **Operating System, e.g. Windows 10 20H2 or Windows 7 SP1:**
> > > Windows 10 Dev 21390.2025（最后一个Windows 10 Dev版）
> > 
> > 
> > **Error description (required):**
> > > 亚克力效果与VMWare Tools不兼容
> > 
> > 
> > _Reproduction steps (suggested):_ 1.在VMWare WorkStation 16中安装Windows 10 21390.2025（[我从UUPDump上下载的镜像](https://www.123pan.com/s/qMjA-2aQxv)） 2.安装VMWare Tools 3.打开Office Tool Plus，设置打开亚克力效果 4.如下图所示 _Screenshot (suggested):_ ![错误截图](https://user-images.githubusercontent.com/87637612/170811327-1569f533-9af1-41b2-ac13-17ccc3a2f294.png)
> > _Additional information (optional):_ 可能是.NET的毛病？还是我的Windows版本问题？调成无效果或必应壁纸可以临时修复 另外可以确定不是我的显卡（1050Ti）毛病，宿主机正常
> 
> 我自己在Windows 11 22H2 (22621.1)中测试没问题，无论是浅色模式还是深色模式。
> 
> vmware-tools为12.0.5最新版：https://packages.vmware.com/tools/releases/latest/windows
> 
> ![屏幕截图 2022-05-30 112221](https://user-images.githubusercontent.com/11471475/170911376-f11a8dbd-18ac-4b90-a052-a1e0b4bf8913.png)

从实际情况上来说，我个人觉得更多的是驱动程序或者 DWM 的问题，亚克力效果由 DWM 处理，因此即使它真的出了问题，也只能由显卡驱动程序提供商或微软进行修复。

**Comment by YerongAI** [comment]
请问您是否还有其他问题？如无问题，我们将会在两天后将此 issue 标记为已完成。

**Comment by NewbieXvwu** [comment]
我目前认为这是VMWare显卡驱动的问题，似乎Edge在虚拟机中也出现了一些问题。但是我好奇的是绝大多数软件的亚克力效果还是正常的。另外我将该虚拟机系统原模原样安装到了同一台实体机上，没有出现问题。或许我应该向VMWare提交这个问题？

**Comment by NewbieXvwu** [comment]
卸载VMWare Tools后亚克力效果似乎正常显示。

**Comment by YerongAI** [comment]
> 卸载VMWare Tools后亚克力效果似乎正常显示。

个人认为这个和 VMWare Tools 有关，您可以就此问题向 VM 报告。

**Comment by NewbieXvwu** [comment]
或许您可以在检测到VMWare Tools且用户试图开启亚克力效果时弹窗提示？

**Comment by YerongAI** [comment]
> 或许您可以在检测到VMWare Tools且用户试图开启亚克力效果时弹窗提示？

这是偶发问题，在我这边测试并无问题，因此没有必要添加此类提示。

**Comment by YerongAI** [comment]
此问题已得出结论，将做结题处理。如后续有任何意见或问题，欢迎继续讨论。
