### ISSUE TITLE
[BUG] Black block below OTP window when maximized

### ISSUE THREAD

**Issue by yaeyaya** [YerongAI/Office-Tool#515]
**Office Tool Plus Version, e.g. 8.1.0.0:**
> 

**Operating System, e.g. Windows 10 20H2 or Windows 7 SP1:**
> Windows 11 21H2 22000.708

**Error description (required):**
> There is a black block below the OTP window, above the Windows taskbar, when OTP window is maximized.

*Reproduction steps (suggested):*
1. Run OTP
2. Maximize OTP window

*Screenshot (suggested):*
<img width="960" alt="image" src="https://user-images.githubusercontent.com/9144748/171873211-1a184e32-2d0f-45f4-9972-cb0b55d947db.png">

*Additional information (optional):*

**Comment by YerongAI** [comment]
The issue should be fixed by MS, not us.

When it appears again, you can click on taskbar, then it should be normal.

**Comment by yaeyaya** [comment]
> The issue should be fixed by MS, not us.
> 
> When it appears again, you can click on taskbar, then it should be normal.

Yes. It disappears. 👍
