### ISSUE TITLE
[ASK] Office shows Error 30088-27 when trying to manually update

### ISSUE THREAD

**Issue by GitExploraa** [YerongAI/Office-Tool#516]
i have installled Office as mentionned in the guide and everything is working fine, but when i try to manually update it from the account pages, first it says product is up to date, then after a few moments i get this error
![image](https://user-images.githubusercontent.com/44654056/171907691-48b1d5ba-7dc4-4ffd-9d2f-c4e509c7409d.png)

**Comment by iDolmatov** [comment]
Office bug, not Office-Tool. It was more useful to specify the installation channel and the update channel, a product version.
In addition, the update logs are located in the temp folder. These logs should preferably be sent to Microsoft.

**Comment by YerongAI** [comment]
You can uninstall Office and install a new version, this may helpful to fix it.

**Comment by GitExploraa** [comment]
> https://techcommunity.microsoft.com/t5/office-insider/receiving-quot-something-went-wrong-quot-error-30088-27-and-quot/m-p/3460377

i guess this is more or less a widespread issue for now, i'll wait sometime and see how it goes, ill be sure to update this thread when it gets fixed/ i find a solution, Thank you

**Comment by GitExploraa** [comment]
> You can uninstall Office and install a new version, this may helpful to fix it.

as the previous comment suggested this may be an issue from Office itself, ill wait sometime and see how it goes, Thank you both

**Comment by YerongAI** [comment]
> > You can uninstall Office and install a new version, this may helpful to fix it.
> 
> as the previous comment suggested this may be an issue from Office itself, ill wait sometime and see how it goes, Thank you both

You can collect log to analyze the problem. Open Office Tool Plus, go to toolbox page and you can collect the installer logs.

**Comment by GitExploraa** [comment]
> > > You can uninstall Office and install a new version, this may helpful to fix it.
> > 
> > 
> > as the previous comment suggested this may be an issue from Office itself, ill wait sometime and see how it goes, Thank you both
> 
> You can collect log to analyze the problem. Open Office Tool Plus, go to toolbox page and you can collect the installer logs.

noted, ill give it a look

**Comment by GitExploraa** [comment]
seems like this was a bug only with the previous update, the latest update got installed and is working fine, Thank you
