### ISSUE TITLE
V9 - Many antiviruses report the app as malware

### ISSUE THREAD

**Issue by boromyr** [YerongAI/Office-Tool#517]
With the new version 9 of OT many antiviruses report the app as malware Gen: Variant.Fugrafa.222451, here is the reference link VirusTotal:
https://www.virustotal.com/gui/file/5be368b09a07e39a6407626748f001a0029bfb0a4c3dc329975e8820fc19f290/detection/f-5be368b09a07e39a6407626748f001a0029bfb0a435c3d1a0029b329975e8820d
Versions 8.x gave 100% clean results.

**Comment by YerongAI** [comment]
And now it's 4 left.

**Comment by YerongAI** [comment]
The link you provided was 100% clean now. Thank you for your report.

Also, we will keep going on it after next version is released.
