### ISSUE TITLE
你太厉害了，怎么想到开发这个工具的[ASK] 

### ISSUE THREAD

**Issue by limit123123** [YerongAI/Office-Tool#520]
Please go to discussions for help.
牛逼大佬

**Comment by fxzxmicah** [comment]
谢谢夸奖，因为微软很垃圾，所以开发者自己动手造福大众。

**Comment by YerongAI** [comment]
谢谢夸奖，用脑子想的 😊

**Comment by YerongAI** [comment]
你太厉害了，怎么想到问这个问题的 😋

**Comment by plotqq** [comment]
眼前一亮啊！大神~~~

**Comment by chiyi4488** [comment]
前来膜拜

**Comment by limit123123** [comment]
牛



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2022年6月16日(周四) 上午10:38
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [YerongAI/Office-Tool] 你太厉害了，怎么想到开发这个工具的[ASK]  (Issue #520)




 
谢谢夸奖，用脑子想的 😊
