### ISSUE TITLE
[ASK] 是否应该适当修改一下措辞

### ISSUE THREAD

**Issue by fuchanghao** [YerongAI/Office-Tool#546]
关于这个"不再支持"的提示：

![屏幕截图 2022-07-19 141736](https://user-images.githubusercontent.com/11471475/179682151-304ff3dd-1cbc-4c4a-a081-03100e305d8f.png)

第一：

目前来说，微软的说法是2023年1月停止支持Windows 7和Windows 8.1等系统：

https://techcommunity.microsoft.com/t5/office-end-of-support-blog/act-now-and-keep-microsoft-365-apps-supported-after-january-10/ba-p/3568981

具体来说也是“将不再”，或者更准确的说“将停止”。

第二点就是不太希望用“支持(support)”，这个词，这个词已经被微软滥用了，导致表意不明：
在微软中有两种含义：
(1) 不再兼容，例如.NET 7停止支持Windows 7和Windows 8.1：
https://github.com/dotnet/core/issues/7556
或者Office 2019/2021不再支持Windows 7/Windows 8.1都是这个含义

(2)依旧兼容，只是出Bug微软不管：
例如Windows Server 2022发布时微软就声明：Microsoft 365 Apps isn’t supported on Windows Server 2022.
https://docs.microsoft.com/en-us/deployoffice/endofsupport/windows-server-support#windows-server-2022

但实际上依旧可以使用OTP部署和运行：

![屏幕截图 2022-07-19 142454](https://user-images.githubusercontent.com/11471475/179685278-2f5b096b-c469-4c7b-930e-3d4fc9330fbf.png)
![屏幕截图 2022-07-19 143237](https://user-images.githubusercontent.com/11471475/179685303-1d9cbc2d-e5dc-41ed-82ca-b406b7aee222.png)

只是这种情况下出了Bug反馈到微软是不管的，微软不会理会这个系统上的兼容性问题。

所以这里与其用“支持”这种比较有歧义的话，还不如用“兼容”这个词更好。

**Comment by YerongAI** [comment]
欢迎您查看最新提交的 #547 并告诉我们您的意见和想法！
