### ISSUE TITLE
[IDEA] 通道描述改进和更细粒度的更新策略

### ISSUE THREAD

**Issue by fuchanghao** [YerongAI/Office-Tool#548]
**Feature description:**
(1)多通道能否描述的更准确和完整一点。
(2)能否提供更多的更新策略。

**How it work?**
(1)我这里无论是否勾选显示内部通道，都只显示一个半年企业通道(其它Semi-Annual Enterprise Channel的也是同样的版本号)，但是月度企业通道通常是2-3条同时存在的(一条通道会更新小版本修复Bug14个月)。(当然左边要是自动注明2205、2204字样就更好了，不过不强求了。)

例如这是目前的半年企业通道，可以官网查到然后手动指定版本部署：

https://docs.microsoft.com/en-us/officeupdates/microsoft365-apps-security-updates

Semi-Annual Enterprise Channel: Version 2202 (Build 14931.20604)
Semi-Annual Enterprise Channel: Version 2108 (Build 14326.21062)
Semi-Annual Enterprise Channel: Version 2102 (Build 13801.21528)

但是查看通道这里只看到了2202这一条。

还有就是切换通道的设计不知能否满足如下的升级需求，例如：

我想升级方案是：
月度企业通道
Monthly Enterprise Channel: Version 2202 (Build 14931.20392)
Monthly Enterprise Channel: Version 2203 (Build 15028.20282)
Monthly Enterprise Channel: Version 2204 (Build 15128.20312)

这样每个月都是接受晚当前通道两个大版本的小版本(默认为晚当前通道一个月大版本的小版本)，对于新功能不太敏感的用户可以这样追求稳定性。

或者选择半年企业通道的用户，希望每次都是该通道结束生命周期之后再换到下一个通道。例如2102版不再更新了就切换到2108版，2108版不再更新了就切换到2202版，这种更新策略不知道OTP能不能实现。

**Comment by YerongAI** [comment]
您好，查阅官方文档后并未发现官方有对此配置的叙述，尽管我也认为该功能是可以实现的。但由于缺乏官方的操作步骤，因此无法将其集成到 Office Tool Plus 中。

**Comment by YerongAI** [comment]
请问您是否还有其他疑问或者问题？如若无问题，我们将在两天后关闭此 issue
