### ISSUE TITLE
[BUG] OTP无法正常卸载Office 365

### ISSUE THREAD

**Issue by Vercharon** [YerongAI/Office-Tool#549]
**Office Tool Plus Version, e.g. 8.1.0.0:**
> 9.0.2.10

**Operating System, e.g. Windows 10 20H2 or Windows 7 SP1:**
> Windows 11 Professional beta 22621.232

**Error description (required):**
> OTP部署卸载office 365时未能正常卸载，反而进入下载进程。但是在控制面板的程序和功能中能够正常卸载office。

*Reproduction steps (suggested):*
卸载产品-->点击【开始部署】以确认卸载-->进入下载office进程

*Screenshot (suggested):*
![屏幕截图 2022-07-27 220356](https://user-images.githubusercontent.com/107681877/181268434-a9d111b2-0446-4d66-ace1-811dfdf38740.png)
![屏幕截图 2022-07-27 220426](https://user-images.githubusercontent.com/107681877/181268566-14a64882-2ee7-48cb-b493-6536470e8335.png)

*Additional information (optional):*

**Comment by YerongAI** [comment]
请您点击「卸载」按钮后，点击 「查看 XML 代码」，将其截图留存，如果后续点击「开始部署」仍为安装，请将此 XML 代码截图提供给我们，以便我们确定是什么模块的问题。

同时请您从「工具箱」页面收集 Office 安装程序日志提供给我们以进行分析。

**Comment by YerongAI** [comment]
不用了，我试出来问题了，是微软的 Office 部署工具有问题，准备下发更新替换这个版本。

**Comment by YerongAI** [comment]
更新已下发，我这边的问题已经解决，如果后续还有问题，可以重新打开此 issue
