### ISSUE TITLE
OTP with .Net Framwork 5.0+ not supported in Windows 7

### ISSUE THREAD

**Issue by Lovely-XPP** [YerongAI/Office-Tool#550]
开发者您好,因为工作原因只能使用windows7,之前用windows10/11使用OTP,体验极佳,因此在win7下也想尝试使用OTP,我注意到网站上描述的系统要求(Windows 7 SP1 +),我兴奋地下载了最新版进行尝试,但是发现无法打开(就单纯地**双击后没有任何反应**).

<img width="485" alt="网站截图" src="https://user-images.githubusercontent.com/66028151/183297825-1653b492-12fa-4364-9463-70b68b3d433e.PNG">

经过我的不断尝试,我发现**可以打开的版本对应的.Net Framwork最高不超过4(<5)**,因此想问问您可不可以**针对windows7发布一个最新可以使用的版本**,对于像我们这类极其特殊只能使用windows7的工作者,万分感谢!

当然,我的情况也有可能是个例,希望开发者可以给我一些解决方案,感谢您的辛苦付出!

**Comment by YerongAI** [comment]
请尝试下载并安装 [UpdatePack](https://download.coolhub.top/Extensions/Win7_UpdatePack/)，然后重新尝试打开 Office Tool Plus.

**Comment by Lovely-XPP** [comment]
可以了，感谢开发者😁
