### ISSUE TITLE
[BUG] Office Tool Plus v9.0.3.6无法自动更新且手动更新后会弹出反向更新到9.0.2,10更新的问题

### ISSUE THREAD

**Issue by fuchanghao** [YerongAI/Office-Tool#551]
**Office Tool Plus Version, e.g. 8.1.0.0:**
> v9.0.3.6

**Operating System, e.g. Windows 10 20H2 or Windows 7 SP1:**
> Windows 10 22H2 19045.1889

**Error description (required):**
> 使用Office Tool Plus v9.0.2.10无法检测到更新，手动更新到 v9.0.3.6后会弹框要我反向更新到Office Tool Plus v9.0.2.10。

*Reproduction steps (suggested):*

1.下载v9.0.3.6压缩包并解压
https://github.com/YerongAI/Office-Tool/releases/download/v9.0.3.6/Office_Tool_with_runtime_v9.0.3.6.7z
2.运行Office Tool Plus.exe
3.可以看到如下提示框，点击后会会弹出反向更新到9.0.2,10。

*Screenshot (suggested):*

![屏幕截图 2022-08-10 164954](https://user-images.githubusercontent.com/11471475/183858717-dfd3dbad-2fba-4c43-ac4c-8820ccf95843.png)
![屏幕截图 2022-08-10 165015](https://user-images.githubusercontent.com/11471475/183858728-49870203-034e-491c-a056-11296fa806c1.png)

*Additional information (optional):*

**Comment by YerongAI** [comment]
您好，因为 9.0.3.6 有致命的问题，我们已经撤回此版本，并加紧开发 9.0.3.7，对此造成的不便还请您谅解 :(

**Comment by YerongAI** [comment]
您好，v9.0.3.7 版本，请您下载并使用此版本，对此造成的不便我们深表歉意！
