### ISSUE TITLE
[IDEA] 希望能支持arm64位Office的下载

### ISSUE THREAD

**Issue by FakeNewsNextOne** [YerongAI/Office-Tool#554]
**Feature description:**
> Write down here

**How it work?**
> Write down here

Technical Reference (if possible):
> Write down here

**Comment by YerongAI** [comment]
https://insider.office.com/zh-cn/blog/64-bit-office-for-windows-on-arm

这里说明了怎么装。

以及我没有 arm 设备，故不会做任何开发与测试。
