### ISSUE TITLE
[BUG] 文档转换功能无法将任意Powerpoint文件转为视频格式

### ISSUE THREAD

**Issue by Charon2050** [YerongAI/Office-Tool#555]
Office Tool Plus 版本: 9.0.3.7

操作系统: Windows 10 64 bit

Office: Office LTSC 专业增强版 2021 16.0.14332.20358

在文档转换功能中，无法将Powerpoint格式的文件(.pptx、.ppt、.ppsm等)转换为视频格式(.mp4、.wmv)，提示为“保存成功”，但相应目录找不到转换后的文件。其它的格式转换工作正常。

在另一台电脑上复现了此Bug。

**Comment by YerongAI** [comment]
Fixed，已修复，明天发新版本

**Comment by YerongAI** [comment]
更新尚未发布，因此重新打开此 issue

**Comment by WsinGithub** [comment]
Microsoft 365 企业应用版 同样会报错
![image](https://user-images.githubusercontent.com/55137994/204097511-0cc996e5-d923-4629-8325-91eb083f1f02.png)

**Comment by WsinGithub** [comment]
另外，更新后需要卸载365并重新部署吗？🐣

**Comment by YerongAI** [comment]
> Microsoft 365 企业应用版 同样会报错
> ![image](https://user-images.githubusercontent.com/55137994/204097511-0cc996e5-d923-4629-8325-91eb083f1f02.png)
> 

这个问题请咨询 Office 技术支持。
