### ISSUE TITLE
[BUG] 最新版'9.0.3.7'可访问性降低

### ISSUE THREAD

**Issue by cary-rowen** [YerongAI/Office-Tool#556]
**Office Tool Plus Version, e.g. 8.1.0.0:**
9.0.3.7

**Operating System, e.g. Windows 10 20H2 or Windows 7 SP1:**
Windows 10 21H2 (x64) build 19044.1889

**Error description (required):**
1. 在单选按钮之间导航的时候屏幕阅读器朗读“转到页面”，例如“Deploy单选按钮未选中转到页面”，“Home单选按钮已选中转到页面”，“转到页面的提示过于冗余”如果这是人为设置的可以考虑取消；
2. 控件的 name 和 description 无需重复，请优先设置 name 属性，例如“home”这个控件的  name 和 description 的值都设置为 "home"往往是没有必要的；
description:的正确使用是那些快捷图标，比如：'outlook'按钮，屏幕阅读器 focus 到该按钮会朗读为“Outlook按钮Business-class email through a rich and familiar Outlook experience.”这样的提示非常好的告诉了屏幕阅读器该按钮的用途。
3. 在“Deploy”页面，选择产品版本的 comboBox 中的项目无法被屏幕阅读器正常读出：使用上下箭头查看屏幕阅读器会朗读为“Yerong.OfficeToolPlus.Office.Models.Product.OfficeProduct”
4. 控件之间存在空的焦点，例如使用 Tab 键从 Architecture移动到Channel ComboBox 时，会多出一个焦点屏幕阅读器没有朗读任何内容，同样的情况也出现在设置页面。
5. 在“Deploy”页面，'menu'按钮的name 没有设置值，而只有 description ，建议更正。
6. 在“Deploy”页面，用于折叠/展开某个 group 的 toggleButton 缺失了 name 属性。
*Reproduction steps (suggested):*
在电脑上安装并运行NVDA屏幕阅读器，尝试使用键盘操作 Office Tool Plus: https://github.com/nvaccess/nvda

*Screenshot (suggested):*

*Additional information (optional):*

**Comment by YerongAI** [comment]
最近测试版已发布，如有兴趣欢迎帮助我们测试并反馈问题！

**Comment by cary-rowen** [comment]
您好，是否可以提供一下测试版供测试。

**Comment by YerongAI** [comment]
> 您好，是否可以提供一下测试版供测试。

Release 里我发了测试版了啊

**Comment by cary-rowen** [comment]
这个版本的可访问性大幅度提升了，多数的 description 信息恰到好处，可以改善用户的使用体验。

## 以下有几个需要完善的点
1. 避免 Description和 Tooltip 的内容重复：如“点击以展开或收起导航栏”，这样屏幕阅读器会有朗读重复信息的效果。
2. 一般无需在名称上提供方位，如“**底部**导航栏”，但是这里底部导航栏中有两项“关于”和“设置”，能否统一放到另一个导航栏中，或者给这两项的顶层容器一个其他的名称以做区分。
3. “安装 iSlide 插件”的 description '海量 PPT 素材下载，PPT 智能排版，让 PPT 设计更简单。'跟另外的 label 存在重复，并且此处有两个焦点作用不明，一个名称是“立即安装 iSlide”另一个是“安装 iSlide 插件”。
4. “导航栏展开/收起”的按钮点击后界面无变化。
5. “备份”和“恢复” office 设置两个按钮的 description 是一样的，建议去掉该描述，因为其所属 group 已经包含描述（备份或者恢复 Office 设置...）。
6. “添加产品”的对话框，筛选文本框中输入“365”似乎没有产生筛选效果，不知道是否是 bug。

**Comment by cary-rowen** [comment]
补充：
在部署页面，针对某产品或语言包进行卸载时，点击“卸载”按钮后 tab 焦点会被重置，希望点击“卸载”后， Tab 焦点能聚焦在“取消卸载”的按钮上。

**Comment by YerongAI** [comment]
> 补充：
> 在部署页面，针对某产品或语言包进行卸载时，点击“卸载”按钮后 tab 焦点会被重置，希望点击“卸载”后， Tab 焦点能聚焦在“取消卸载”的按钮上。

请问除此之外还有其他问题吗？

**Comment by cary-rowen** [comment]
另外一个问题： 安装过程中最小化到任务栏之后无法点击显示窗口查看状态。

## 测试步骤（基于屏幕阅读器的键盘操作）
1. 开启 NVDA屏幕阅读器 或系统的讲述人。
2. 执行 Office 安装，在下载安装过程中按 Alt+F4 进度窗口将会被最小化到通知区域工具栏。
3. 按 Win +B 将焦点移动到通知区域，使用上下左右方向键，找到“‪正在后台安装 Office。单击此处查看状态。‬”的图标并回车。

## 预期效果
安装进度窗口再次显示，允许查看安装详情。

## 实际效果
按回车键后没有反应，窗口没有显示。

**Comment by cary-rowen** [comment]
部署页面，点击“确定”按钮关闭添加产品对话框后 Tab 焦点会被重置到底部导航栏，建议将焦点设置到“取消部署”或者“添加产品”按钮上。

**Comment by YerongAI** [comment]
> 另外一个问题： 安装过程中最小化到任务栏之后无法点击显示窗口查看状态。
> 
> ## 测试步骤（基于屏幕阅读器的键盘操作）
> 1. 开启 NVDA屏幕阅读器 或系统的讲述人。
> 2. 执行 Office 安装，在下载安装过程中按 Alt+F4 进度窗口将会被最小化到通知区域工具栏。
> 3. 按 Win +B 将焦点移动到通知区域，使用上下左右方向键，找到“‪正在后台安装 Office。单击此处查看状态。‬”的图标并回车。
> 
> ## 预期效果
> 安装进度窗口再次显示，允许查看安装详情。
> 
> ## 实际效果
> 按回车键后没有反应，窗口没有显示。

这个程序是微软的，应该向微软报告。

**Comment by cary-rowen** [comment]
> > 另外一个问题： 安装过程中最小化到任务栏之后无法点击显示窗口查看状态。
> > ## 测试步骤（基于屏幕阅读器的键盘操作）
> > 
> > 1. 开启 NVDA屏幕阅读器 或系统的讲述人。
> > 2. 执行 Office 安装，在下载安装过程中按 Alt+F4 进度窗口将会被最小化到通知区域工具栏。
> > 3. 按 Win +B 将焦点移动到通知区域，使用上下左右方向键，找到“‪正在后台安装 Office。单击此处查看状态。‬”的图标并回车。
> > 
> > ## 预期效果
> > 安装进度窗口再次显示，允许查看安装详情。
> > ## 实际效果
> > 按回车键后没有反应，窗口没有显示。
> 
> 这个程序是微软的，应该向微软报告。

OK, Thanks!

**Comment by YerongAI** [comment]
> 这个版本的可访问性大幅度提升了，多数的 description 信息恰到好处，可以改善用户的使用体验。
> 
> ## 以下有几个需要完善的点
> 1. 避免 Description和 Tooltip 的内容重复：如“点击以展开或收起导航栏”，这样屏幕阅读器会有朗读重复信息的效果。
> 2. 一般无需在名称上提供方位，如“**底部**导航栏”，但是这里底部导航栏中有两项“关于”和“设置”，能否统一放到另一个导航栏中，或者给这两项的顶层容器一个其他的名称以做区分。
> 3. “安装 iSlide 插件”的 description '海量 PPT 素材下载，PPT 智能排版，让 PPT 设计更简单。'跟另外的 label 存在重复，并且此处有两个焦点作用不明，一个名称是“立即安装 iSlide”另一个是“安装 iSlide 插件”。
> 4. “导航栏展开/收起”的按钮点击后界面无变化。
> 5. “备份”和“恢复” office 设置两个按钮的 description 是一样的，建议去掉该描述，因为其所属 group 已经包含描述（备份或者恢复 Office 设置...）。
> 6. “添加产品”的对话框，筛选文本框中输入“365”似乎没有产生筛选效果，不知道是否是 bug。

1. 我没有设置 Description。
2. 恕我实在没有办法做到合并在一起，因为按理讲它们确实分开比较合理。我也想不到有什么别的名字可以起的。
3. 已更改。
4. 未复现，没有发现问题。
5. 已修正。
6. 未复现，没有发现问题。

**Comment by YerongAI** [comment]
已发布了新的 Alpha，您可以验证问题是否已解决或仍然存在，同时我们针对产品、语言、许可证列表进行了修复，修复了筛选之后无法使用 Tab 进行导航的问题。

**Comment by cary-rowen** [comment]
以下录屏展示了： （1）、（4）、（6）：

https://user-images.githubusercontent.com/21048245/205493998-51bc50e1-454a-47d4-a69e-8ce5ba6b9499.mp4


1. 重复朗读“点击以展开或收起导航栏”，通过 NVDA +F1 查看日志，发现该控件具有 description 属性；
2. 那就保持现状吧；
4. 点击“展开或收起导航栏”可能视觉上有变化，使用 tab 键查看并没有发现焦点的改变；
6. 在录屏中，在筛选输入框中键入“365”理想化的效果应该列表中只展示包含365的项目，不知道是否是这样。

**Comment by YerongAI** [comment]
> 以下录屏展示了： （1）、（4）、（6）：
> 
> https://user-images.githubusercontent.com/21048245/205493998-51bc50e1-454a-47d4-a69e-8ce5ba6b9499.mp4
> 
> 
> 1. 重复朗读“点击以展开或收起导航栏”，通过 NVDA +F1 查看日志，发现该控件具有 description 属性；
> 2. 那就保持现状吧；
> 4. 点击“展开或收起导航栏”可能视觉上有变化，使用 tab 键查看并没有发现焦点的改变；
> 6. 在录屏中，在筛选输入框中键入“365”理想化的效果应该列表中只展示包含365的项目，不知道是否是这样。
> 
> 

1. 代码中没有设置 description，微软的“讲述人”也不会发生此类问题。
4. 这个怎么说呢，肯定是视觉上的改变啊。那总不能关了然后喊一句导航栏已关闭吧。而且我也没有发现有这类 API 可以调用。
6. 录屏里面我没发现有任何问题，一切都是正常的。

**Comment by cary-rowen** [comment]
> > 以下录屏展示了： （1）、（4）、（6）：
> > 
> >   
> >     
> >     
> > 
> >     20221204_213525.mp4
> >     
> >   
> > 
> >   
> > 
> >   
> > 
> > 
> > 
> > 1. 重复朗读“点击以展开或收起导航栏”，通过 NVDA +F1 查看日志，发现该控件具有 description 属性；
> > 2. 那就保持现状吧；
> > 3. 点击“展开或收起导航栏”可能视觉上有变化，使用 tab 键查看并没有发现焦点的改变；
> > 4. 在录屏中，在筛选输入框中键入“365”理想化的效果应该列表中只展示包含365的项目，不知道是否是这样。
> 
> 1. 代码中没有设置 description，微软的“讲述人”也不会发生此类问题。
    - 可能是 NVDA 的问题，我会再观察一下。
> 2. 这个怎么说呢，肯定是视觉上的改变啊。那总不能关了然后喊一句导航栏已关闭吧。而且我也没有发现有这类 API 可以调用。
  - 按钮这种特性点击后不具有 stateChange 事件，如果只是视觉上的改变的话对屏幕阅读器操作无感可以设置不具有  tab 焦点，总之这一点影响不大。
> 3. 录屏里面我没发现有任何问题，一切都是正常的。

**Comment by cary-rowen** [comment]
> 已发布了新的 Alpha，您可以验证问题是否已解决或仍然存在，同时我们针对产品、语言、许可证列表进行了修复，修复了筛选之后无法使用 Tab 进行导航的问题。

---

我测试了 release 页的最新版：第一次输入关键词（如： 365）筛选 tab 键可正常聚焦筛选后的列表，删除关键词输入另一个关键词（如： 2016）使用 Tab 键则无法再次找到筛选结果列表，但筛选列表确实是显示了，只是不具有 Tab 焦点。
添加语言和许可证的筛选列表存在同样的问题。

---

有看到在“添加产品”和“添加语言”点击确定后设置了焦点停留，但点击“取消”或者按  Esc 关闭对话框后焦点依然会被重置，理想状态下，按   ESC 取消添加，焦点应该继续停留在“添加”按钮上。

---

工具箱里的“恢复”按钮改好了，备份按钮依然存在 description 信息，可删除。

谢谢，辛苦了

**Comment by cary-rowen** [comment]
您好，我测试了最新的版本，目前来说所提到的问题都解决了。
如您所说，产品、语言和许可证列表内的列表项不能被正确朗读，这个问题大概会在正式版中被修复吗？
尤其是添加产品，属于高频功能，如果不能正确读出列表项的标题确实会比较麻烦。
再次感谢。

**Comment by YerongAI** [comment]
> 您好，我测试了最新的版本，目前来说所提到的问题都解决了。
> 如您所说，产品、语言和许可证列表内的列表项不能被正确朗读，这个问题大概会在正式版中被修复吗？
> 尤其是添加产品，属于高频功能，如果不能正确读出列表项的标题确实会比较麻烦。
> 再次感谢。

会修复的，我只是当时测试的时候忘了而已 😅

**Comment by YerongAI** [comment]
> 您好，我测试了最新的版本，目前来说所提到的问题都解决了。
> 如您所说，产品、语言和许可证列表内的列表项不能被正确朗读，这个问题大概会在正式版中被修复吗？
> 尤其是添加产品，属于高频功能，如果不能正确读出列表项的标题确实会比较麻烦。
> 再次感谢。

最近测试版应该没有问题了。

**Comment by cary-rowen** [comment]
这个版本体验很棒了，感谢感谢👍

**Comment by cary-rowen** [comment]
补充一个，点击“卸载”产品后焦点被重置了，建议停留到“取消”按钮上

**Comment by YerongAI** [comment]
> 补充一个，点击“卸载”产品后焦点被重置了，建议停留到“取消”按钮上

我设置的是跳转到另一个产品的卸载按钮，在我这边没有发现问题。

停留在取消按钮上对于代码实现来说有点难度。

**Comment by cary-rowen** [comment]
> 我设置的是跳转到另一个产品的卸载按钮，在我这边没有发现问题。

---
如果只有一个产品的话可能就会出问题吧，我这里是只有一个 Office365点“卸载”焦点回到了“底部导航栏”，如果无法聚焦到“取消”按钮，聚焦到“添加产品”按钮应该也会好一点，毕竟不用从头再按Tab 找了。

**Comment by YerongAI** [comment]
> > 我设置的是跳转到另一个产品的卸载按钮，在我这边没有发现问题。
> 
> 如果只有一个产品的话可能就会出问题吧，我这里是只有一个 Office365点“卸载”焦点回到了“底部导航栏”，如果无法聚焦到“取消”按钮，聚焦到“添加产品”按钮应该也会好一点，毕竟不用从头再按Tab 找了。

已了解并修复了此问题。
