### ISSUE TITLE
[IDEA] 关于重置Office设置，注册表还有个键似乎也应该删

### ISSUE THREAD

**Issue by davictor233** [YerongAI/Office-Tool#559]
**Feature description:**
> HKEY_CURRENT_USER\SOFTWARE\Microsoft\Shared Tools

**How it work?**
> 这个键也是Office生成的，一些Office设置比如Word里“选项-校对”保存在这里。9.0.3.7的重置Office设置似乎不会重置这里。

Technical Reference (if possible):
> 删除该键。

**Comment by YerongAI** [comment]
好的，经研究后决定删除以下几个注册表项：

```
HKEY_CURRENT_USER\SOFTWARE\Microsoft\Shared Tools\Font Mapping
HKEY_CURRENT_USER\SOFTWARE\Microsoft\Shared Tools\Outlook
HKEY_CURRENT_USER\SOFTWARE\Microsoft\Shared Tools\Panose
HKEY_CURRENT_USER\SOFTWARE\Microsoft\Shared Tools\Proofing Tools
```
