### ISSUE TITLE
[ASK] 一顿操作之后下不了了

### ISSUE THREAD

**Issue by greenwink** [YerongAI/Office-Tool#560]
大神你好，我的情况是这样的：我按照一个B站教程安装，进度条一直卡在51%不动，就按MSoffice官网的解决方案操作，结果重启后点开始部署提示说需要下载的文件都已经下好了，但是excel这些文件前面的图标的都是一张白色的纸，也打不开。点office的setup弹出一个黑色框，过一两秒黑色框闪退，提示office部署工具未正常退出。请问我该怎么办呢？

**Comment by YerongAI** [comment]
你是不是忘了把部署模式改成安装？

**Comment by greenwink** [comment]
应该是！我又对着b站的教程调整了一遍，那个正在安装office的界面又出来了！多谢！



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2022年9月26日(周一) 晚上6:19
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [YerongAI/Office-Tool] [ASK] 一顿操作之后下不了了 (Issue #560)

**Comment by greenwink** [comment]
你好，这个又卡在51%不动了，一小时多了，是网速原因还是其他原因呀





------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "YerongAI/Office-Tool"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年9月26日(星期一) 晚上6:19
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [YerongAI/Office-Tool] [ASK] 一顿操作之后下不了了 (Issue #560)





 
你是不是忘了把部署模式改成安装？

**Comment by YerongAI** [comment]
> 你好，这个又卡在51%不动了，一小时多了，是网速原因还是其他原因呀
> 
> 
> 
> 
> 
> ------------------&nbsp;原始邮件&nbsp;------------------
> 发件人:                                                                                                                        "YerongAI/Office-Tool"                                                                                    ***@***.***&gt;;
> 发送时间:&nbsp;2022年9月26日(星期一) 晚上6:19
> ***@***.***&gt;;
> ***@***.******@***.***&gt;;
> 主题:&nbsp;Re: [YerongAI/Office-Tool] [ASK] 一顿操作之后下不了了 (Issue #560)
> 
> 
> 
> 
> 
>  
> 你是不是忘了把部署模式改成安装？
>  
> —
> Reply to this email directly, view it on GitHub, or unsubscribe.
> You are receiving this because you authored the thread.Message ID: ***@***.***&gt;

这个地方不动多半是文件损坏，建议校验安装文件。

**Comment by greenwink** [comment]
请问校验安装文件是用这个方法吗？我想下载这个文件被浏览器拦截了



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2022年9月26日(周一) 晚上11:10
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [YerongAI/Office-Tool] [ASK] 一顿操作之后下不了了 (Issue #560)
