### ISSUE TITLE
[ASK] 產品啟動失敗

### ISSUE THREAD

**Issue by a406010503** [YerongAI/Office-Tool#561]
- 作業系統：Windows 11 專業版 22H2 (22621.608)
- Office 版本：Microsoft Office LTSC 專業增強版 2021（大量授權）
- 操作過程：使用 Office-Tool 部屬過程都正常，也有做 KMS 伺服器設定，並點選啟用。(也有嘗試完整解除安裝再重新安裝)
- 錯誤訊息：開啟任一個 Office 程式每次皆會跳出「Microsoft Office 無法驗證此產品的授權，您應該使用[控制台]修復此Office程式。」，並標題會顯示(產品啟動失敗)，但是任何功能都能正常使用。
- 問題截圖：
![問題截圖1](https://user-images.githubusercontent.com/50009618/194375618-8529ba79-d3c0-41a7-85dd-c334bd4a6667.png)
![問題截圖2](https://user-images.githubusercontent.com/50009618/194375692-44c41686-c51f-47fc-a496-874043c6a81d.png)

**Comment by chiyi4488** [comment]
請嘗試：(1)依微軟指示修復 Office；(2) 到啟用功能頁> 授權管理> 移除全部授權，然後再重新安裝授權和設定KMS、點選啟用。

**Comment by a406010503** [comment]
@chiyi4488 有做過無數次，遺憾的是，以上兩個方案皆無效... 也確認過不是防毒和防火牆的問題

**Comment by chiyi4488** [comment]
請嘗試透過OfficeToolPlus 工具箱內的工具嘗試修復，例如透過OfficeToolPlus強制移除Office

**Comment by a406010503** [comment]
@chiyi4488 這個也做過了，我甚至把裡面的每個功能都做一次修復，但依然不起作用。

**Comment by chiyi4488** [comment]
@YerongAI 你排解吧

**Comment by YerongAI** [comment]
> @chiyi4488 這個也做過了，我甚至把裡面的每個功能都做一次修復，但依然不起作用。

重建 Windows 激活令牌（重建啟用權杖），然后重新激活 Office.

**Comment by a406010503** [comment]
剛剛依照您的指示又做了一次，但仍無法解決出現錯誤訊息的問題

**Comment by YerongAI** [comment]
> 剛剛依照您的指示又做了一次，但仍無法解決出現錯誤訊息的問題

有点难搞其实，特别还是 Windows 11

**Comment by iDolmatov** [comment]
Does the KMS Server Check feature give a positive result for the selected server?
