### ISSUE TITLE
[ASK] 

### ISSUE THREAD

**Issue by xinxijishuwyq** [YerongAI/Office-Tool#563]
Please go to discussions for help.
能否增加office2016 的vl版

**Comment by iDolmatov** [comment]
Exist. Provide a link to the Microsoft site with the desired product if you are not sure which one to choose.
![00](https://user-images.githubusercontent.com/19782385/196008190-00d903f9-01a2-4bf7-9523-3f21fb707f57.png)

**Comment by xinxijishuwyq** [comment]
> 

![image](https://user-images.githubusercontent.com/1755898/196012011-e2761071-1574-4d25-a3c4-faecced10b44.png)
I don't show 2016 vl here

**Comment by YerongAI** [comment]
> > 
> 
> ![image](https://user-images.githubusercontent.com/1755898/196012011-e2761071-1574-4d25-a3c4-faecced10b44.png) I don't show 2016 vl here

请在设置中打开“高级功能”选项
