### ISSUE TITLE
Application doesn't launch[BUG] 

### ISSUE THREAD

**Issue by umair786155** [YerongAI/Office-Tool#564]
**Office Tool Plus Version, e.g. 8.1.0.0:**
> 9.0.3.7

**Operating System, e.g. Windows 10 20H2 or Windows 7 SP1:**
> Windows 7 SP1 x64 [MBR]

**Error description (required):**
> Application isn't launching at all. I've tried both packages (the one with no runtime, and with runtime). The required .NET framework software is already installed in the system.
Tried launching after disabling antivirus but no luck, same case in safe mode as well.

Anyway, to check what's the issue with some log or tracking method?

*Reproduction steps (suggested):*
Nothing, just trying to open application but it doesn't.

*Screenshot (suggested):*
https://youtu.be/Cc_W3RlGLwk [Video - 30 Seconds], [Recorded when system was in Safe Mode]

*Additional information (optional):*

**Comment by YerongAI** [comment]
To run Office Tool Plus, please make sure you have upgraded your Windows 7 to the latest version.

Download update pack here: https://download.coolhub.top/Extensions/Win7_UpdatePack/UpdatePack7R2-22.8.10.exe

**Comment by umair786155** [comment]
> To run Office Tool Plus, please make sure you have upgraded your Windows 7 to the latest version.
> 
> Download update pack here: https://download.coolhub.top/Extensions/Win7_UpdatePack/UpdatePack7R2-22.8.10.exe

Thanks a lot sir, upon installing this update, it started working as usual.

Thank you so much!
