### ISSUE TITLE
[ASK] 在外网下载好版本，保存成iso
，断网后，在内网部署，不成功，一直卡后台安装0%，如何解决？

### ISSUE THREAD

**Issue by zenjan1** [YerongAI/Office-Tool#565]
Please go to discussions for help.

**Comment by iDolmatov** [comment]
You need to create a report template (Issue: Bug Report).

`**Office Tool Plus Version, e.g. 8.1.0.0:**
> Write down here

**Operating System, e.g. Windows 10 20H2 or Windows 7 SP1:**
> Write down here

**Error description (required):**
> Write down here

*Reproduction steps (suggested):*

*Screenshot (suggested):*

*Additional information (optional):*
`
