### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by TimucinPusat** [YerongAI/Office-Tool#567]
When I want to download mic office word it says: Can not find Office installation files in Office Tool Plus's root directory, please download installation files first! Or move installation files to the working path. what to do? I couldn't see any option to download installation files first.

**Comment by YerongAI** [comment]
Please check "Download first, then deploy" option.

**Comment by TimucinPusat** [comment]
> Please check "Download first, then deploy" option.

It's ok now YerongAI. Thank you a lot. I understand now. Something else: I chose office 2021 home and student but when I install it through office tool plus it turns out to be Microsoft Office LTSC Professional Plus 2021. why? BTW I install only office word and excell. Is there any difference in terms of performance or working without any problems between pro plus 2021 and home and student 2021 or they alredy use the same files?

**Comment by TimucinPusat** [comment]
I downloaded office home and student 2021 again but it now says The configuration si incorrect. WHY?

**Comment by YerongAI** [comment]
There is no difference about performance.
If you are worries about terms, you should buy a license from MS.
