### ISSUE TITLE
When will Office Tool Plus support macos

### ISSUE THREAD

**Issue by CoolJosh0221** [YerongAI/Office-Tool#568]
When will office tool plus support macOS??

I'm on a MacBook Pro and I really want to deploy Microsoft 365 for free.

**Comment by YerongAI** [comment]
Ask for MS, when they will release a deploy tool for MacOS. 😪

**Comment by CoolJosh0221** [comment]
let's ask

**Comment by CoolJosh0221** [comment]
sad
