### ISSUE TITLE
软件缺少

### ISSUE THREAD

**Issue by 111juini** [YerongAI/Office-Tool#572]
我看主页有14个office软件，为什么下载后只有10个？

**Comment by iDolmatov** [comment]
1. 

> 我看主页

网址，截图？

2. https://github.com/YerongAI/Office-Tool

> Supports custom deployment and activation of the following products:

Microsoft 365.
Office 2016, 2019, 2021.
Visio 2016, 2019, 2021 & Online Plan 2.
Project 2016, 2019, 2021 & Online Desktop Client.

3. https://zh.wikipedia.org/wiki/Microsoft_Office_2010

> Microsoft Office 2010（又称为Office 2010和Office 14）
