### ISSUE TITLE
[BUG] 

### ISSUE THREAD

**Issue by Lippiman** [YerongAI/Office-Tool#573]
**Office Tool Plus Version, e.g. 8.1.0.0:**
> 9.0.3.7

**Operating System, e.g. Windows 10 20H2 or Windows 7 SP1:**
> 版本：Windows 10 专业版
>版本号：22H2

**Error description (required):**
> 部署的office版本与实际安装的版本不同。
>例如，当选择部署office家庭和学生版2016时，实际安装的是office standard 2019
*Reproduction steps (suggested):*

*Screenshot (suggested):*
![屏幕截图 2022-11-28 163821](https://user-images.githubusercontent.com/92634284/204232218-13299d10-11ec-421a-a46d-d7c928f2ec73.png)

*Additional information (optional):*

**Comment by iDolmatov** [comment]
A feature of the new Microsoft Office is to use old activation licenses if another product was previously installed.
The product type is checked in the registry.
`HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Office\ClickToRun\Configuration`
`HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Office\16.0\ClickToRunStore`
`HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Office\ClickToRun\Inventory\Office\16.0`
**ProductReleaseIds**

**Comment by YerongAI** [comment]
> A feature of the new Microsoft Office is to use old activation licenses if another product was previously installed.
> The product type is checked in the registry.
> `HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Office\ClickToRun\Configuration`
> `HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Office\16.0\ClickToRunStore`
> `HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Office\ClickToRun\Inventory\Office\16.0`
> **ProductReleaseIds**

There was another answers I think.
