### ISSUE TITLE
[BUG] 在输出的内容中尝试滑动滚轮没有用

### ISSUE THREAD

**Issue by qhy040404** [YerongAI/Office-Tool#575]
**Office Tool Plus Version, e.g. 8.1.0.0:**
> 10.0.0.4

**Operating System, e.g. Windows 10 20H2 or Windows 7 SP1:**
> 11 Beta 22623.1020

**Error description (required):**
> 在输出的内容中尝试滑动滚轮没有用，只能在输出的框外面才能翻动

*Reproduction steps (suggested):*
- 激活/工具箱 -> 查询版本信息/查询激活信息（任意有输出的即可）

*Screenshot (suggested):*

*Additional information (optional):*

**Comment by YerongAI** [comment]
是这样的，我也不知道怎么解决

**Comment by YerongAI** [comment]
具体点来说，是因为有输出的那一部分里面也有一个 Scroll Viewer，外面还有一层，就导致了两个冲突，但是实际上里面那个是滚不起来的，所以就造成了滑动没有任何反应，这在之前任何一个版本上的 OTP 都是这样的。我尝试过自定义控件把这个 Scroll Viewer 去掉，但会出现奇奇怪怪的 bug，所以还是放弃了。

至少，目前是没有办法的。

**Comment by qhy040404** [comment]
把里面那个ScrollViewer接受到的event捕获下来 然后让外层的执行呢

**Comment by YerongAI** [comment]
> 把里面那个ScrollViewer接受到的event捕获下来 然后让外层的执行呢
> 
> 或者说直接注册到一个滚轮event上 ![微信图片_20221203174334](https://user-images.githubusercontent.com/45379733/205434589-ddc9e6da-f2a4-43bd-ae58-a6050a6e7881.png)

像 FlowDocumentScrollViewer 和 DataGrid 这种控件，它们自己就带一个 Scroll Viewer，而且在用户代码里面是看不见的，只有运行的时候在可视化树里面才看得见。

最佳的做法还是重写它们的 Template，这样能从源头去掉这个“内置”的 Scroll Viewer

**Comment by qhy040404** [comment]
想到一个可能的解决方案
先获取到FlowDocumentScrollViewer内部（子控件）的ScrollViewer对象，然后把它的`PreviewMouseWheel`绑定到外层的ScrollViewer上面

**Comment by qhy040404** [comment]
或者说简单粗暴
```cs
/// <summary>
/// inner: ScrollViewer 中的 FlowDocumentScrollViewer
/// outSV: 外层的 ScrollViewer
/// </summary>
/// <param name="sender"></param>
/// <param name="e"></param>
private void inner_PreviewMouseWheel(object sender, MouseWheelEventArgs e)
{
    if (sender is not FlowDocumentScrollViewer)
        return;
    outSV.ScrollToVerticalOffset(outSV.VerticalOffset - e.Delta);
}
```

**Comment by YerongAI** [comment]
激活页面的 FlowDocument 已经移除了，激活页面不再存在这个问题。

DataGird 还在工具箱、文档转换、哈希值校验这几个地方使用中。
