### ISSUE TITLE
高分屏适配

### ISSUE THREAD

**Issue by tim-wang-tmp** [YerongAI/Office-Tool#576]
**Feature description:**
> 目前好像不支持高分屏，高分屏字太小了。

**How it work?**
> Write down here

Technical Reference (if possible):
> ![微信截图_20221205204343](https://user-images.githubusercontent.com/1762601/205641605-425c4c6a-8a19-4baa-b991-5c236ad9beb5.png)

**Comment by YerongAI** [comment]
别的程序呢？
