### ISSUE TITLE
[BUG] Office Tool Plus v10.0.2.2 Beta 自动更新问题

### ISSUE THREAD

**Issue by fuchanghao** [YerongAI/Office-Tool#583]
**Office Tool Plus Version, e.g. 8.1.0.0:**
> Office Tool Plus v10.0.2.2

**Operating System, e.g. Windows 10 20H2 or Windows 7 SP1:**
> Windows 10 IoT LTSC 2021 19044.2364

**Error description (required):**
> 自动更新时并没有更新.NET Core运行库版本。

*Reproduction steps (suggested):*
1.下载旧版本，例如Office Tool Plus v10.0.1.0 Beta。
2.等待软件进行自动更新。
3.发现更新后.NET Core运行库版本依旧是6.0.11，而非全新下载的含运行库版本的6.0.12。

*Screenshot (suggested):*

*Additional information (optional):*

**Comment by YerongAI** [comment]
我晓得，我就是这样设置的
