### ISSUE TITLE
将背景改为模糊会出现拖动窗口延时（win1122621.900）

### ISSUE THREAD

**Issue by xiaohuluobo** [YerongAI/Office-Tool#584]
**Office Tool Plus Version, e.g. 8.1.0.0:**
> Write down here

**Operating System, e.g. Windows 10 20H2 or Windows 7 SP1:**
> Write down here

**Error description (required):**
> Write down here

*Reproduction steps (suggested):*

*Screenshot (suggested):*

*Additional information (optional):*

**Comment by YerongAI** [comment]
你们什么时候才能学会提问的智慧？
