### ISSUE TITLE
[BUG] 在设置中进行的修改无法保存

### ISSUE THREAD

**Issue by gnlio** [YerongAI/Office-Tool#585]
**Office Tool Plus Version, e.g. 8.1.0.0:**
> Write down here
10.0.2.2
**Operating System, e.g. Windows 10 20H2 or Windows 7 SP1:**
> Write down here
Windows 11 22H
**Error description (required):**
> Write down here
在设置中进行的修改无法保存
*Reproduction steps (suggested):*
在设置中进行修改，退出程序
重新打开应用
*Screenshot (suggested):*

*Additional information (optional):*

**Comment by YerongAI** [comment]
有没有一种可能就是说你忘了打开保存设置到本地这个选项。
