### ISSUE TITLE
[BUG] 创建ISO时的问题

### ISSUE THREAD

**Issue by VMwareEFI** [YerongAI/Office-Tool#586]
就像这样
![image](https://user-images.githubusercontent.com/109196429/208813361-551e7180-7e50-4505-a970-c138d88b91a5.png)
版本10.0.2.6
文件结构图
![image](https://user-images.githubusercontent.com/109196429/208813576-0c01c999-593a-447d-95ab-0024e50d0eb8.png)

**Comment by YerongAI** [comment]
确实没有安装文件啊，要先下载啊

**Comment by YerongAI** [comment]
还有你那个多出来的 Runtime 文件夹是什么

**Comment by VMwareEFI** [comment]
怎么下载
（已经装了LTSC2021）

**Comment by VMwareEFI** [comment]
![image](https://user-images.githubusercontent.com/109196429/209270050-29ea3d67-bd81-4e10-a09d-c1c0310a4c18.png)
runtime里的

**Comment by YerongAI** [comment]
1. 删除 Runtime 文件夹和 setup.bat，那都是老久之前才需要的东西了。
2. 勾选下载后再部署，会自动下载所需要的文件。

**Comment by VMwareEFI** [comment]
可以了
![image](https://user-images.githubusercontent.com/109196429/209495997-0f1f254d-c1bd-4fae-a8b9-44a28a7d8070.png)
