### ISSUE TITLE
[ASK]

### ISSUE THREAD

**Issue by liyaoqi20081120** [YerongAI/Office-Tool#587]
无法部署office
![E90BA52C-9102-46a8-B85A-4FAC648A5630](https://user-images.githubusercontent.com/121273110/209263776-cc9ff033-89fc-434d-a58a-81d192b31363.png)

**Comment by YerongAI** [comment]
Windows 7 请改用 Office Tool Plus 作为安装模块，安装模块默认是 Office 部署工具。
