### ISSUE TITLE
[ASK] 

### ISSUE THREAD

**Issue by liyaoqi20081120** [YerongAI/Office-Tool#588]
无法部署

![B71AAABC-725C-414a-8D44-CD6E934C6BEE](https://user-images.githubusercontent.com/121273110/209285167-af6584f4-4464-4dc6-86ae-e14ca085df56.png)

**Comment by YerongAI** [comment]
1. 网有问题，建议检查网络环境，实在不行勾选上下载后再部署。
2. Windows 7 就不要妄想安装 Office 2021 了。
3. 请不要在 GitHub 重复提交 issue
