### ISSUE TITLE
[BUG] win7可以下载office2021

### ISSUE THREAD

**Issue by ningjingzhe** [YerongAI/Office-Tool#594]
win7可以下载office2021，但是安装又提示不支持。所以一开始应该提示不支持才对。

**Comment by YerongAI** [comment]
你有没有想过可以下载下来做安装包分享出去呢？

**Comment by iDolmatov** [comment]
To check v10.0.3.3, I selected the target Windows 7 system in the ODT settings, but when downloading, I get the current version. This is older than the version given in the documentation.
https://learn.microsoft.com/en-us/deployoffice/endofsupport/windows-7-support

> Microsoft 365 Apps Update for Windows 7 – Version 2002 for x64 based Edition (Build 12527.#####)
> Microsoft 365 Apps Update for Windows 7 – Version 2002 for x86 based Edition (Build 12527.#####)


So what's missing is a notification that the version you're getting won't work for Windows 7.
Similarly for Windows 8. In the official documentation, builds are not indicated, only versions based on the date. But the builds are shown in the API. Links on discord.
