### ISSUE TITLE
[BUG] 重启dwm会使程序崩溃

### ISSUE THREAD

**Issue by 1357310795** [YerongAI/Office-Tool#595]
**Office Tool Plus Version, e.g. 8.1.0.0:**
> 10.0.3.3

**Operating System, e.g. Windows 10 20H2 or Windows 7 SP1:**
> Windows 10 专业版 22H2

**Error description (required):**
> 我的电脑日常dwm内存泄漏（重装系统都没有用）
> ![{I0K$EE{OO3QOO1$~N}XO5A](https://user-images.githubusercontent.com/35869804/211526883-4dc91a9c-42a6-4b29-b627-a3f703a71a02.png)
> 一般重启dwm就好了
> 但是Office Tool Plus 在重启dwm的时候会崩溃

*Reproduction steps (suggested):*

*Screenshot (suggested):*
![QQ截图20230110182629](https://user-images.githubusercontent.com/35869804/211527014-b246d987-6ee8-4b55-95a0-a3dcdb473f4a.png)

*Additional information (optional):*

**Comment by YerongAI** [comment]
这个基本上就是会崩溃的，没办法能避免。
