### ISSUE TITLE
[BUG] 希望能对于选择的语言不存在之后做一个比较好的判断。

### ISSUE THREAD

**Issue by fuchanghao** [YerongAI/Office-Tool#596]
**Office Tool Plus Version, e.g. 8.1.0.0:**
> [v9.0.4.2](https://github.com/YerongAI/Office-Tool/releases/tag/v9.0.4.2) / [v10.0.3.3](https://github.com/YerongAI/Office-Tool/releases/tag/v10.0.3.3)

**Operating System, e.g. Windows 10 20H2 or Windows 7 SP1:**
> Windows 10 IoT LTSC 2021 x64

**Error description (required):**
> 

*Reproduction steps (suggested):*

1.新建一个Office Tool的下载，下载通道选择Windows 7通道（16.0.12527.22286）。
2.下载的时候语言选择en-gb，进行下载。
3.下载的时候提示下载超时。

*Screenshot (suggested):*

![屏幕截图 2023-01-11 104102](https://user-images.githubusercontent.com/11471475/211709532-c550bab8-9d25-4d60-b316-81097df18842.png)

*Additional information (optional):*

希望能在指定通道之后获取该版本包含的语言，自动跳过该版本不包含的语言。

**Comment by YerongAI** [comment]
自动跳过不可能，因为没有相关信息可以检阅。

出错后继续下载倒是可以，但意义不是很大。
