### ISSUE TITLE
[BUG] 软件授权服务报告应用程序正在有效的宽限期内运行。(无法激活、无法安装许可证)

### ISSUE THREAD

**Issue by InThe-Darkness** [YerongAI/Office-Tool#601]
**Office Tool Plus Version, e.g. 8.1.0.0:**
> 9.0.3.7

**Operating System, e.g. Windows 10 20H2 or Windows 7 SP1:**
> windows11

**Error description (required):**
> Office 激活处理
 
Office 21, Office21Excel2021R OEM Perp edition
•	许可证说明: Office 21, RETAIL channel
•	SKU ID: 42c9d0c4-a27f-49e1-a929-3227cd0c6b92
•	许可证状态:  未许可 
•	错误代码: 0xC004F014
•	错误信息: 软件许可服务报告产品密钥不可用。
 
Office 21, Office21Excel2021R Grace edition
•	许可证说明: Office 21, RETAIL(Grace) channel
•	SKU ID: 4c8d9af4-ae41-473a-bbb6-da498ac55e3f
•	许可证状态:  OOB_宽限期 
•	错误代码: 0x4004F00C
•	错误信息: 软件授权服务报告应用程序正在有效的宽限期内运行。
•	剩余期限: 4 天 (7054 分钟后到期)
•	产品密钥的最后五个字符: Q3Y68
 
Office 21, Office21Excel2021R Trial edition
•	许可证说明: Office 21, TIMEBASED_EVAL channel
•	SKU ID: 950dfc5d-6ffd-49b8-939b-7a823f03dbf6
•	许可证状态:  未许可 
•	错误代码: 0xC004F014
•	错误信息: 软件许可服务报告产品密钥不可用。
 
Office 21, Office21Excel2021R Retail edition
•	许可证说明: Office 21, RETAIL channel
•	SKU ID: fb099c19-d48b-4a2f-a160-4383011060aa
•	许可证状态:  未许可 
•	错误代码: 0xC004F014
•	错误信息: 软件许可服务报告产品密钥不可用。

*Reproduction steps (suggested):*

*Screenshot (suggested):*

*Additional information (optional):*

**Comment by YerongAI** [comment]
这种激活问题要么自己去看教程要么花钱买正版。
