### ISSUE TITLE
[BUG] Office Tool Plus.Console 部署报错 0-2039 (0)

### ISSUE THREAD

**Issue by Roger-WIN** [YerongAI/Office-Tool#602]
**Office Tool Plus Version, e.g. 8.1.0.0:**
> 10.0.4.7

**Operating System, e.g. Windows 10 20H2 or Windows 7 SP1:**
> Windows 11/10 22H2

**Error description (required):**
> 使用 Office Tool Plus.Console 来部署 Office，总会出现弹窗报错，错误码 0-2039 (0)。

*Reproduction steps (suggested):*

1. 以管理员权限启动 PowerShell；
2. 定位到 Office Tool Plus.Console.exe 所在的目录；
3. 执行如下命令
    ```pwsh
    .\"Office Tool Plus.Console" deploy /addProduct "O365HomePremRetail_zh-cn_Access,Publisher,OneDrive,Outlook" /clientEdition 64 /display false /downloadFirst
    ````

*Screenshot (suggested):*

![image](https://user-images.githubusercontent.com/25821208/212286092-63358ec4-414f-4807-9e7a-af42fd4e571a.png)

*Additional information (optional):*

- 尝试过在 `deploy` 命令后跟其它 SKU 的 Office，一样会报错。
- 从 PowerShell Core 改为 Windows PowerShell 和命令提示符，也还是会报错。

**Comment by qhy040404** [comment]
没加`Channel`

**Comment by Roger-WIN** [comment]
> 没加 `Channel` ![image](https://user-images.githubusercontent.com/45379733/212320667-19b5bd94-85a9-4829-82e9-1ce82d7ca954.png)

还真的可以。

但是我看[文档](https://help.coolhub.top/zh-cn/others/commands.html#%E9%83%A8%E7%BD%B2%E5%91%BD%E4%BB%A4)里描述的 `channel` 选项明明是有默认值的呀，所以我完全没往它上面去想。

![image](https://user-images.githubusercontent.com/25821208/212356308-4cc24d0c-f455-4bde-b678-d0024a9439b4.png)

而且我将上述不含 `/channel` 的 `deploy` 命令输入到 Office Tool Plus 图形界面的命令框中是可以正常执行的。

**Comment by YerongAI** [comment]
我再调查一下这个 channel 是哪方面的问题，因为[微软官方](https://learn.microsoft.com/zh-cn/deployoffice/office-deployment-tool-configuration-options#channel-attribute-part-of-add-element)自己也说了 channel 属于可选值。

顺带一提，download first 在这个模式下是不会工作的，仅限于在主程序上使用的时候才行。

**Comment by YerongAI** [comment]
您好。

在调查之后，我认为现在的 ODT 需要传递 Channel 参数才可以正常工作，即使微软官方自己的文档写的是不需要。*或者说，当本地安装有 Office 的时候才不需要吧。*

我们的说明文档将会更新这些内容。同时，我们也发现了 `/display` 参数不能正常工作的问题。这将会在下个版本中解决。

感谢您的反馈。

**Comment by Roger-WIN** [comment]
> 您好。
> 
> 在调查之后，我认为现在的 ODT 需要传递 Channel 参数才可以正常工作，即使微软官方自己的文档写的是不需要。_或者说，当本地安装有 Office 的时候才不需要吧。_
> 
> 我们的说明文档将会更新这些内容。同时，我们也发现了 `/display` 参数不能正常工作的问题。这将会在下个版本中解决。
> 
> 感谢您的反馈。

感谢，辛苦了！☺️
