### ISSUE TITLE
[IDEA] 加入Sway部署

### ISSUE THREAD

**Issue by lzy20091001** [YerongAI/Office-Tool#603]
**Feature description:**
> 如果能加入Sway的部署，那将会非常棒！

**How it work?**
> Write down here

Technical Reference (if possible):
> Write down here

**Comment by iDolmatov** [comment]
https://sway.office.com/
![2023-01-18 21 38 30](https://user-images.githubusercontent.com/19782385/213240611-237548c7-2f6f-4261-8995-29f6f008325c.png)
没有经典的应用程序。无需部署.
