### ISSUE TITLE
[BUG] 

### ISSUE THREAD

**Issue by Franknah** [YerongAI/Office-Tool#605]
**Office Tool Plus Version, e.g. 8.1.0.0:**
> 10.0.4.7

**Operating System, e.g. Windows 10 20H2 or Windows 7 SP1:**
> Windows 11 22H2

**Error description (required):**
> 当我在“设置-外观和行为-背景”选项中选择模糊时，拖动窗口时会十分怪异。窗口随鼠标拖动的速度会延迟几秒

*Reproduction steps (suggested):*
设置-外观与行为-背景，选择模糊选项
*Screenshot (suggested):*

*Additional information (optional):*

**Comment by YerongAI** [comment]
简单粗暴点说，这是微软他们的问题，跟我没关系。

硬要我解决的话，现阶段我能做的就是禁止在 Win 11 中开启这个特效。但我觉得没用，也不想管。

总之，SBMS.
