### ISSUE TITLE
[BUG] 

### ISSUE THREAD

**Issue by LeMonarchKing** [YerongAI/Office-Tool#606]
**Office Tool Plus Version, e.g. 8.1.0.0:**
> 10.0.4.7

**Operating System, e.g. Windows 10 20H2 or Windows 7 SP1:**
> Windows 11 22H2

**Error description (required):**
> 在今日的microsoft 365 更新后，以前的激活方式疑似失效被封，账户页面提示称“无法验证许可”

*Reproduction steps (suggested):*

*Screenshot (suggested):*
![image](https://user-images.githubusercontent.com/92427413/214548378-9fc27dcc-c887-457c-b74e-cb5fa5c5fad6.png)

*Additional information (optional):*

**Comment by iDolmatov** [comment]
Contact your vendor/Microsoft for license status.

If the license is active, then try resetting the activation status.
https://help.coolhub.top/zh-cn/activate/
https://help.coolhub.top/zh-cn/faq/activation.htm

**Comment by LeMonarchKing** [comment]
> 



> Contact your vendor/Microsoft for license status.
> 
> If the license is active, then try resetting the activation status. https://help.coolhub.top/zh-cn/activate/ https://help.coolhub.top/zh-cn/faq/activation.htm

I have tried all the possible methods mentioned in the files, but cannot solve the problem.

**Comment by iDolmatov** [comment]
What did the seller or support person say?

**Comment by LeMonarchKing** [comment]
I don't know, because I used the KMS server in the Office Tool Plus to activate the app, instead of paying for the official version of microsoft.

**Comment by iDolmatov** [comment]
"Microsoft 365" is paid (Microsoft subscription).

1. Reset activation with removal of keys and licenses;
2. Install a KMS-compatible [license](https://www.coolhub.top/tech-articles/products.html);
3. Choose and install a [KMS server](https://www.coolhub.top/tech-articles/kms_list.html), or start your own.
4. Perform activation.

I recommend joining the telegram channel, the discord channel is also available. The telegram has the bot-assistant, and the discord is an alternative way to discuss issues.

**Comment by YerongAI** [comment]
1. 在 Office 内退出自己的 MS 账号。
2. 关闭所有 Office 应用程序。
3. 在 Office Tool Plus 内确保 Office 已经通过 Mondo Volume 证书激活，别的批量版证书也可以，不强制要求，反正能激活就行。
4. 在工具箱页面将 Office 重置为默认设置。
5. 重新打开 Office，看一下是否正常。
