### ISSUE TITLE
[BUG] Office ISO内ConfigForISO.xml包含绝对路径

### ISSUE THREAD

**Issue by caipeter888** [YerongAI/Office-Tool#609]
**Office Tool Plus Version:**
> 10.0.4.11

**Operating System:**
> Windows 10 22H2

**Error description (required):**
> 创建Office ISO后，iso内ConfigForISO.xml的SourcePath为Office Tool安装目录的绝对路径，不便于对外分享iso文件。

*Screenshot (suggested):*
![截图](https://user-images.githubusercontent.com/84651929/216008075-46dae5cb-fb61-4764-a507-6efae6687533.png)

**Comment by YerongAI** [comment]
这个“不便”指的是会安装失败还是说会泄露某些信息？

**Comment by caipeter888** [comment]
不影响正常安装，就是不同电脑用相同版本软件相同配置生成的ISO不同，校验码不同无法使用网盘“秒传”之类的功能。要说泄露信息的话只是泄露了个软件路径，一般问题不大

**Comment by YerongAI** [comment]
> 不影响正常安装，就是不同电脑用相同版本软件相同配置生成的ISO不同，校验码不同无法使用网盘“秒传”之类的功能。要说泄露信息的话只是泄露了个软件路径，一般问题不大

但你的文件信息不一样也没法秒传啊。

**Comment by caipeter888** [comment]
是我没考虑周到了
