### ISSUE TITLE
下载安装是会了，但是找不到默认的下载的iso文件位置再哪里？

### ISSUE THREAD

**Issue by better319** [YerongAI/Office-Tool#619]
如题，求指点

**Comment by YerongAI** [comment]
没说过会默认创建 ISO 吧？那是自己手动创建的

**Comment by better319** [comment]
> 

可能我没描述清楚，
我想找到，他下载下来的安装文件。
我想知道这个安装文件的路径在哪里？

**Comment by YerongAI** [comment]
> > 
> 
> 可能我没描述清楚，
> 我想找到，他下载下来的安装文件。
> 我想知道这个安装文件的路径在哪里？

就在程序文件夹里
