### ISSUE TITLE
[IDEA] 

### ISSUE THREAD

**Issue by narulmcto** [YerongAI/Office-Tool#628]
**Feature description:**
> 不同的功能时，可不可以把无用的选项变灰？

**How it work?**
> 比如在创建ISO时，把无用的那些“产品”“语言”等等选项变灰，否则会让新用户看了很混淆

Technical Reference (if possible):
> Write down here

**Comment by YerongAI** [comment]
您好，这是有用的

**Comment by narulmcto** [comment]
邮件已收到，我会尽快查看
