### ISSUE TITLE
[ASK] 如何卸载某个版本的office/不能理解贵工具的“部署”两字

### ISSUE THREAD

**Issue by anonymouscnuser** [YerongAI/Office-Tool#647]
当前版本：10

我并不是对office很熟悉的玩家

现在情况是，电脑里有两个office让我很不爽
![image](https://user-images.githubusercontent.com/68681806/227708379-10e9bfba-e415-452c-9a94-992cce2f934c.png)

在这个情况下，我如何利用工具卸载我不想要的版本呢？

我点击“开始部署”将得到如下界面，但文字表述是又会安装一个新的office？
![image](https://user-images.githubusercontent.com/68681806/227708437-5e9b506b-fd41-458f-9f6d-4d10a39aab65.png)

**Comment by anonymouscnuser** [comment]
说白了，就是这个工具讲的还不够“人话”

**Comment by YerongAI** [comment]
您好，因为你额外勾选了 Groove 程序，因此程序会显示这个界面。请您放心，直接开始部署即可。后续我们会针对即将卸载的产品加入单独的提示信息。

**Comment by YerongAI** [comment]
已改善界面消息提示，将会在下个版本中发布。
