### ISSUE TITLE
[IDEA] 更改office更新通道功能中部分通道应当有分支名

### ISSUE THREAD

**Issue by yuijker** [YerongAI/Office-Tool#653]
**Feature description:**
> Write down here
office更新通道功能的beta通道有四个，这四个通道名都叫beta通道，但实际上他们的分支名是不同的，应当标识出这四个通道的分支名方便用户分辨。
**How it work?**
> Write down here
当开启显示内部通道这一选项时，四个Beta通道应当用括号展示其分支名。
Technical Reference (if possible):
> Write down here

![image](https://user-images.githubusercontent.com/72558803/228738940-2d07f9b1-a59b-4655-8e43-a171e0c837eb.png)

![image](https://user-images.githubusercontent.com/72558803/228739292-840db6d3-6bef-4aae-ba7d-f45314fd19a0.png)

25、29、43、45，四个Beta通道，但分支名不同，获得的office365版本号也不同。应当有分支名进行标注才更好选择。

**Comment by YerongAI** [comment]
现阶段，鼠标悬停的时候有分支名会显示。

**Comment by yuijker** [comment]
分支说明框应当出现的稍微短一点，有时很久以后才出现。

**Comment by YerongAI** [comment]
> 分支说明框应当出现的稍微短一点，有时很久以后才出现。

已从 1000 毫秒调整为 500 毫秒。
