### ISSUE TITLE
[BUG] 更新至Microsoft365后，Office Tool文件转换功能无法找到正确版本的软件。

### ISSUE THREAD

**Issue by yuang233** [YerongAI/Office-Tool#654]
**Office Tool Plus Version, e.g. 8.1.0.0:**
> 10.0.6.2

**Operating System, e.g. Windows 10 20H2 or Windows 7 SP1:**
> Windows11 22H2

**Error description (required):**
>  更新至Microsoft365后，Office Tool文件转换功能无法找到正确版本的软件。

*Reproduction steps (suggested):*

*Screenshot (suggested):*
![image](https://user-images.githubusercontent.com/111548732/228826741-435b7d6b-86bd-48ef-be51-79b49ed498e1.png)
![image](https://user-images.githubusercontent.com/111548732/228826922-d1937035-5cb2-4c5c-9b02-f93ec169ba09.png)

*Additional information (optional):*

**Comment by YerongAI** [comment]
尝试一下 Office 自带的快速修复功能

**Comment by YerongAI** [comment]
已修改此功能的逻辑，将在下个更新中发布。
