### ISSUE TITLE
[BUG] 您好！请问现在工具是部署不了吗？等待了很久，尝试了一天，没有进度。

### ISSUE THREAD

**Issue by Hurakan965** [YerongAI/Office-Tool#655]
部署365企业版的word、excel、ppt，弹出的进度框显示“We're getting things ready...”，然后就一直是这个界面，重试了一天都不行，没有看到在下载和部署的迹象与进度。

**Comment by YerongAI** [comment]
把安装模块换成 Office Tool Plus
