### ISSUE TITLE
[ASK] win7 ent 无法打开程序

### ISSUE THREAD

**Issue by cathywife** [YerongAI/Office-Tool#66]
win7 企业版无法打开office tool程序，直接报错，停止工作。
![office tool error](https://user-images.githubusercontent.com/12652922/69907675-c5948300-1413-11ea-9d12-084dd994aa0c.png)

**Comment by chiyi4488** [comment]
1. 是否可截圖錯誤詳細資訊
2. 請確認系統是否有安裝 .Net Framework 4.6.1 以上版本
3. Office Tool Plus 是否為最新版本

**Comment by YerongAI** [comment]
一般情况下，正常的系统都可以运行 Office Tool Plus，但由于某些原因导致系统损坏将无法正常运行 Office Tool Plus，建议重新安装系统以解决此问题。
