### ISSUE TITLE
[ASK] Office 2019 企业长期版下载总是任务超时

### ISSUE THREAD

**Issue by tldzyx** [YerongAI/Office-Tool#670]
如下图, 类似的配置下载2021可以, 下载2019会卡在`i640.cab.cat`这个文件直到任务超时. 尝试过使用不同的下载引擎以及使用https连接甚至是挂代理, 均是这种结果. 是我的配置哪里不对吗?
![image](https://user-images.githubusercontent.com/5987706/232333697-e8a39dd6-6a03-4b4d-9ef7-67966f337bcf.png)

**Comment by YerongAI** [comment]
我晓得了，暂时先用旧版本就可以了。
