### ISSUE TITLE
[BUG] Windows 8.1下各通道检测的版本号问题。

### ISSUE THREAD

**Issue by fuchanghao** [YerongAI/Office-Tool#671]
**Office Tool Plus Version, e.g. 8.1.0.0:**
> [v10.1.3.4](https://github.com/YerongAI/Office-Tool/releases/tag/v10.1.3.4)

**Operating System, e.g. Windows 10 20H2 or Windows 7 SP1:**
> Windows Embedded 8.1 Industry Enterprise

**Error description (required):**
> 在检测通道的时候，Windows 8.1的当前通道/月度企业通道等被锁定在2023年2月后不再更新。

根据我自己手动指定版本号进行部署的兼容性实测，从Version 2303 (Build 16227.xxxxx)开始在部署时已经不再兼容Windows 8.1，需要最低Windows 10的系统才能运行。而Version 2302 (Build 16130.xxxxx)则能够正常在Windows 8.1系统上运行，而Version 2302则可以通过半年企业通道的方式持续更新到2024年9月才结束生命周期。

*Reproduction steps (suggested):*

*Screenshot (suggested):*

*Additional information (optional):*

**Comment by YerongAI** [comment]
所以你想表达什么？

**Comment by fuchanghao** [comment]
> 所以你想表达什么？

是不是忘了更新OTP检测的Windows 8.1下检测的各种通道的版本号了？

**Comment by YerongAI** [comment]
> > 所以你想表达什么？
> 
> 是不是忘了更新OTP检测的Windows 8.1下检测的各种通道的版本号了？

这个版本号是微软决定的不是我决定的

**Comment by fuchanghao** [comment]
> > > 所以你想表达什么？
> > 
> > 
> > 是不是忘了更新OTP检测的Windows 8.1下检测的各种通道的版本号了？
> 
> 这个版本号是微软决定的不是我决定的

了解了，看来是微软没有Version 2302到Windows 8.1上了。
