### ISSUE TITLE
[ASK] 

### ISSUE THREAD

**Issue by xRorkr** [YerongAI/Office-Tool#672]
can I use it to deactivate the error that gives office 2019, that the office is not original ?

**Comment by YerongAI** [comment]
Sorry I can't understand, could you explain it clearly?

**Comment by iDolmatov** [comment]
Do you see a message about the product being unlicensed (not a genuine license)?

In most cases, it is enough to reset and clear the activation. After that, install the required license, key. If you use KMS, then specify the address. Perform activation.
Make sure you are using the latest version of the program.

**Comment by xRorkr** [comment]
> Do you see a message about the product being unlicensed (not a genuine license)?
> 
> In most cases, it is enough to reset and clear the activation. After that, install the required license, key. If you use KMS, then specify the address. Perform activation. Make sure you are using the latest version of the program.

Yess !! ty !!
