### ISSUE TITLE
[BUG] Acrylic not work亚克力效果不显示

### ISSUE THREAD

**Issue by TonyBlur** [YerongAI/Office-Tool#683]
**Office Tool Plus Version, e.g. 8.1.0.0:**
>10.1.7.1

**Operating System, e.g. Windows 10 20H2 or Windows 7 SP1:**
> Windows 11 build 25357

**Error description (required):**
> 在设置中更改亚克力/模糊背景效果不生效，表现为灰色背景

*Screenshot (suggested):*
![image](https://github.com/YerongAI/Office-Tool/assets/101348912/913e69ce-470a-44d0-9509-0b5ab058cfd7)

**Comment by iDolmatov** [comment]
The developer was previously informed, but there is no solution. 
I hope he will fix the error or make the item auto-hide when unavailable.

**Comment by YerongAI** [comment]
已修复，Fixed.
