### ISSUE TITLE
[BUG] OneNote is installed even though the install option is unchecked

### ISSUE THREAD

**Issue by JeepWillys58** [YerongAI/Office-Tool#692]
**Office Tool Plus Version, e.g. 8.1.0.0:**

v10.1.8.5 with Runtime

**Operating System, e.g. Windows 10 20H2 or Windows 7 SP1:**

Edition		Windows 11 Pro
Version		22H2
Install Date	15/‎05/‎2023
Compilation	22621.1755
Experience	Windows Feature Experience Pack 1000.22642.1000.0

**Error description (required):**

Even after customizing the Office-Tool configuration to not install some of the Office Pro Plus applications, like OneNote, after the installation is finished the OneNote application continues to be installed, I tried three times using the following installation channels:

Office 2021 Perpetual Enterprise Production::LTSC2021 16.0.14332.20503 05/16/2023 14:15:14

Semi-Annual Enterprise Channel Production::DC 16.0.15601.20660 05/17/2023 11:35:19

Current Channel Production::CC 16.0.16327.20248 05/13/2023 11:20:19

In all installation attempts the same thing happens, and even unchecking OneNote so that it is not installed it ends up being installed the same way.

*Reproduction steps (suggested):*

I customize the configuration first, then save the configuration file and perform the installation.

*Screenshot (suggested):*

https://i.ibb.co/sRYrsxt/OTP-Version.png
https://i.ibb.co/xM6qd8n/System.png
https://i.ibb.co/WDxSdBg/Config-No-One-Note-App.png
https://i.ibb.co/wS1y4Ph/One-Note-App-Installed.png

*Additional information (optional):*

Configuration file used:

InstallConfiguration-2023_05_17.xml
`<Configuration>
  <Add OfficeClientEdition="64" Channel="PerpetualVL2021" SourcePath="O:\@llOptionalApps\4-CommomApps64bit\OfficeToolPlusInstaller" Version="16.0.14332.20503" AllowCdnFallback="true">
    <Product ID="ProPlusSPLA2021Volume" PIDKEY="FXYTK-NJJ8C-GB6DW-3DYQT-6F7TH">
      <Language ID="MatchOS" Fallback="pt-br" />
      <ExcludeApp ID="Lync" />
      <ExcludeApp ID="OneNote" />
      <ExcludeApp ID="Teams" />
    </Product>
  </Add>
  <Display Level="None" AcceptEULA="True" />
  <Property Name="AutoActivate" Value="1" />
  <Updates Enabled="true" />
  <Updates Channel="ProPlusSPLA2021Volume" Enabled="true" />  
  <Extend DownloadFirst="true" Module="1" />
</Configuration>`

**Comment by YerongAI** [comment]
Thank you for your info, we have fixed the issue. Please wait for the new version.

**Comment by JeepWillys58** [comment]
> Thank you for your info, we have fixed the issue. Please wait for the new version.

I had seen that you had already completed V10.1.9 yesterday (2022/05/17). Is it possible a beta of her to test if this still occurs?

OFF TOPIC:
By the way, I made a fork of this repository, I am intended to help PT-BR translations, if possible in testing new versions and dirting improvements with the vision of the common user, because I have an almost null knowledge of code.

What documents do you allow them to be translated?

Thank you in advance.

Best Regards.

**Comment by iDolmatov** [comment]
> By the way, I made a fork of this repository, I am intended to help PT-BR translations, if possible in testing new versions and dirting improvements with the vision of the common user, because I have an almost null knowledge of code.

@igorruckert planning to update the translation?
[History "pt-br"](https://github.com/YerongAI/Office-Tool/commits/main/src/OfficeToolPlus/Dictionaries/Languages/pt-br.xaml)

> What documents do you allow them to be translated?

If the language is native to you, or you have professional skills, then follow the instructions. Machine translation is inappropriate, linguistic problems are possible.
https://github.com/YerongAI/Office-Tool#help-with-localization
https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/working-with-forks/about-forks

**Comment by igorruckert** [comment]
@iDolmatov 

Yes, I'm still active and want to keep translation always updated ;)

**Comment by YerongAI** [comment]
The issue of install option was fixed.

If you have any questions about translation or others, please open new issues or discussion.
