### ISSUE TITLE
[BUG] 

### ISSUE THREAD

**Issue by Wangdage666** [YerongAI/Office-Tool#703]
**Office Tool Plus Version, e.g. 8.1.0.0:**
> Write down here
10.1.10.1
**Operating System, e.g. Windows 10 20H2 or Windows 7 SP1:**
> Write down here
Win11
**Error description (required):**
> Write down here
安装许可证时没有反应，右下角运行ospp几秒钟就没了，且没有许可证被安装，试了一下旧版本还是可以的
*Reproduction steps (suggested):*

*Screenshot (suggested):*

*Additional information (optional):*

**Comment by YerongAI** [comment]
请问安装许可证之后能不能在许可证列表里面刷新看到？
