### ISSUE TITLE
[BUG]无法获取内容

### ISSUE THREAD

**Issue by hxinbeng** [YerongAI/Office-Tool#709]
**Office Tool Plus Version, e.g. 8.1.0.0:**
v10.1.10.1

**Operating System, e.g. Windows 10 20H2 or Windows 7 SP1:**
Windows 10 22H2

**Error description (required):**
> Write down here

*Reproduction steps (suggested):*

*Screenshot (suggested):*

*Additional information (optional):*

软件无法正常使用

**Comment by YerongAI** [comment]
有没有可能就是说无法获取内容也不影响你用软件
