### ISSUE TITLE
[ASK]请问怎么选择安装路径？不想装C盘

### ISSUE THREAD

**Issue by tedlz** [YerongAI/Office-Tool#71]
设置里找遍了，也google过了，没找到方法

**Comment by YerongAI** [comment]
### Office 帮助文档原文

[原文链接](https://github.com/YerongAI/Office-Tool/blob/master/Tips/zh-cn/Deploy.md#%E9%83%A8%E7%BD%B2-office-%E8%AF%B4%E6%98%8E)

由于微软限制，Office 仅可以安装在系统盘上。
