### ISSUE TITLE
部署的时候出现问题部署不了

### ISSUE THREAD

**Issue by damieai** [YerongAI/Office-Tool#711]
**Office Tool Plus Version, e.g. 8.1.0.0:**
> Write down here
10.1.10.1
**Operating System, e.g. Windows 10 20H2 or Windows 7 SP1:**
> Write down here
第一个错误是在选择office tool plus的错误图片
第二个图片是在选择部署工具时候的错误图片
**Error description (required):**
> Write down here
代理什么的也设置过了,清除office和恢复重置也都弄过了但是还是不行
*Reproduction steps (suggested):*

*Screenshot (suggested):*
![image](https://github.com/YerongAI/Office-Tool/assets/103806899/a542c6aa-66f7-44fa-b9fb-2800f1f4f742)
![image](https://github.com/YerongAI/Office-Tool/assets/103806899/0705b85f-8974-4942-aac0-ab3806511dfd)

*Additional information (optional):*

**Comment by YerongAI** [comment]
工具箱修复 Windows 环境变量

**Comment by damieai** [comment]
我刚刚使用的微软提供的Office卸载工具清除了它的注册表,但是似乎这是没有产生效果,请问用什么工具箱可以修复这个错误,可以提供链接或者教程链接么,感谢

**Comment by YerongAI** [comment]
> 我刚刚使用的微软提供的Office卸载工具清除了它的注册表,但是似乎这是没有产生效果,请问用什么工具箱可以修复这个错误,可以提供链接或者教程链接么,感谢

我说的是 Office Tool Plus 的工具箱页面。

**Comment by damieai** [comment]
我之前用过otp的工具移除没有效果,后面我还原回去一个系统点之后再卸载就可以了
