### ISSUE TITLE
[BUG] 当OfficeClickToRun.exe运行时无论如何都无法激活Office

### ISSUE THREAD

**Issue by NatsumiXD** [YerongAI/Office-Tool#712]
**Office Tool Plus Version, e.g. 8.1.0.0:**
> 10.1.10.1

**Operating System, e.g. Windows 10 20H2 or Windows 7 SP1:**
> Windows10 20H2

**Error description (required):**
> 当OfficeClickToRun.exe运行时无论如何都无法激活Office，但是只要结束此进程即可继续激活

*Reproduction steps (suggested):*
1. 部署并安装最新的LTSC 2021 专业增强版 批量许可证
2. 在激活页面激活，若OfficeClickToRun.exe正在运行，则无法正常激活
*Screenshot (suggested):*
忘记截图了（
*Additional information (optional):*

**Comment by NatsumiXD** [comment]
临时解决方案就是以管理员模式来执行`taskkill /f /im OfficeClickToRun.exe`

**Comment by YerongAI** [comment]
不能激活的时候报什么错啊？

**Comment by NatsumiXD** [comment]
> 不能激活的时候报什么错啊？

等我开个虚拟机试试看

**Comment by NatsumiXD** [comment]
算了卸载许可证再试试

**Comment by NatsumiXD** [comment]
![image](https://github.com/YerongAI/Office-Tool/assets/63963655/26f6bbd9-4268-45a1-be2e-a6deb801e8cd)

**Comment by NatsumiXD** [comment]
```
Office 21, Office21Standard2021VLKMSClient_AE edition
•	描述: Office 21, VOLUME_KMSCLIENT channel
•	错误代码: 0x8007007B
```
