### ISSUE TITLE
[ASK]  0xC004F017是什么报错原因？

### ISSUE THREAD

**Issue by woshiniba-debug** [YerongAI/Office-Tool#713]
Please go to [discussions](https://github.com/YerongAI/Office-Tool/discussions) for help.

**Comment by iDolmatov** [comment]
1. 
![image](https://github.com/YerongAI/Office-Tool/assets/19782385/aa661ac5-696c-42ae-9d42-cada3fac81d0)
2. Go to Google or [discussions](https://github.com/YerongAI/Office-Tool/discussions).
3. Read https://learn.microsoft.com/en-us/answers/questions/320884/kms-error-code-0xc004f017-software-licensing-servi and similar.

**Comment by YerongAI** [comment]
请查看[帮助文档](https://otp.landian.vip/help/?error_code=0xC004F017)
