### ISSUE TITLE
怎么管理卸载指定的组件（比如：access）

### ISSUE THREAD

**Issue by windows99** [YerongAI/Office-Tool#72]

**Comment by YerongAI** [comment]
### Office Tool Plus 帮助文档原文

[原文链接](https://github.com/YerongAI/Office-Tool/blob/master/Tips/zh-cn/Deploy.md#%E4%BF%AE%E6%94%B9%E5%BA%94%E7%94%A8%E7%A8%8B%E5%BA%8F)

#### 修改应用程序

如果您需要修改应用程序，请首先选中这个产品，然后将不需要的应用程序取消勾选，将需要添加的选上，然后开始部署即可。
