### ISSUE TITLE
[BUG] 

### ISSUE THREAD

**Issue by 94CMO** [YerongAI/Office-Tool#725]
**Office Tool Plus Version, e.g. 8.1.0.0:**
V10.1.10.1

**Operating System, e.g. Windows 10 20H2 or Windows 7 SP1:**
Windows 11 22H2

**Error description (required):**
在部署过程中，安装进度卡死几个小时，故重启应用，但此时的状态为产品已安装，但无法重新部署，用office移除工具移除office后，再重新部署，同样无法重新部署，power  shell检查后，发现安装的office确实已经全部删除，不知道怎么重新部署安装

*Reproduction steps (suggested):*

*Screenshot (suggested):*
![企业微信截图_16915450534997](https://github.com/YerongAI/Office-Tool/assets/107663397/b41cccea-38cc-464f-82db-0bd0f9f83145)

*Additional information (optional):*

**Comment by YerongAI** [comment]
答案就在截图里
