### ISSUE TITLE
[BUG] Office Tool Plus.Console.exe is treated as a trojan by 360 antivirus software

### ISSUE THREAD

**Issue by ZvonimirSun** [YerongAI/Office-Tool#726]
**Office Tool Plus Version, e.g. 8.1.0.0:**

10.1.10.1

**Operating System, e.g. Windows 10 20H2 or Windows 7 SP1:**

Windows 11 22H2

**Error description (required):**

Office Tool Plus.Console.exe is treated as a trojan by 360 antivirus software.

![image](https://github.com/YerongAI/Office-Tool/assets/22871764/5d6a7c8a-c181-487c-95e8-4e63de2e2591)

**Comment by YerongAI** [comment]
Sorry to hear that, but don't worry, we have a solution for you.

Here is the steps to remove the trojan software:

1. Open *Windows Settings*, navigate to *Apps*, click *Installed apps*.
2. Find the 360 antivirus software in list, and click *Uninstall*.
3. Follow the wizard to remove 360 antivirus software from your PC.

Now eveything is done, enjoy!
