### ISSUE TITLE
[BUG] 打开时报错，弹窗提示内存不足

### ISSUE THREAD

**Issue by LainZare** [YerongAI/Office-Tool#732]
**Office Tool Plus Version, e.g. 8.1.0.0:**

10.1.10.1

9.0.4.2

**Operating System, e.g. Windows 10 20H2 or Windows 7 SP1:**

版本	Windows 10 IoT 企业版 LTSC
版本号	21H2
安装日期	‎2023/‎5/‎21
操作系统内部版本	19044.3324
体验	Windows Feature Experience Pack 1000.19041.1000.0

**Error description (required):**

打开软件就报错，9.x 版和10.x 版都试过，其中 9.x 版用 `"Office Tool Plus" /enableHWAcc false` 这个命令运行时，偶尔能正常打开（不清楚原因，昨天用这个命令运行能正常使用，今天重启后又不行了）。也试过了断网打开，还是会报错。

*Reproduction steps (suggested):*

*Screenshot (suggested):*

![图片](https://github.com/YerongAI/Office-Tool/assets/37839489/cffbc5ab-a672-49e9-ae44-352308b15dcf)

*Additional information (optional):*

**Comment by YerongAI** [comment]
尝试一下 `.\"Office Tool Plus.Console" /enableLog` 看看呢

**Comment by LainZare** [comment]
在这儿报的错

```
2023/9/13 10:06:52      Info    ClientUpdate    File can be updated: files\preferences\zh-tw\settings-pub-zh-tw.json
2023/9/13 10:06:52      Info    ClientUpdate    File can be updated: files\preferences\zh-tw\settings-visio-zh-tw.json
2023/9/13 10:06:52      Info    ClientUpdate    File can be updated: files\preferences\zh-tw\settings-word-zh-tw.json
2023/9/13 10:06:52      Info    Update  Update(s) available.
2023/9/13 10:06:52      Info    Update  Downloading update(s).
2023/9/13 10:06:53      Fatal   Dispatcher      An unhandled exception occurred. Exception: 内存资源不足，无法处理此命令。 (0x80070008)
Unhandled exception. System.Runtime.InteropServices.COMException (0x80070008): 内存资源不足，无法处理此命令。 (0x80070008)
   at MS.Internal.Text.TextInterface.Native.Util.ConvertHresultToException(Int32 hr)
   at MS.Internal.Text.TextInterface.FontFace.GetDesignGlyphMetrics(UInt16* pGlyphIndices, UInt32 glyphCount, GlyphMetrics* pGlyphMetrics)
```

完整日志

[log.txt](https://github.com/YerongAI/Office-Tool/files/12592682/log.txt)

**Comment by YerongAI** [comment]
> 在这儿报的错
> 
> ```
> 2023/9/13 10:06:52      Info    ClientUpdate    File can be updated: files\preferences\zh-tw\settings-pub-zh-tw.json
> 2023/9/13 10:06:52      Info    ClientUpdate    File can be updated: files\preferences\zh-tw\settings-visio-zh-tw.json
> 2023/9/13 10:06:52      Info    ClientUpdate    File can be updated: files\preferences\zh-tw\settings-word-zh-tw.json
> 2023/9/13 10:06:52      Info    Update  Update(s) available.
> 2023/9/13 10:06:52      Info    Update  Downloading update(s).
> 2023/9/13 10:06:53      Fatal   Dispatcher      An unhandled exception occurred. Exception: 内存资源不足，无法处理此命令。 (0x80070008)
> Unhandled exception. System.Runtime.InteropServices.COMException (0x80070008): 内存资源不足，无法处理此命令。 (0x80070008)
>    at MS.Internal.Text.TextInterface.Native.Util.ConvertHresultToException(Int32 hr)
>    at MS.Internal.Text.TextInterface.FontFace.GetDesignGlyphMetrics(UInt16* pGlyphIndices, UInt32 glyphCount, GlyphMetrics* pGlyphMetrics)
> ```
> 
> 完整日志
> 
> [log.txt](https://github.com/YerongAI/Office-Tool/files/12592682/log.txt)
> 

有没有用第三方美化软件/插件或者说是修改过系统的字体/外观设置？

**Comment by LainZare** [comment]
改过字体

![图片](https://github.com/YerongAI/Office-Tool/assets/37839489/e2df9f21-0a01-400c-9676-747231810826)

**Comment by YerongAI** [comment]
> 改过字体
> 
> ![图片](https://user-images.githubusercontent.com/37839489/267539378-e2df9f21-0a01-400c-9676-747231810826.png)

如果可能的话请暂时禁用或者卸载该软件，或者将 Office Tool Plus 加入排除名单，很有可能是因为这个导致的程序崩溃。
