### ISSUE TITLE
[BUG] Endless Update Cycle

### ISSUE THREAD

**Issue by lelik107** [YerongAI/Office-Tool#736]
**Office Tool Plus Version, e.g. 8.1.0.0:**
> 10.1.10.1 (09.09.2023 Distribution)

**Operating System, e.g. Windows 10 20H2 or Windows 7 SP1:**
> Windows 10 22H2

**Error description (required):**
> Endless Update Cycle.
The utility tries to update itself. It downloads 120 files for \files\preferences\
but they are either wrong or corrupt. They match the structure but don't match sizes.

*Reproduction steps (suggested):*
Just update.

*Screenshot (suggested):*
![2023-09-26 073259](https://github.com/YerongAI/Office-Tool/assets/128335446/da9488ea-901b-4a6b-adf4-ca5a05314b0d)
It say It can't update please download the latest version manually.

*Additional information (optional):*
From the log.
26.09.2023 7:30:41	Info	Update	Update(s) available.
26.09.2023 7:30:41	Info	Update	Downloading update(s).
26.09.2023 7:31:12	Error	Update	Errors occurred while checking updates. Exception: One or more errors occurred. (Hash value check failure, file: files\preferences\es-es\settings-office-es.json, hash: 91d7cab9be753780d5008158d10c5a5eedb5001ff50e9f3e76e0b0c708097f07). Inner exception: Hash value check failure, file: files\preferences\es-es\settings-office-es.json, hash: 91d7cab9be753780d5008158d10c5a5eedb5001ff50e9f3e76e0b0c708097f07
26.09.2023 7:31:25	Info	Update	Checking updates.
26.09.2023 7:31:25	Warning	ClientUpdate	Can not connect to server. Exception: Response status code does not indicate success: 502 (Bad Gateway).
26.09.2023 7:31:31	Info	Update	Update(s) available.
26.09.2023 7:31:31	Info	Update	Downloading update(s).
26.09.2023 7:31:53	Error	Update	Errors occurred while checking updates. Exception: One or more errors occurred. (End of Central Directory record could not be found.).

Maybe you update the distribution with the latest configuration files available so won't be any problems.

**Comment by YerongAI** [comment]
Hi, thanks for your information, it should be normal now, please restart your Office Tool Plus to check it again.

**Comment by lelik107** [comment]
Yep! It's fixed :)

**Comment by lelik107** [comment]
Yep! It's fixed :)
