### ISSUE TITLE
[IDEA] Version from the chosen update channel.

### ISSUE THREAD

**Issue by lelik107** [YerongAI/Office-Tool#737]
**Feature description:**
> I'd like to ask for a field that shows version available for the chosen update channel.
It might automatically request the version (text field with the auto update)
or a clickable text field that requests it manually.
I think it will be nice to have this information there.
**How it work?**
![2023-09-26 075812](https://github.com/YerongAI/Office-Tool/assets/128335446/8d3813ad-9f50-4bd9-817d-dbda7c4ae272

P.S. And Thank You a Lot for this nice and useful utility.

**Comment by YerongAI** [comment]
New release was out, check it and tell us if your request is solved.

**Comment by lelik107** [comment]
I might miss something...

**Comment by YerongAI** [comment]
Here you can see them.

![image](https://github.com/YerongAI/Office-Tool/assets/44803668/f9829fc7-fbb2-4434-9218-88f9992425bf)

**Comment by lelik107** [comment]
Now we even can choose the different versions from the same channel! I know ODT can deploy that way.
This is very useful option. Thank you a lot. I'm closing the issue.
