### ISSUE TITLE
[BUG] 使用noMeiryoUI修改系统字体后，otp无法启动

### ISSUE THREAD

**Issue by 7890qwaszx** [YerongAI/Office-Tool#744]
**Office Tool Plus Version, e.g. 8.1.0.0:**
> 10.3.1.2

**Operating System, e.g. Windows 10 20H2 or Windows 7 SP1:**
> Win10 10.0.19044.1826

**Error description (required):**
> 使用noMeiryoUI修改系统字体后，otp无法启动。

*Reproduction steps (suggested):*
1. 使用noMeiryoUI 3.2.1.1将系统全局字体修改为“更纱黑体 UI SC   9pt”
2. 再次打开otp出现问题
3. 将系统字体恢复默认（Microsoft YaHei UI   9pt）后，打开otp正常

*Screenshot (suggested):*
![图片](https://github.com/YerongAI/Office-Tool/assets/32451252/deaee1c6-7ded-40c9-903e-b6bba8aceed6)

*Additional information (optional):*

**Comment by YerongAI** [comment]
尝试通过 Office Tool Plus.Console 启动程序，看看具体报的什么错。

命令：

`.\"Office Tool Plus.Console" /enablelog`

**Comment by 7890qwaszx** [comment]
https://pastebin.ubuntu.com/p/H79KcsCjKM/
内容有点长，但重复内容居多

**Comment by 7890qwaszx** [comment]
输出内容：https://pastebin.ubuntu.com/p/n237GnMSdM/

内容较长，但重复的异常居多

---

此外，根据进一步的测试，此问题由更纱黑体造成：

使用不同版本的noMeiryoUI更换了思源宋体、思源黑体、等线、霞鹜文凯等字体，只有更纱黑体出现这种情况。

另外，```System.Runtime.InteropServices.COMException```疑似系统COM组件的问题。

**Comment by YerongAI** [comment]
> 输出内容：https://pastebin.ubuntu.com/p/n237GnMSdM/
> 
> 内容较长，但重复的异常居多
> 
> ---
> 
> 此外，根据进一步的测试，此问题由更纱黑体造成：
> 
> 使用不同版本的noMeiryoUI更换了思源宋体、思源黑体、等线、霞鹜文凯等字体，只有更纱黑体出现这种情况。
> 
> 另外，```System.Runtime.InteropServices.COMException```疑似系统COM组件的问题。

如果是尝试使用 64 位的 Office Tool Plus 呢？64 位的可以从 [Release](https://github.com/YerongAI/Office-Tool/releases) 里面找到文件包。

**Comment by YerongAI** [comment]
> 64位运行正常

那基本上就是因为 32 位版本引起的内存问题了。

可以再麻烦看一下 64 位在运行的时候内存占用有多少吗？任务管理器可看。

**Comment by 7890qwaszx** [comment]
x64未更改系统字体：
![图片](https://github.com/YerongAI/Office-Tool/assets/32451252/674bab68-7dc1-4bfe-a4cf-852cd7354b52)
x86未更改系统字体：
![图片](https://github.com/YerongAI/Office-Tool/assets/32451252/276cd903-86b3-41b7-9d62-012168fa15c2)
x64更改为更纱黑体：
![图片](https://github.com/YerongAI/Office-Tool/assets/32451252/82208cbb-d909-468c-9488-00e0084e905f)
x86更改为更纱黑体：
约60M

**Comment by YerongAI** [comment]
那看来是更纱黑体导致程序渲染那边出了问题，并不是程序本身的问题。

目前来讲只有两个建议：

- 使用 64 位版本的 Office Tool Plus，这样就没什么问题了。与 32 位版本几乎没什么差别。
- 不用 noMeiryoUI 或者不用 更纱黑体。

就这么多吧，自行决定即可。反正我这边是没有能力去修这种问题的。
