### ISSUE TITLE
[BUG] 非默认下载目录创建iso异常

### ISSUE THREAD

**Issue by VictoriousRaptor** [YerongAI/Office-Tool#745]
**Office Tool Plus Version, e.g. 8.1.0.0:**
> 10.3.1.2

**Operating System, e.g. Windows 10 20H2 or Windows 7 SP1:**
> Windows 10.19045

**Error description (required):**
> 选择其它目录作为下载Office文件的目录时，创建的`iso`文件大小异常，具体表现为为文件中的Office目录为空

*Reproduction steps (suggested):*
1. 选择非默认目录作为下载Office文件的目录，我选择了其它磁盘下的一个目录
2. 按照下图配置点击开始部署
3. 发现iso文件大小异常，对比正常创建的，iso文件中Office目录为空

*Screenshot (suggested):*

![Clip_20231104_215136](https://github.com/YerongAI/Office-Tool/assets/10308169/219ae714-ba75-44c2-b851-8caea619af9c)

*Additional information (optional):*

**Comment by YerongAI** [comment]
已应用缓解措施，请等待新版本的发布。
