### ISSUE TITLE
[BUG] win7 无法运行

### ISSUE THREAD

**Issue by yjd** [YerongAI/Office-Tool#746]
**Office Tool Plus Version, e.g. 8.1.0.0:**
> 9.0.4.2

**Operating System, e.g. Windows 10 20H2 or Windows 7 SP1:**
> win7 企业版 sp1
> 官方原版默认只带这四个补丁
> [01]: KB2999226
> [02]: KB3118401
> [03]: KB3140245
> [04]: KB976902

虚拟机win7 企业版 sp1下（官方 sp1 ISO 没有更新补丁）运行不起来。
运行时(windowsdesktop-runtime-6.0.24-win-x86.exe)已经装了并重启也没用。
双击程序没有运行起来

**Comment by YerongAI** [comment]
已不支持 Windows 7，对于 Windows 7 上的问题请自行进行解决。

**Comment by yjd** [comment]
官方网站还是改下，https://otp.landian.vip/zh-cn/download.html 
> 如果您有任何需要，您可以下载 V9 版本继续使用哦~
系统要求：Windows 7 SP1 或更高版本，不支持其他操作系统（例如 Linux 或 macOS）
