### ISSUE TITLE
[BUG] 提示部署工具未正常退出

### ISSUE THREAD

**Issue by SaintChangeTheWorld** [YerongAI/Office-Tool#747]
**Office Tool Plus Version, e.g. 8.1.0.0:**
>10.3.1.2

**Operating System, e.g. Windows 10 20H2 or Windows 7 SP1:**
> Win 11 22H2

**Error description (required):**
> 无论是部署还是卸载，在执行完后总是提示部署工具未正常退出。

*Reproduction steps (suggested):*

*Screenshot (suggested):*

*Additional information (optional):*

**Comment by YerongAI** [comment]
请问有没有更详细的描述可以补充一下？例如所选模块，安装或者卸载的产品或步骤等。

**Comment by SaintChangeTheWorld** [comment]
现在有新版本更新了。对于该条回复内容为：部署模块。
操作步骤是选择产品点击开始部署  部署完成后应该需要退出部署工具。该问题是部署完成后提示部署工具未正常退出 只是出现该提示信息而已。对操作无影响 手动点击x关闭即可。

> 请问有没有更详细的描述可以补充一下？例如所选模块，安装或者卸载的产品或步骤等。

**Comment by SaintChangeTheWorld** [comment]
我看你更新日志里支持office 2024了 但是在部署模块下的添加产品列表中搜2024无结果。翻看列表也没找到

**Comment by YerongAI** [comment]
> 我看你更新日志里支持office 2024了 但是在部署模块下的添加产品列表中搜2024无结果。翻看列表也没找到

需要在设置里面启用“显示内部通道和产品”

**Comment by SaintChangeTheWorld** [comment]
嗯。执行过了。
现在有如下场景：
我在web端的365后台下载了安装包。主要是用的订阅的账号下载。然后一路安装升级 开启beta，Excel的Python我都体验了，每次更新正常。但是呢，visio是我常用的工具，365中不包含。再就是project。这两个我在tool工具上选的都是2024版的 是不是这两款软件安装特别慢？我人为强制结束了。
然后清空office，在tool工具上重新安装365，visio，project。安装好后365（Excel）更新失败了。
________________________________
发件人: Yerong ***@***.***>
发送时间: 2023年11月9日 11:22
收件人: YerongAI/Office-Tool ***@***.***>
抄送: SaintChangeTheWorld ***@***.***>; Author ***@***.***>
主题: Re: [YerongAI/Office-Tool] [BUG] 提示部署工具未正常退出 (Issue #747)


我看你更新日志里支持office 2024了 但是在部署模块下的添加产品列表中搜2024无结果。翻看列表也没找到

需要在设置里面启用“显示内部通道和产品”

―

**Comment by YerongAI** [comment]
> 嗯。执行过了。 现在有如下场景： 我在web端的365后台下载了安装包。主要是用的订阅的账号下载。然后一路安装升级 开启beta，Excel的Python我都体验了，每次更新正常。但是呢，visio是我常用的工具，365中不包含。再就是project。这两个我在tool工具上选的都是2024版的 是不是这两款软件安装特别慢？我人为强制结束了。 然后清空office，在tool工具上重新安装365，visio，project。安装好后365（Excel）更新失败了。

2024 还没有正式发布，在此之前无法使用，请改用其他版本。
