### ISSUE TITLE
OPT下载文件不全

### ISSUE THREAD

**Issue by sx1435078** [YerongAI/Office-Tool#752]
OfficeToolPlus10.4.1.1下载部署Office2021时，在线安装无任何问题。下载安装文件并生成ISO文件用于无网络环境安装时，提示无网络无法下载相关文件，安装失败退出。经与Office-C2R Install下载的文件（无网络环境下可正常安装）对比，发现缺少i642052.cab（安装64位时，32位情况下为i322052.cab）。

**Comment by YerongAI** [comment]
![image](https://github.com/YerongAI/Office-Tool/assets/44803668/11dff0d9-6464-435e-a3fe-36aacfdd8348)

并没有发现问题

**Comment by YerongAI** [comment]
请确保语言添加正确并且没有勾选仅部署校对工具
