### ISSUE TITLE
[BUG] 一键部署完成后没有Excel

### ISSUE THREAD

**Issue by pangyanyuan** [YerongAI/Office-Tool#753]
**Office Tool Plus Version, e.g. 8.1.0.0:**
> Write down here
v10.4.2.4
**Operating System, e.g. Windows 10 20H2 or Windows 7 SP1:**
> Write down here
win10 企业版 ltsc
**Error description (required):**
> Write down here
部署了三遍，365也用，2019也用，都部署不出来Excel
*Reproduction steps (suggested):*

*Screenshot (suggested):*

*Additional information (optional):*

**Comment by pangyanyuan** [comment]
Your early feedback will be appreciated!

**Comment by YerongAI** [comment]
建议完全卸载并移除后再尝试安装：**工具箱 - 移除 Office**
