### ISSUE TITLE
[BUG] 无法在 Office Tool Plus 文件夹中找到 Office 安装文件。请先下载 Office 安装文件，或者移动 Office 安装文件到工作目录中。

### ISSUE THREAD

**Issue by VictoriousRaptor** [YerongAI/Office-Tool#755]
**Office Tool Plus Version, e.g. 8.1.0.0:**
> 10.4.2.4

**Operating System, e.g. Windows 10 20H2 or Windows 7 SP1:**
> Windows 10 22H2 19045.3636

**Error description (required):**

无法在 Office Tool Plus 文件夹中找到 Office 安装文件。请先下载 Office 安装文件，或者移动 Office 安装文件到工作目录中。

*Reproduction steps (suggested):*

1. 选择visio pro 2021 LTSC， 开启“询问保存位置”，选择下载后安装，创建ISO
2. 点击开始部署

*Screenshot (suggested):*

*Additional information (optional):*

**Comment by YerongAI** [comment]
不能改变默认的存储位置。

**Comment by YerongAI** [comment]
将会应用缓解措施
