### ISSUE TITLE
[IDEA] 生成ISO时适配目标架构

### ISSUE THREAD

**Issue by SituChengxiang** [YerongAI/Office-Tool#768]
**生成ISO功能的一个小改进**
> ARM64 版本指定架构体系为 x64 时，往 ISO 复制的 Office Tool Plus 应为 x64 架构的。如果复制的 ARM64 的 Office Tool Plus，会导致使用的该 ISO 的 x64 设备无法正常启动正常部署过程。

**How it work?**
> 在发行版中同时塞上 x64 和 arm64 的 office tool plus client？(*^_^*) 然后主目录用 x86 的？再根据系统架构启动对应版本？

Technical Reference (if possible):
> 慢慢来😂

**Comment by YerongAI** [comment]
因为不同版本的 Office Tool 没有做互通，因此暂时不考虑此类问题。请在创建 Office ISO 时使用对应版本操作，或者使用第三方工具进行打包。
