### ISSUE TITLE
[BUG] 反馈一个关于激活状态的bug

### ISSUE THREAD

**Issue by matocool** [YerongAI/Office-Tool#770]
如图所示，通过tool卸载激活，然后使用HEU KMS激活后，刷新激活状态，显示未激活，但是实际上打开office检查是激活状态，

![image](https://github.com/YerongAI/Office-Tool/assets/83129369/fd9416ec-40f1-4203-b5bd-abebddc7a025)

**Comment by YerongAI** [comment]
两个问题：

1. Ohook 激活原理是对 Office 进行破解，不是对系统进行破解。因此除了 Office 之外，任何程序查看的激活状态都可能会与 Office 不一致。既然你使用了 HEU 进行激活，那就用 HEU 查看激活状态。Office Tool Plus 不会对 Ohook 进行判断，未来也不会做相关工作。
2. Win 7 已停止支持，不再回答相关问题。
