### ISSUE TITLE
[BUG] 

### ISSUE THREAD

**Issue by nuitar** [YerongAI/Office-Tool#774]
**Office Tool Plus Version, e.g. 8.1.0.0:**
> Office_Tool_with_runtime_v10.4.5.0_arm64

**Operating System, e.g. Windows 10 20H2 or Windows 7 SP1:**
> Windows 10 专业版 22H2

**Error description (required):**
> 点击安装密钥和激活按钮均报错 但是已安装.Net framework
Could not find an installation of .NET Framework v4.0.30319. System.Management requires native modules from the .NET Framework to operate.
卸载密钥没有问题
<img src="https://github.com/YerongAI/Office-Tool/assets/108944715/dcde745f-20f4-498d-9707-7f73cdea30ad" width=500>
注册表应该没问题
.net 4.0 32位已安装

*Screenshot (suggested):*
<img src="https://github.com/YerongAI/Office-Tool/assets/108944715/ab25e45f-3cbf-4d99-bdfa-d69ce7462d50" width=500>
<img src="https://github.com/YerongAI/Office-Tool/assets/108944715/c3850b21-86a0-4e46-93c8-ca6811e1bb19" width=500>

*Additional information (optional):*
Window arm64架构

**Comment by YerongAI** [comment]
我没有 Arm 设备还真不好测，别的 Arm 用户倒是反馈正常

**Comment by YerongAI** [comment]
不过我在你的截图里面看到了 Windows on Arm 设备的默认环境变量，Office Tool Plus 以后修复系统环境变量会考虑 Arm 的路径了，~~这也是这个 issue 目前来讲最有用的信息（~~

**Comment by nuitar** [comment]
可能设备比较特殊，使用的是小米平板5的Windows，不过已通过命令行kms激活，感谢回复

**Comment by LanYunDev** [comment]
Windows 10 arm
Office_Tool_with_runtime_v10.21.35.0_arm64.zip
依然出现这个问题

**Comment by YerongAI** [comment]
> Windows 10 arm Office_Tool_with_runtime_v10.21.35.0_arm64.zip 依然出现这个问题

如果可以，还烦请加群提供远程访问权限，我没有 Arm 设备无法进行实地测试或者调试。

**Comment by LanYunDev** [comment]
> 如果可以，还烦请加群提供远程访问权限，我没有 Arm 设备无法进行实地测试或者调试。

好的
