### ISSUE TITLE
[BUG] 提示部署工具未正常退出. 部署因此无法继续

### ISSUE THREAD

**Issue by FguoDaf** [YerongAI/Office-Tool#779]
**Office Tool Plus Version, e.g. 8.1.0.0:**
> 10.4.5.0

**Operating System, e.g. Windows 10 20H2 or Windows 7 SP1:**
> win 10 教育版

**Error description (required):**
> 一键部署指令安装时, 部署界面提示"部署工具未正常退出" 然后就不会继续动作, 手动点击部署, 依然会这样提示 且无法重新部署

*Reproduction steps (suggested):*

*Screenshot (suggested):*

*Additional information (optional):*
尝试删除tool plus 重新解压  执行部署, 依然失败

**Comment by FguoDaf** [comment]
后续操作, 误打误撞修改了安装模块为"office tool plus"后 手动点击部署, 能成功开始下载
![image](https://github.com/YerongAI/Office-Tool/assets/92022245/500542f8-0233-4328-810e-8448ff0fc8aa)

**Comment by YerongAI** [comment]
既然能部署了问题就不大，Office 部署工具也不在我们的可控范围内，这种问题一般没有解决方案。
