### ISSUE TITLE
[Request] UI Library

### ISSUE THREAD

**Issue by MIAIONE** [YerongAI/Office-Tool#780]
otp 这个UI设计挺好看的, 而且也能够本机编译, 能否独立出来一个UI的仓库呢? 另外你们是怎么做到 aot程序没有manage字段的? 怎么利用hostfxr 精简runtime的? 没有独立UI的计划也大概说下吧! QwQ, 说实话太想要这个UI了

**Comment by YerongAI** [comment]
UI 仓库大概是不会有的，虽然在项目中是一个独立的 library，但我还没想过独立出来一个仓库。AOT 这个可能是由 .NET Reactor 完成的，具体的我也不是很清楚。hostfxr.dll 的工作原理是之前用 Process Monitor 监视自己程序的时候偶然发现的，然后就根据自己的想法把现在这个结构摸索出来了。
