### ISSUE TITLE
[BUG] 

### ISSUE THREAD

**Issue by xing75** [YerongAI/Office-Tool#781]
**Office Tool Plus Version, e.g. 8.1.0.0:**
> 10.4.5.0

**Operating System, e.g. Windows 10 20H2 or Windows 7 SP1:**
> Windows 10 21H1

**Error description (required):**
> 激活设置KMS主机地址  （无论设置任何地址）输入地址后点  设置主机  都会提示   无法保存 KMS 设置，请检查 KMS 主机名称是否正确，然后重试

*Reproduction steps (suggested):*
![微信图片_20240106135420](https://github.com/YerongAI/Office-Tool/assets/52085681/4e75369b-83da-4e1f-9adb-20660fe6fef6)

*Screenshot (suggested):*

*Additional information (optional):*

**Comment by YerongAI** [comment]
你好，在出现这个问题之后，请按下 <kbd>Ctrl + Shift + P</kbd> 快捷键打开命令框，输入 `/getlogs` 命令，以获取具体的错误信息。

**Comment by xing75** [comment]
TimeTypeActionMessage

2024/1/6 12:38:20InfoInitRegistering events.

2024/1/6 12:38:20InfoInitLoading application settings.

2024/1/6 12:38:20InfoInitLoaded 3 value(s).

2024/1/6 12:38:20InfoInitUpdating application settings.

2024/1/6 12:38:20InfoChecking envsOS version: Microsoft Windows 10.0.19043 X64.

2024/1/6 12:38:20InfoChecking envsOS language: zh-CN.

2024/1/6 12:38:20InfoChecking envsOS culture: zh-CN.

2024/1/6 12:38:20InfoChecking envsOS region: CN.

2024/1/6 12:38:20InfoChecking envsOS is 64-bit: True.

2024/1/6 12:38:20InfoChecking envsWorking directory is I:\装机1解包软件鸡火\HEU_KMS_Activator_v40.0.0\Office Tool

2024/1/6 12:38:20InfoChecking envsScreen resolution: 1920 x 1080.

2024/1/6 12:38:20InfoChecking envsPrimary resolution: 1920 x 1080.

2024/1/6 12:38:20InfoChecking envsVirtual resolution: 1920 x 1080.

2024/1/6 12:38:20InfoChecking envsCurrent window size: 1440 x 759.

2024/1/6 12:38:20InfoChecking envsCurrent process ID: 31320.

2024/1/6 12:38:20InfoChecking envsCurrent process architecture: X86.

2024/1/6 12:38:20InfoChecking envsCurrent process is 64-bit: False.

2024/1/6 12:38:20InfoInitBinding commands.

2024/1/6 12:38:20InfoInitCommands binding done.

2024/1/6 12:38:20InfoInitTemp path is set to C:\Users\Administrator\AppData\Local\Temp\OTP_4009

2024/1/6 12:38:20InfoInitRegistering taskbar item.

2024/1/6 12:38:20InfoInitPermission is administrator.

2024/1/6 12:38:20InfoUpdateChecking updates.

2024/1/6 12:38:22InfoClientUpdateApplication version is higher than required version, skip update.

2024/1/6 12:38:27InfoUpdateApplication is up to date.

2024/1/6 12:38:35InfoDeployLoading Office information.

2024/1/6 12:38:35InfoDeployOffice is installed on C:\Program Files (x86)\Microsoft Office

2024/1/6 12:38:35InfoDeployOffice version: 16.0.17304.20000

2024/1/6 12:38:35InfoDeployOffice architecture: x86.

2024/1/6 12:38:35InfoDeployOffice branch: Dogfood::DevMain.

2024/1/6 12:38:35InfoDeploySuccessfully obtaining Office version information.

2024/1/6 12:39:07ErrorSetKMSHostCan not apply settings. Exception: 

2024/1/6 12:39:34ErrorSetKMSHostCan not apply settings. Exception: 

2024/1/6 12:39:49ErrorQueryLicensesCan not get licenses status. Exception: 

2024/1/6 12:41:29ErrorSetKMSHostCan not apply settings. Exception: 

2024/1/6 12:41:34ErrorSetKMSHostCan not apply settings. Exception: 

2024/1/6 12:43:11ErrorSetKMSHostCan not apply settings. Exception: 

2024/1/6 12:43:16ErrorSetKMSHostCan not apply settings. Exception: 

2024/1/6 12:50:02ErrorSetKMSHostCan not apply settings. Exception: Input string was not in a correct format.

2024/1/6 12:50:17ErrorSetKMSHostCan not apply settings. Exception: 

2024/1/6 12:50:27ErrorSetKMSHostCan not apply settings. Exception: 

2024/1/6 12:50:43InfoUpdateTriggered by user, checking updates.

2024/1/6 12:50:45InfoClientUpdateApplication version is higher than required version, skip update.

2024/1/6 12:50:47InfoUpdateApplication is up to date.

2024/1/6 12:54:31ErrorSetKMSHostCan not apply settings. Exception: 

2024/1/6 12:55:28ErrorSetKMSHostCan not apply settings. Exception: 

2024/1/6 12:57:43ErrorSetKMSHostCan not apply settings. Exception: 

2024/1/6 13:07:18ErrorSetKMSHostCan not apply settings. Exception: 

2024/1/6 13:07:22ErrorSetKMSHostCan not apply settings. Exception: 

2024/1/6 13:42:55ErrorSetKMSHostCan not apply settings. Exception: 

2024/1/6 13:42:57ErrorSetKMSHostCan not apply settings. Exception: 

2024/1/6 13:44:14ErrorSetKMSHostCan not apply settings. Exception: 

2024/1/6 13:51:29ErrorSetKMSHostCan not apply settings. Exception: 

2024/1/6 13:51:45ErrorSetKMSHostCan not apply settings. Exception: 

2024/1/6 13:52:30ErrorSetKMSHostCan not apply settings. Exception: 

2024/1/6 13:53:06ErrorSetKMSHostCan not apply settings. Exception: 

2024/1/6 14:17:09ErrorSetKMSHostCan not apply settings. Exception: 

2024/1/6 14:17:16ErrorQueryLicensesCan not get licenses status. Exception: 
















--

石礼奇




在 2024-01-06 14:14:39，"Yerong" ***@***.***> 写道：

你好，在出现这个问题之后，请按下 Ctrl + Shift + P 快捷键打开命令框，输入 /getlogs 命令，以获取具体的错误信息。

**Comment by YerongAI** [comment]
大意了，忘了捕捉错误代码。先尝试一下去工具箱页面修复 WMI 组件看看吧。

**Comment by xing75** [comment]
修复完后  还是一样的错误













--

石礼奇




在 2024-01-06 14:26:00，"Yerong" ***@***.***> 写道：

大意了，忘了捕捉错误代码。先尝试一下去工具箱页面修复 WMI 组件看看吧。

**Comment by YerongAI** [comment]
您好，[GitHub release](https://github.com/YerongAI/Office-Tool/releases/tag/v10.6.1.0) 里已发布新版本。请您使用此新版本，按照之前的步骤操作，继续查看日志。本次应该能够正常记录错误代码。

**Comment by YerongAI** [comment]
由于此 issue 长时间未回应，将进行关闭操作。如若问题依旧，请重新打开此 issue
