### ISSUE TITLE
[BUG] 錯誤代碼: 0x80131501

### ISSUE THREAD

**Issue by Sasha820828** [YerongAI/Office-Tool#787]
**Office Tool Plus Version, e.g. 8.1.0.0:**
> V10.4.5.0

**Operating System, e.g. Windows 10 20H2 or Windows 7 SP1:**
> Write down here

**Error description (required):**
> 啟用時安裝一直出現錯誤代碼: 0x80131501

*Reproduction steps (suggested):*

*Screenshot (suggested):*

*Additional information (optional):*

**Comment by YerongAI** [comment]
您好，此错误代码没有实际意义，请提供错误代码底下给出的错误信息。

**Comment by YerongAI** [comment]
由於此 issue 無人回應，現在將關閉此 issue。如果有新的問題可提交新的 issue
