### ISSUE TITLE
update[BUG] 

### ISSUE THREAD

**Issue by yycyyx** [YerongAI/Office-Tool#788]
**Office Tool Plus Version, e.g. 8.1.0.0:**
> The 72nd file keeps showing updates being downloaded

**Operating System, e.g. Windows 10 20H2 or Windows 7 SP1:**
>  Windows11

**Error description (required):**
>No error message, two hours after the update is still displayed in the update

*Reproduction steps (suggested):*

*Screenshot (suggested):*
<img width="297" alt="image" src="https://github.com/YerongAI/Office-Tool/assets/107899011/2bd4d372-c8dc-4f7e-befb-ad5b78081e78">

*Additional information (optional):*

**Comment by YerongAI** [comment]
如果用的是中国移动宽带，那这个问题我也无解。由于 Office Tool Plus 的服务器是入门级别的，因此没法提供全面的服务。可以忽略这个更新，或者在[这里下载](https://onedrive.officetool.plus/?/Office_Tool/Office%20Tool%20Plus/10.6.2.0_v2/)最新打包的程序。

**Comment by YerongAI** [comment]
Fixed, the new version will be released this month.
