### ISSUE TITLE
[BUG] 更新时进度条一直显示0.00%，卡在最后一个更新文件不动

### ISSUE THREAD

**Issue by ZWCLD** [YerongAI/Office-Tool#789]
**Office Tool Plus Version, e.g. 8.1.0.0:**
> Write down here
10.6.2.0
**Operating System, e.g. Windows 10 20H2 or Windows 7 SP1:**
> Write down here
Windows 11 23H2
**Error description (required):**
> Write down here
更新时进度条一直显示0.00%，卡在最后一个更新文件不动
*Reproduction steps (suggested):*
None
*Screenshot (suggested):*
<img width="960" alt="298297933-84542ed4-a622-4d15-a777-2e0cfb53ecfa" src="https://github.com/YerongAI/Office-Tool/assets/97391687/72e839f4-afbf-42c2-92ab-91580f9264ec">
*Additional information (optional):*
None

**Comment by YerongAI** [comment]
请问重启程序后是否依然会这样？如果是的话，还烦请提供一下日志：

按下 <kbd>Ctrl</kbd> + <kbd>Shift</kbd> + <kbd>P</kbd>，打开程序命令框，输入 `/getlogs` 以获取日志。

**Comment by buzhuiwen** [comment]
> 请问重启程序后是否依然会这样？如果是的话，还烦请提供一下日志：
> 
> 按下 Ctrl + Shift + P，打开程序命令框，输入 `/getlogs` 以获取日志。

Time	Type	Action	Message
2024/1/23 20:29:02	Info	Init	Registering events.
2024/1/23 20:29:02	Info	Init	Loading application settings.
2024/1/23 20:29:02	Info	Init	Loaded 3 value(s).
2024/1/23 20:29:02	Info	Init	Updating application settings.
2024/1/23 20:29:02	Info	Checking envs	OS version: Microsoft Windows 10.0.22631 X64.
2024/1/23 20:29:02	Info	Checking envs	OS language: zh-CN.
2024/1/23 20:29:02	Info	Checking envs	OS culture: zh-CN.
2024/1/23 20:29:02	Info	Checking envs	OS region: CN.
2024/1/23 20:29:02	Info	Checking envs	OS is 64-bit: True.
2024/1/23 20:29:02	Info	Checking envs	Working directory is D:\Program Files\Office Tool
2024/1/23 20:29:02	Info	Checking envs	Screen resolution: 3840 x 2160.
2024/1/23 20:29:02	Info	Checking envs	Primary resolution: 1920 x 1080.
2024/1/23 20:29:02	Info	Checking envs	Virtual resolution: 1920 x 1080.
2024/1/23 20:29:02	Info	Checking envs	Current window size: 1440 x 755.5.
2024/1/23 20:29:02	Info	Checking envs	Current process ID: 15644.
2024/1/23 20:29:02	Info	Checking envs	Current process architecture: X64.
2024/1/23 20:29:02	Info	Checking envs	Current process is 64-bit: True.
2024/1/23 20:29:02	Info	Init	Binding commands.
2024/1/23 20:29:02	Info	Init	Commands binding done.
2024/1/23 20:29:02	Info	Init	Temp path is set to C:\Users\buzhu\AppData\Local\Temp\OTP_7068
2024/1/23 20:29:02	Info	Init	Registering taskbar item.
2024/1/23 20:29:02	Info	Init	Permission is administrator.
2024/1/23 20:29:02	Info	Update	Checking updates.
2024/1/23 20:29:10	Info	ClientUpdate	Application version is higher than required version, skip update.
2024/1/23 20:29:10	Info	ClientUpdate	Process architecture doesn't match the requirement, skip update.
2024/1/23 20:29:20	Info	ClientUpdate	File can be updated: files\preferences\de-de\settings-excel-de.json
2024/1/23 20:29:20	Info	ClientUpdate	File can be updated: files\preferences\de-de\settings-office-de.json
2024/1/23 20:29:20	Info	ClientUpdate	File can be updated: files\preferences\de-de\settings-onent-de.json
2024/1/23 20:29:20	Info	ClientUpdate	File can be updated: files\preferences\de-de\settings-outlk-de.json
2024/1/23 20:29:20	Info	ClientUpdate	File can be updated: files\preferences\de-de\settings-ppt-de.json
2024/1/23 20:29:20	Info	ClientUpdate	File can be updated: files\preferences\de-de\settings-word-de.json
2024/1/23 20:29:20	Info	ClientUpdate	File can be updated: files\preferences\en-us\settings-excel-en.json
2024/1/23 20:29:20	Info	ClientUpdate	File can be updated: files\preferences\en-us\settings-office-en.json
2024/1/23 20:29:20	Info	ClientUpdate	File can be updated: files\preferences\en-us\settings-onent-en.json
2024/1/23 20:29:20	Info	ClientUpdate	File can be updated: files\preferences\en-us\settings-outlk-en.json
2024/1/23 20:29:20	Info	ClientUpdate	File can be updated: files\preferences\en-us\settings-ppt-en.json
2024/1/23 20:29:20	Info	ClientUpdate	File can be updated: files\preferences\en-us\settings-word-en.json
2024/1/23 20:29:20	Info	ClientUpdate	File can be updated: files\preferences\es-es\settings-excel-es.json
2024/1/23 20:29:20	Info	ClientUpdate	File can be updated: files\preferences\es-es\settings-office-es.json
2024/1/23 20:29:20	Info	ClientUpdate	File can be updated: files\preferences\es-es\settings-onent-es.json
2024/1/23 20:29:20	Info	ClientUpdate	File can be updated: files\preferences\es-es\settings-outlk-es.json
2024/1/23 20:29:20	Info	ClientUpdate	File can be updated: files\preferences\es-es\settings-ppt-es.json
2024/1/23 20:29:20	Info	ClientUpdate	File can be updated: files\preferences\es-es\settings-word-es.json
2024/1/23 20:29:20	Info	ClientUpdate	File can be updated: files\preferences\fr-fr\settings-excel-fr.json
2024/1/23 20:29:20	Info	ClientUpdate	File can be updated: files\preferences\fr-fr\settings-office-fr.json
2024/1/23 20:29:20	Info	ClientUpdate	File can be updated: files\preferences\fr-fr\settings-onent-fr.json
2024/1/23 20:29:20	Info	ClientUpdate	File can be updated: files\preferences\fr-fr\settings-outlk-fr.json
2024/1/23 20:29:20	Info	ClientUpdate	File can be updated: files\preferences\fr-fr\settings-ppt-fr.json
2024/1/23 20:29:20	Info	ClientUpdate	File can be updated: files\preferences\fr-fr\settings-word-fr.json
2024/1/23 20:29:20	Info	ClientUpdate	File can be updated: files\preferences\it-it\settings-excel-it.json
2024/1/23 20:29:20	Info	ClientUpdate	File can be updated: files\preferences\it-it\settings-office-it.json
2024/1/23 20:29:20	Info	ClientUpdate	File can be updated: files\preferences\it-it\settings-onent-it.json
2024/1/23 20:29:20	Info	ClientUpdate	File can be updated: files\preferences\it-it\settings-outlk-it.json
2024/1/23 20:29:20	Info	ClientUpdate	File can be updated: files\preferences\it-it\settings-ppt-it.json
2024/1/23 20:29:20	Info	ClientUpdate	File can be updated: files\preferences\it-it\settings-word-it.json
2024/1/23 20:29:20	Info	ClientUpdate	File can be updated: files\preferences\ja-jp\settings-excel-ja.json
2024/1/23 20:29:20	Info	ClientUpdate	File can be updated: files\preferences\ja-jp\settings-office-ja.json
2024/1/23 20:29:20	Info	ClientUpdate	File can be updated: files\preferences\ja-jp\settings-onent-ja.json
2024/1/23 20:29:20	Info	ClientUpdate	File can be updated: files\preferences\ja-jp\settings-outlk-ja.json
2024/1/23 20:29:20	Info	ClientUpdate	File can be updated: files\preferences\ja-jp\settings-ppt-ja.json
2024/1/23 20:29:20	Info	ClientUpdate	File can be updated: files\preferences\ja-jp\settings-word-ja.json
2024/1/23 20:29:20	Info	ClientUpdate	File can be updated: files\preferences\ko-kr\settings-excel-ko.json
2024/1/23 20:29:20	Info	ClientUpdate	File can be updated: files\preferences\ko-kr\settings-office-ko.json
2024/1/23 20:29:20	Info	ClientUpdate	File can be updated: files\preferences\ko-kr\settings-onent-ko.json
2024/1/23 20:29:20	Info	ClientUpdate	File can be updated: files\preferences\ko-kr\settings-outlk-ko.json
2024/1/23 20:29:20	Info	ClientUpdate	File can be updated: files\preferences\ko-kr\settings-ppt-ko.json
2024/1/23 20:29:20	Info	ClientUpdate	File can be updated: files\preferences\ko-kr\settings-word-ko.json
2024/1/23 20:29:20	Info	ClientUpdate	File can be updated: files\preferences\nl-nl\settings-excel-nl.json
2024/1/23 20:29:20	Info	ClientUpdate	File can be updated: files\preferences\nl-nl\settings-office-nl.json
2024/1/23 20:29:20	Info	ClientUpdate	File can be updated: files\preferences\nl-nl\settings-onent-nl.json
2024/1/23 20:29:20	Info	ClientUpdate	File can be updated: files\preferences\nl-nl\settings-outlk-nl.json
2024/1/23 20:29:20	Info	ClientUpdate	File can be updated: files\preferences\nl-nl\settings-ppt-nl.json
2024/1/23 20:29:20	Info	ClientUpdate	File can be updated: files\preferences\nl-nl\settings-word-nl.json
2024/1/23 20:29:20	Info	ClientUpdate	File can be updated: files\preferences\pt-br\settings-excel-pt.json
2024/1/23 20:29:20	Info	ClientUpdate	File can be updated: files\preferences\pt-br\settings-office-pt.json
2024/1/23 20:29:20	Info	ClientUpdate	File can be updated: files\preferences\pt-br\settings-onent-pt.json
2024/1/23 20:29:20	Info	ClientUpdate	File can be updated: files\preferences\pt-br\settings-outlk-pt.json
2024/1/23 20:29:20	Info	ClientUpdate	File can be updated: files\preferences\pt-br\settings-ppt-pt.json
2024/1/23 20:29:20	Info	ClientUpdate	File can be updated: files\preferences\pt-br\settings-word-pt.json
2024/1/23 20:29:20	Info	ClientUpdate	File can be updated: files\preferences\ru-ru\settings-excel-ru.json
2024/1/23 20:29:20	Info	ClientUpdate	File can be updated: files\preferences\ru-ru\settings-office-ru.json
2024/1/23 20:29:20	Info	ClientUpdate	File can be updated: files\preferences\ru-ru\settings-onent-ru.json
2024/1/23 20:29:20	Info	ClientUpdate	File can be updated: files\preferences\ru-ru\settings-outlk-ru.json
2024/1/23 20:29:20	Info	ClientUpdate	File can be updated: files\preferences\ru-ru\settings-ppt-ru.json
2024/1/23 20:29:20	Info	ClientUpdate	File can be updated: files\preferences\ru-ru\settings-word-ru.json
2024/1/23 20:29:20	Info	ClientUpdate	File can be updated: files\preferences\zh-cn\settings-excel-zh-cn.json
2024/1/23 20:29:20	Info	ClientUpdate	File can be updated: files\preferences\zh-cn\settings-office-zh-cn.json
2024/1/23 20:29:20	Info	ClientUpdate	File can be updated: files\preferences\zh-cn\settings-onent-zh-cn.json
2024/1/23 20:29:20	Info	ClientUpdate	File can be updated: files\preferences\zh-cn\settings-outlk-zh-cn.json
2024/1/23 20:29:20	Info	ClientUpdate	File can be updated: files\preferences\zh-cn\settings-ppt-zh-cn.json
2024/1/23 20:29:20	Info	ClientUpdate	File can be updated: files\preferences\zh-cn\settings-word-zh-cn.json
2024/1/23 20:29:20	Info	ClientUpdate	File can be updated: files\preferences\zh-tw\settings-excel-zh-tw.json
2024/1/23 20:29:20	Info	ClientUpdate	File can be updated: files\preferences\zh-tw\settings-office-zh-tw.json
2024/1/23 20:29:20	Info	ClientUpdate	File can be updated: files\preferences\zh-tw\settings-onent-zh-tw.json
2024/1/23 20:29:20	Info	ClientUpdate	File can be updated: files\preferences\zh-tw\settings-outlk-zh-tw.json
2024/1/23 20:29:20	Info	ClientUpdate	File can be updated: files\preferences\zh-tw\settings-ppt-zh-tw.json
2024/1/23 20:29:20	Info	ClientUpdate	File can be updated: files\preferences\zh-tw\settings-word-zh-tw.json
2024/1/23 20:29:20	Info	Update	Update(s) available.
2024/1/23 20:29:20	Info	Update	Downloading update(s).
2024/1/23 20:45:25	Info	Update	Triggered by user, checking updates.
2024/1/23 20:46:51	Info	Update	Triggered by user, checking updates.
2024/1/23 20:46:52	Info	Update	Triggered by user, checking updates.
我也遇到了，重启一次程序还是这样

**Comment by Aracher** [comment]
我也遇到了这个问题 希望得到您的帮助

**Comment by YerongAI** [comment]
已修复，新版本将在这个月的晚些时候发布
