### ISSUE TITLE
[BUG] 为什么一直处于更新状态啊，然后百分之0

### ISSUE THREAD

**Issue by Cloudins** [YerongAI/Office-Tool#791]
**Office Tool Plus Version, e.g. 8.1.0.0:**
> Write down here

**Operating System, e.g. Windows 10 20H2 or Windows 7 SP1:**
> Write down here

**Error description (required):**
> Write down here

*Reproduction steps (suggested):*

*Screenshot (suggested):*

*Additional information (optional):*

**Comment by lc6464** [comment]
好问题，但你看起来什么都没有提供，看看网络吧。

**Comment by Cloudins** [comment]
![image](https://github.com/YerongAI/Office-Tool/assets/98966253/387dc851-99d7-4f8b-82e6-6e730dbb50a4)

**Comment by YerongAI** [comment]
重复 #789
