### ISSUE TITLE
[BUG] Could not load ICU data. UErrorCode: 2

### ISSUE THREAD

**Issue by Unknown78** [YerongAI/Office-Tool#792]
**Office Tool Plus Version,**
> [Office_Tool_with_runtime_v10.6.2.0_x64.7z](https://github.com/YerongAI/Office-Tool/releases/tag/v10.6.2.0)

**Operating System,**
> [WinPE 11-10-8 Sergei Strelec (x86/x64/Native x86) 2023.06.25 English version](https://sergeistrelec.name/winpe-10-8-sergei-strelec-english/233-winpe-11-10-8-sergei-strelec-x86x64native-x86-20230626-english-version.html)
> Loaded with [Easy2Boot v2.20 by Steve Si](https://easy2boot.xyz/download/) with[ .isoHW file extension](https://easy2boot.xyz/create-your-website-with-blocks/e2b-payload-file-extensions/).
> I choose to boot in Windows 10 x64 20H1 10.0.19041.1

**Error description (required):**

If I run `Office Tool Plus.exe`, it will be crashed at launch.

Here is the screenshot from [Process Monitor v3.96 by Sysinternals](https://learn.microsoft.com/en-us/sysinternals/downloads/procmon):
![image](https://github.com/YerongAI/Office-Tool/assets/25132599/df5cc1e2-3e9f-4caf-bf71-ac7ebf084c75)

And if I start with
```
"Office Tool Plus.Console.exe" /start
```
It will output this error:
```
Could not load ICU data. UErrorCode: 2
```

**Comment by YerongAI** [comment]
We don't make any warranties for use in non-standard environments.

**Comment by Unknown78** [comment]
I'm not demanding any warranties.
But a bug is still a bug.

**Comment by YerongAI** [comment]
> I'm not demanding any warranties. But a bug is still a bug.

PE is not a standard environments. We won't do anything about bugs in non-standard environments.

**Comment by Unknown78** [comment]
Okay.
I've just tested it on `Windows 11 x64 Home 23H2 10.0.22631.3007`
If you try to rename, delete, or corrupt the file of `icudtl.dat` within the directory of:
```
C:\Windows\Globalization\ICU
```
Then you will receive the same error.

I've looked up on the internet, it seems because of improper unicode support in case of failure or something like that.

**Comment by YerongAI** [comment]
> Okay. I've just tested it on `Windows 11 x64 Home 23H2 10.0.22631.3007` If you try to rename, delete, or corrupt the file with the full path of:
> 
> ```
> C:\Windows\Globalization\ICU\icudtl.dat
> ```
> 
> Then you will receive the same error.
> 
> The same thing also happened with `C:\Windows\System32\icu.dll`
> 
> I've looked up on the internet, it seems because of improper unicode support in case of failure or something like that. Add a fallback mechanism perhaps?

This is a bug with .NET runtime, you should report it to the .NET team.
