### ISSUE TITLE
[BUG] 文档转换Execl功能程序卡顿后自动退出，无提示

### ISSUE THREAD

**Issue by xinmiti** [YerongAI/Office-Tool#794]
**Office Tool Plus Version,**
> v10.6.2.0

**Operating System**
> Windows 10 22H2

**Error description (required):**
> 文档转换功能中，准备将xls格式的文件转换成xlsx格式，点转换时程序卡顿后自动退出了

*Scre![gif20240219082543](https://github.com/YerongAI/Office-Tool/assets/40022543/e166dde6-feb8-47ae-bd76-52238d19b367)

**Comment by YerongAI** [comment]
经测试，在我的电脑上运行正常。

您可以在 `%temp%\OTP_Logs` 里面找到崩溃后的日志文件，也可以通过管理员身份的 Shell 运行 `.\"Office Tool Plus.Console" /log` 查看程序运行时的日志输出。
