### ISSUE TITLE
[BUG] 激活功能报错

### ISSUE THREAD

**Issue by Mrzqd** [YerongAI/Office-Tool#799]
**Office Tool Plus Version, e.g. 8.1.0.0:**
>  10.8.5.0

**Operating System, e.g. Windows 10 20H2 or Windows 7 SP1:**
> win10专业版 1511

**Error description (required):**
> 激活时报错  The native library 'C:\Windows\Microsoft.NET\Framework64\v4.0.30319\wminet_utils.dll' does not have all required functions. Please, update the .NET Framework.

*Reproduction steps (suggested):*

*Screenshot (suggested):*
![780def05522f34682852eae8f63c457](https://github.com/YerongAI/Office-Tool/assets/104408988/802547a1-4d8e-4960-880e-1326650b548a)

*Additional information (optional):*

**Comment by YerongAI** [comment]
先把系统更新到最新版。
