### ISSUE TITLE
转换功能--想把TXT转WORD--报错

### ISSUE THREAD

**Issue by Linjiaoshou** [YerongAI/Office-Tool#800]
错误
Unable to cast COM object of type'System. ComObject' to interface type'Microsoft.Office.Interop.Word.Application'. Thisoperation failed because the QueryInterface call onthe COM component for the interface with lD100020970-0000-0000-C000-000000000046;faileddue to the following error: 加载类型库/DLL 时出错。(0x80029C4A(TYPE E CANTLOADLIBRARY)).
这个错误报告是转换功能时出现的，我想把TXT转WORD，结果就出现上述报告，希望能帮忙解决，谢谢
![用TXT转WORD的功能时报错](https://github.com/YerongAI/Office-Tool/assets/103524097/f90a5947-4866-4434-9565-8fa661d617f0)

**Comment by YerongAI** [comment]
装最新版的 Office 没？

**Comment by Linjiaoshou** [comment]
我的Office是买电脑的时候就有的，正版的，不知道这个能不能升级，我不敢卸载，一些后面就要用破解的了

**Comment by Linjiaoshou** [comment]
谢谢您能抽空帮我解答！！

**Comment by YerongAI** [comment]
> 我的Office是买电脑的时候就有的，正版的，不知道这个能不能升级，我不敢卸载，一些后面就要用破解的了

看看 Office Tool Plus 的部署页面可以认出来不
