### ISSUE TITLE
关于重建Windows激活令牌和清除Office激活信息功能

### ISSUE THREAD

**Issue by Nexchard** [YerongAI/Office-Tool#801]
目前需要一个能清除现有Windows和office激活的工具，看到贵项目存在相关功能，想知道是如何实现的，能否开源这部分代码或告知其实现方式

**Comment by YerongAI** [comment]
List:

- Clean.ps1 -> https://gist.github.com/ave9858/9fff6af726ba3ddc646285d1bbf37e71
- Rebuild activation token: [Help docs](https://otp.landian.vip/docs/zh-cn/toolbox/windows.html#%E9%87%8D%E5%BB%BA-windows-%E6%BF%80%E6%B4%BB%E4%BB%A4%E7%89%8C)

你想知道的都在这里。
