### ISSUE TITLE
无法通过已下载的cab文件创建ISO文件[BUG] 

### ISSUE THREAD

**Issue by 2565904536** [YerongAI/Office-Tool#804]
**Office Tool Plus Version, e.g. 8.1.0.0:**
> 10.8.5.0

**Operating System, e.g. Windows 10 20H2 or Windows 7 SP1:**
> windows 10

**Error description (required):**
> 不能通过已下载的cab文件创建ISO文件

*Reproduction steps (suggested):*

*Screenshot (suggested):*

*Additional information (optional):*

**Comment by 2565904536** [comment]
文件不在office tool安装目录时，即使指定了cab文件也会会提示找不到安装文件

**Comment by YerongAI** [comment]
已添加新功能，下个版本发布。
