### ISSUE TITLE
[BUG] 卸载office有个很老版本 Microsoft Office 2000 Premium 的注册表没有清除掉 

### ISSUE THREAD

**Issue by kokutoukiritsugu** [YerongAI/Office-Tool#805]
**Office Tool Plus Version, e.g. 8.1.0.0:**
> 10.8.5.0

**Operating System, e.g. Windows 10 20H2 or Windows 7 SP1:**
> windows 10

**Error description (required):**
> 卸载office有个很老版本 Microsoft Office 2000 Premium 的注册表没有清除掉 

系统里就剩下这个注册表，别的啥也没有了。

[408000001E872D116BF00006799C897E.reg.zip](https://github.com/YerongAI/Office-Tool/files/14621906/408000001E872D116BF00006799C897E.reg.zip)

**Comment by YerongAI** [comment]
这个大概率是因为原来的安装源找不到了，导致这个包卸载失败，所以会留下这么一个注册表信息。

通常来讲正常情况下，如果卸载了这个包，相关注册表信息会自动清除。

**Comment by YerongAI** [comment]
刚发布的新版已尝试解决此问题，感谢您的反馈。
