### ISSUE TITLE
[BUG] 

### ISSUE THREAD

**Issue by yiwang103** [YerongAI/Office-Tool#806]
**Office Tool Plus Version, e.g. 8.1.0.0:**
> Write down here
10.8.5.0
**Operating System, e.g. Windows 10 20H2 or Windows 7 SP1:**
> Write down here
win11
**Error description (required):**
> Write down here
已经开启了询问文件保存位置，但是依然直接默认安装，没有进行询问
*Reproduction steps (suggested):*

*Screenshot (suggested):*

*Additional information (optional):*

**Comment by YerongAI** [comment]
有没有想过这个设置问的是下载在哪里而不是问安装在哪里？

![image](https://github.com/YerongAI/Office-Tool/assets/44803668/1ad6a29c-442f-4748-8d2b-cd7720d7b610)
