### ISSUE TITLE
[BUG] 运行激活报错

### ISSUE THREAD

**Issue by 2018-11-27** [YerongAI/Office-Tool#811]
下载包名称：Office_Tool_with_runtime_v10.8.5.0_x64.zip

我的系统：Win11 专业版（已激活）

Office版本：当前最新个人版

报错如图：
![image](https://github.com/YerongAI/Office-Tool/assets/45390011/b83c2432-6ab4-4462-ac5c-5b579b381fe5)

**Comment by YerongAI** [comment]
这种情况我只能说：

1. 没看教程
2. 没买正版是这样的
