### ISSUE TITLE
[BUG] NONONO

### ISSUE THREAD

**Issue by flyyhui** [YerongAI/Office-Tool#815]
NONONO

**Comment by zyxnet0115** [comment]
今天愚人节。四月一号。XD

**Comment by flyyhui** [comment]
这种愚人行为，并不高明，也并不好笑。强烈建议收回。


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "YerongAI/Office-Tool"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2024年4月1日(星期一) 上午10:50
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [YerongAI/Office-Tool] [BUG] 打开软件后会自动弹出更新，但点更新时会跳到bilibili的网站，而且对比官方和github并没有更新的版本 (Issue #815)





 
今天愚人节。四月一号。XD
