### ISSUE TITLE
[BUG] It is not possible to add licenses for version 2024

### ISSUE THREAD

**Issue by blockke** [YerongAI/Office-Tool#816]
**Office Tool Plus Version, e.g. 8.1.0.0:**
> 10.10.3.0

**Operating System, e.g. Windows 10 20H2 or Windows 7 SP1:**
> Windows 11 22H4

**Error description (required):**
> It is not possible to add licenses for version 2024

*Reproduction steps (suggested):*

*Screenshot (suggested):*

*Additional information (optional):*

**Comment by blockke** [comment]
Office Tool Plus Version, e.g. 10.10.3.0
Operating System, e.g. Windows 11 22H4:
Error description (required):It is not possible to add licenses for version 2024

**Comment by YerongAI** [comment]
Please provide the reproduction steps and screenshot.

**Comment by Yamds** [comment]
![cf8bbcad4f17068e85c25c1480032d71](https://github.com/YerongAI/Office-Tool/assets/83116013/953ae68b-bfe6-4243-8490-c123f5328569)
windows11 23h2，我也遇到这个

**Comment by byggames** [comment]
yesterday i couldn't activate it because it give me a error, it said that i didn't installed the license but I installed it with the program and its impossible to install, you have to install the LTSC license version

**Comment by Zhangdata** [comment]
officetoolplus安装失败
![84dc0d8f-9d01-489c-b26c-74ee392ca7fd](https://github.com/user-attachments/assets/315ae98d-18b3-4b4e-bb2b-7b4014208129)

**Comment by YerongAI** [comment]
New version 10.14.28.0 released. We have add all product keys of Office 2024, now everything should work fine.
