### ISSUE TITLE
[BUG]Always presenting "spp is runing" but endless

### ISSUE THREAD

**Issue by Yingluobaidao** [YerongAI/Office-Tool#820]
**Office Tool Plus Version, e.g. 8.1.0.0:**
> Write down here

**Operating System, e.g. Windows 10 20H2 or Windows 7 SP1:**
> Write down here

**Error description (required):**
> Write down here

*Reproduction steps (suggested):*

*Screenshot (suggested):*

*Additional information (optional):*

**Comment by YerongAI** [comment]
To solve the problem, first restart Office Tool Plus and try again.

If the progress stuck again, check your OS environment, such as WMI components.
