### ISSUE TITLE
Please simple question [not an issue]

### ISSUE THREAD

**Issue by EstherMoellman** [YerongAI/Office-Tool#824]
Hi,

Firstly, thank you for your Office-Tool! Please, I have two simple questions:

1. By using your Office-Tool on Windows 11, is it possible to install the latest version of Office, but without the CTR (Click-To-Run) stuff? If yes, please, how to do it?

2. If it's not possible to install latest Office without CTR, for Windows 11 is it possible to use your Office-Tool to install an Office version (2016?) without the CTR (Click-To-Run) stuff? If yes, please, how to do it?

In short: For Windows 11, I need to install Office, I prefer the latest Office version, but my priority is to avoid the CTR (Click-To-Run) stuff, so I'm open to install any Office version (even an old one) capable to work without CTR (Click-To-Run) stuff.
On Windows 11, I tested every tutorial in the web, but I couldn't make work Office 2021 without CTR (Click-To-Run) stuff. If CTR is removed, blocked, deleted or disabled in any way, Office stops working.

I appreciate your help.

Thank you in advance!

**Comment by YerongAI** [comment]
Sorry but it's impossible.
