### ISSUE TITLE
[BUG] 移除offic，把我英伟达显卡的驱动给去掉了，重新安装显卡驱动可以正常使用，但是电脑重启又变成驱动不能正常运行。

### ISSUE THREAD

**Issue by oqmmdcm** [YerongAI/Office-Tool#826]
**Office Tool Plus Version, e.g. 8.1.0.0:**
> Write down here

**Operating System, e.g. Windows 10 20H2 or Windows 7 SP1:**
> Write down here

**Error description (required):**
> Write down here

*Reproduction steps (suggested):*

*Screenshot (suggested):*

*Additional information (optional):*

**Comment by YerongAI** [comment]
所以有没有可能就是这件事跟 Office 一点关系都没有，它们只是恰好发生在一个时间点上。
