### ISSUE TITLE
[BUG] 无法保存 KMS 设置，没有在系统中找到有效的 Office KMS 许可证。

### ISSUE THREAD

**Issue by xiebruce** [YerongAI/Office-Tool#827]
**Office Tool Plus Version, e.g. 8.1.0.0:**
> v10.10.7.0 (x64)

**Operating System, e.g. Windows 10 20H2 or Windows 7 SP1:**
> Windows 10 专业版 22H2
<img width="407" alt="image" src="https://github.com/YerongAI/Office-Tool/assets/13575500/c27d7722-7df3-41f7-84ae-b2375a8b8968">

**Error description (required):**
> 设置KMS主机时，提示：无法保存 KMS 设置，没有在系统中找到有效的 Office KMS 许可证。
<img width="601" alt="image" src="https://github.com/YerongAI/Office-Tool/assets/13575500/9ef8b347-bb82-4cdc-aee9-ce1fa36b54da">

*Reproduction steps (suggested):*
<img width="999" alt="image" src="https://github.com/YerongAI/Office-Tool/assets/13575500/0ac6a23e-e2ed-49a5-b954-304bf82c2a0f">
<img width="997" alt="image" src="https://github.com/YerongAI/Office-Tool/assets/13575500/28f34c7a-e914-46b9-b348-bd008f5b5dfc">

安装好之后，可以正常打开word
<img width="1079" alt="image" src="https://github.com/YerongAI/Office-Tool/assets/13575500/52555d9d-7715-4a88-a2a2-4331e0926501">

然后我开始激活，按教程，清除激活信息
<img width="1113" alt="image" src="https://github.com/YerongAI/Office-Tool/assets/13575500/f34d9b19-002d-47f5-8483-ebcdae1b7ae3">

然后安装许可证
<img width="1028" alt="image" src="https://github.com/YerongAI/Office-Tool/assets/13575500/684f5168-e022-4130-bbdd-aa0fdfad3047">

我从许可证列表选择的，就是我安装的office版本，Office LTSC 2021 专业增加版 2021（SPLA）- 批量许可证
<img width="600" alt="image" src="https://github.com/YerongAI/Office-Tool/assets/13575500/051c00aa-5939-4b53-8a95-181335377334">

右下角显示安装成功
<img width="456" alt="image" src="https://github.com/YerongAI/Office-Tool/assets/13575500/d71aa997-dac9-4693-8889-f11a484b796e">

这里也能刷新出来许可证，不过有个错误代码：0x4004F00C，不知道是不是跟这有关？
<img width="1011" alt="image" src="https://github.com/YerongAI/Office-Tool/assets/13575500/557eb46d-52be-4c7f-b5d4-aafc9404793d">

然后设置KMS主机时，每次都弹窗提示：无法保存 KMS 设置，没有在系统中找到有效的 Office KMS 许可证。

*Additional information (optional):*
我试过卸载重装（当然因为之前安装已经下载过有缓存，所以很快），但也没用，一设置KMS主机就弹窗提示：无法保存 KMS 设置，没有在系统中找到有效的 Office KMS 许可证。

**Comment by YerongAI** [comment]
SPLA 不是 Office KMS 许可证。

**Comment by xiebruce** [comment]
好家伙，我正怀疑是这个的问题呢，那我安装它上面那个应该没问题吧？
<img width="546" alt="image" src="https://github.com/YerongAI/Office-Tool/assets/13575500/3f1e984c-a414-41eb-995f-4fac1a11a4dc">

**Comment by YerongAI** [comment]
> 好家伙，我正怀疑是这个的问题呢，那我安装它上面那个应该没问题吧？
> <img width="546" alt="image" src="https://github.com/YerongAI/Office-Tool/assets/13575500/3f1e984c-a414-41eb-995f-4fac1a11a4dc">
> 

没有问题。

**Comment by xiebruce** [comment]
> > 好家伙，我正怀疑是这个的问题呢，那我安装它上面那个应该没问题吧？
> > <img alt="image" width="546" src="https://private-user-images.githubusercontent.com/13575500/327281594-3f1e984c-a414-41eb-995f-4fac1a11a4dc.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTQ2MTE2MzcsIm5iZiI6MTcxNDYxMTMzNywicGF0aCI6Ii8xMzU3NTUwMC8zMjcyODE1OTQtM2YxZTk4NGMtYTQxNC00MWViLTk5NWYtNGZhYzFhMTFhNGRjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MDIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTAyVDAwNTUzN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWQyY2VlNTQ3ODc5MmEyNmNmMDRhYWE3YmMzNDQ0NjJlODNkZWExOTkwMTViNDJkZmUxMGY5ZGY0YjE5NDdiN2YmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.rNe1OCD9llLJbjmJ0FJVpiytruGIopkF5xMNLjMo32A">
> 
> 没有问题。

安装这个版本已经好了，但是安装好就是激活的，我根本没有去做激活操作，它是会自动激活吗？

**Comment by YerongAI** [comment]
> > > 好家伙，我正怀疑是这个的问题呢，那我安装它上面那个应该没问题吧？
> > > <img alt="image" width="546" src="https://private-user-images.githubusercontent.com/13575500/327281594-3f1e984c-a414-41eb-995f-4fac1a11a4dc.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTQ2MTE2MzcsIm5iZiI6MTcxNDYxMTMzNywicGF0aCI6Ii8xMzU3NTUwMC8zMjcyODE1OTQtM2YxZTk4NGMtYTQxNC00MWViLTk5NWYtNGZhYzFhMTFhNGRjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MDIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTAyVDAwNTUzN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWQyY2VlNTQ3ODc5MmEyNmNmMDRhYWE3YmMzNDQ0NjJlODNkZWExOTkwMTViNDJkZmUxMGY5ZGY0YjE5NDdiN2YmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.rNe1OCD9llLJbjmJ0FJVpiytruGIopkF5xMNLjMo32A">
> > 
> > 没有问题。
> 
> 安装这个版本已经好了，但是安装好就是激活的，我根本没有去做激活操作，它是会自动激活吗？

并不会，可能只是恰好发生了什么事而已。
