### ISSUE TITLE
[BUG] 出现报错Windows 找不到文件 'C:\Program Files\Microsoft Office\root\Office16\WINWORD.EXE'。请确定文件名是否正确后，再试一次

### ISSUE THREAD

**Issue by Zpcola** [YerongAI/Office-Tool#830]
**Office Tool Plus Version, e.g. 8.1.0.0:**
> v10.10.7.0（x64）

**Operating System, e.g. Windows 10 20H2 or Windows 7 SP1:**
> Windows11 23h2

**Error description (required):**
> 点击office图标提示
“Windows 找不到文件 'C:\Program Files\Microsoft Office\root\Office16\WINWORD.EXE'。请确定文件名是否正确后，再试一次。”

*Reproduction steps (suggested):*
关闭所有安全软件，安装office后点击桌面图标，出现报错。进入软件根目录后点击“POWERPNT.EXE”，出现同样的报错。使用office联机修复功能后，仍然出现同样的报错

*Screenshot (suggested):*
<img width="899" alt="Snipaste_2024-05-13_20-52-11" src="https://github.com/YerongAI/Office-Tool/assets/116626041/4b9de3ba-954c-43d2-b790-24cbefb39ba5">
<img width="368" alt="Snipaste_2024-05-13_20-42-32" src="https://github.com/YerongAI/Office-Tool/assets/116626041/2c483dce-0381-4952-9b28-5f5365c387dd">

**Comment by YerongAI** [comment]
没遇到过，建议是重装。

> 以及这里一般不接受 Office 问题咨询，有问题都是自行解决。

**Comment by Zpcola** [comment]
经过测试发现原因是安装了64位导致的，更换32位后问题解决，不过还是想吐槽，这个问题好奇怪

**Comment by Zpcola** [comment]
<img width="640" alt="Snipaste_2024-05-14_12-47-24" src="https://github.com/YerongAI/Office-Tool/assets/116626041/e75fdb0e-e212-469e-adf4-ee843a5f2560">
