### ISSUE TITLE
[BUG] 安装office2024ltsc报错

### ISSUE THREAD

**Issue by excosy** [YerongAI/Office-Tool#842]
**Office Tool Plus Version, e.g. 8.1.0.0:**
10.11.5.0

**Operating System, e.g. Windows 10 20H2 or Windows 7 SP1:**
Windows 11 24H2

**Error description (required):**
安装通道 office2024企业长期版
安装产品 standard2024vol 时出现错误，代码为30088-45。切换部署工具仍然同样错误。虽然安装失败但是会显示产品已部署且无法正常卸载。
该通道安装产品 proplus2024vol 时不会报错并可正常安装完成和卸载。

**Comment by excosy** [comment]
<img width="450" alt="配置信息" src="https://github.com/YerongAI/Office-Tool/assets/10704642/8b17fc34-7cf9-4572-9679-70f65cdb2976">
<img width="368" alt="报错1" src="https://github.com/YerongAI/Office-Tool/assets/10704642/81f51a85-55fb-4145-a85b-786e60ba92ce">
<img width="368" alt="报错2" src="https://github.com/YerongAI/Office-Tool/assets/10704642/20d4c5f8-15b9-410c-ac81-c20e55c19c8b">

**Comment by YerongAI** [comment]
这是正常状况，Office 2024 系列产品尚未正式发布，只有 2024 Pro Plus 可安装并尝试。
