### ISSUE TITLE
[BUG]  Issue when installing on Windows 10 IoT LTSC 2021 (Windows10 10.0.19044.4412 x64)

### ISSUE THREAD

**Issue by rjbprime** [YerongAI/Office-Tool#844]
**Office Tool Plus Version, e.g. 8.1.0.0:**
> 10.11.5.0

**Operating System, e.g. Windows 10 20H2 or Windows 7 SP1:**
> Windows 10 IoT LTSC 2021 10.0.19044.4412 x64

**Error description (required):**
> Clicking ``Start Deploy`` on Deploy page throws an error.

*Reproduction steps (suggested):*
* Configure Architecture, Products, Languages and Advanced Settings
  * Set Architecture to 64-bit
  * Choose Products: Microsoft 365 apps for Enterprise, Project Professional 2016 and Visio Professional 2016
  * Choose Language: English US (en-us)
  * Choose Advanced Settings > Activation Settings > Automatically accept the EULA
* Click Deploy
* Throw error

*Screenshot (suggested):*
![OTP-Error-Windows-10-ltsc-2021](https://github.com/YerongAI/Office-Tool/assets/10142751/c6299e81-aa27-43c8-9342-bfcc469b83d5)

*Additional information (optional):*
This has been going on for all the v10 releases I have tried (at least 3 different versions). Not sure what is causing it. Tried over several different installs of Windows 10, one windows 11 install, and two different devices.

**Comment by YerongAI** [comment]
The issue was fixed. The new version will be released on the next week.

**Comment by rjbprime** [comment]
10-4. I'll keep an eye out for it.

**Comment by YerongAI** [comment]
New release was out.
