### ISSUE TITLE
下载大文件完毕卡住[BUG] 

### ISSUE THREAD

**Issue by MaeThird** [YerongAI/Office-Tool#846]
**Office Tool Plus Version, e.g. 8.1.0.0:**
> 10.12.6.0(X64)

**Operating System, e.g. Windows 10 20H2 or Windows 7 SP1:**
> Windows 11 22H2

**Error description (required):**
> 下载大文件（stream.x64.x-none.dat和语言包文件）完毕（显示100%）以后卡住，进程没死，也没有使用网络后续下载，不知道程序在干嘛。暂停然后继续下载依然卡住。关闭应用再重启应用，能够继续往后下载，但是进入office安装界面以后卡在进度5%，查了下微软的文档说是 stream.x64.x-none.dat这个文件损坏。
问题不是必现的，因为搞了大半天终于有一次下载没卡了，就是费了十几G流量，应该不是网络问题，每次下载大概5-10M速度。

**Comment by YerongAI** [comment]
我试过，没问题。

你可以尝试更换下载引擎，也可以尝试更换网络。

如果怀疑文件有问题，可以通过安装文件管理面板进行校验。
