### ISSUE TITLE
[BUG] 自动激活的命令行按钮找不到了

### ISSUE THREAD

**Issue by liYue-feng** [YerongAI/Office-Tool#847]
**Office Tool Plus Version, e.g. 8.1.0.0:**
> Write down here

**Operating System, e.g. Windows 10 20H2 or Windows 7 SP1:**
> Write down here

**Error description (required):**
> Write down here

*Reproduction steps (suggested):*

*Screenshot (suggested):*

*Additional information (optional):*

**Comment by YerongAI** [comment]
在 Windows 11 中已将云母效果作为程序的默认背景。找不到按钮时，请按下 <kbd>Ctrl</kbd> + <kbd>Shift</kbd> + <kbd>P</kbd> 打开命令框。
