### ISSUE TITLE
[BUG] v10.12.7.0 

### ISSUE THREAD

**Issue by szmabcd** [YerongAI/Office-Tool#848]
v10.12.7.0 下载office后，安装源文件选择下载的文件，断网安装会报错，联网安装就不会报错

![PixPin_2024-06-27_21-03-37](https://github.com/YerongAI/Office-Tool/assets/38176269/a7c6906e-e352-4db3-ae6d-9eb9ece24ef6)

![PixPin_2024-06-27_21-04-01](https://github.com/YerongAI/Office-Tool/assets/38176269/28a3c80e-f6d9-41b1-93cb-3b878a89ddef)

**Comment by YerongAI** [comment]
请提供【安装文件管理】面板里面的 Office 安装文件信息截图

**Comment by szmabcd** [comment]
![PixPin_2024-06-27_21-24-27](https://github.com/YerongAI/Office-Tool/assets/38176269/e6b65f47-1e8d-4705-a195-13d354741eac)

![PixPin_2024-06-27_21-23-57](https://github.com/YerongAI/Office-Tool/assets/38176269/b08a036a-88f8-450d-a06d-ff4e06e300cb)

**Comment by YerongAI** [comment]
> ![PixPin_2024-06-27_21-24-27](https://private-user-images.githubusercontent.com/38176269/343792994-e6b65f47-1e8d-4705-a195-13d354741eac.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTk0OTYzNTEsIm5iZiI6MTcxOTQ5NjA1MSwicGF0aCI6Ii8zODE3NjI2OS8zNDM3OTI5OTQtZTZiNjVmNDctMWU4ZC00NzA1LWExOTUtMTNkMzU0NzQxZWFjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MjclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjI3VDEzNDczMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWQ3YzViNzZkZTllMTIxMWExOTZhMDczNGFhNjk2MTFmOGNlODBkZGEwMGFjNWUxMGI0YzMxZjdiZjEwODViYzYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.TZFVJvCXI9ANUhbbbFXfePoUxrhDLR6Gzz2jiFEfBw4)
> 
> ![PixPin_2024-06-27_21-23-57](https://private-user-images.githubusercontent.com/38176269/343793049-b08a036a-88f8-450d-a06d-ff4e06e300cb.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTk0OTYzNTEsIm5iZiI6MTcxOTQ5NjA1MSwicGF0aCI6Ii8zODE3NjI2OS8zNDM3OTMwNDktYjA4YTAzNmEtODhmOC00NTBkLWEwNmQtZmY0ZTA2ZTMwMGNiLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MjclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjI3VDEzNDczMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWM2MmVkNWU1NWExN2FmYmIxMmI3MjYzOWY3OThiYjg5NjI4NWYwYzgxNzM2YTU0MGVkZjhlNjZmODFmYmY1NGEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.CQhhV8APowS8CbPGnYki00B7d5ZhQwfArIJnPf8Whe8)

第二张图截图不全，请重新提供

**Comment by szmabcd** [comment]
行，我试下，谢谢

**Comment by Unknown78** [comment]
@YerongAI Confirmed same issue.

![image](https://github.com/YerongAI/Office-Tool/assets/25132599/0f3181a4-bbfc-4e04-a2bc-8cdad778de91)

**Comment by YerongAI** [comment]
请问问题是否已经解决？

**Comment by szmabcd** [comment]
> 请问问题是否已经解决？

已解决，谢谢
