### ISSUE TITLE
[IDEA] Remove only specific components

### ISSUE THREAD

**Issue by Morgan-6Freedom** [YerongAI/Office-Tool#852]
**Feature description:**
Be able to uninstall component by component. For example uninstall only outlook.
Also : be able to uninstall "Outlook" and not "Outlook (new)"

**Comment by YerongAI** [comment]
Just uncheck Outlook on apps panel and start deploy.

**Comment by Morgan-6Freedom** [comment]
can I use the tool to remove 1 app ?

**Comment by YerongAI** [comment]
> can I use the tool to remove 1 app ?

[https://otp.landian.vip/docs/deploy/modify.html#modify-applications](https://otp.landian.vip/docs/deploy/modify.html#modify-applications)
