### ISSUE TITLE
[BUG] 无法部署

### ISSUE THREAD

**Issue by xianrui-luo** [YerongAI/Office-Tool#853]
**Office Tool Plus Version, e.g. 8.1.0.0:**
> Write down here

**Operating System, e.g. Windows 10 20H2 or Windows 7 SP1:**
> Write down here

**Error description (required):**
> Write down here

*Reproduction steps (suggested):*

*Screenshot (suggested):*
![image](https://github.com/YerongAI/Office-Tool/assets/44058627/4d4cadbc-23c9-4b9f-880c-97aeb3a50973)

*Additional information (optional):*

**Comment by YerongAI** [comment]
没见过这种错误，也暂时不知道解决办法
