### ISSUE TITLE
[BUG] 部署时报 Error Code: 30182-2016 (448)

### ISSUE THREAD

**Issue by ousugo** [YerongAI/Office-Tool#860]
**Office Tool Plus Version, e.g. 8.1.0.0:**
> Write down here

10.13.10.0(x64)

**Operating System, e.g. Windows 10 20H2 or Windows 7 SP1:**
> Write down here

Windows11 23H2(22631.3880)

**Error description (required):**
> Write down here

运行部署工具后，报下面错误：
```
Couldn't install
We're sorry, we can't continue because we weren't able to download a required
file. Please make sure you're connected to the internet or connect to a different
network, then try again.
Go online for additional help.
Error Code: 30182-2016 (448)
```
尝试关闭代理、更换DNS、切换手机热点，都无法解决。但这时候通过 OfficeSetup.exe 安装或者通过自己下载的 ODT 安装都不会报错，可以成功安装。

*Reproduction steps (suggested):*

![image](https://github.com/user-attachments/assets/96b1dab2-7703-41b9-864f-6bc7b6a9adb8)

开始部署--> 下载完成 --> 运行部署工具 --> 报错

*Screenshot (suggested):*

*Additional information (optional):*

**Comment by YerongAI** [comment]
请提供完整的 XML 代码，在部署页面按下 <kbd>Ctrl</kbd> + <kbd>E</kbd> 可查看。

**Comment by ousugo** [comment]
![image](https://github.com/user-attachments/assets/27fc6ef2-15e0-4b6f-949c-b7cc54d682b6)
![image](https://github.com/user-attachments/assets/d1ff041c-ea4e-4e77-b8b5-5027335062a1)
当时这两个都尝试了，都是一样的报错

**Comment by YerongAI** [comment]
最后一个看起来并不正常。如果 DownloadFirst 已启用，应该先触发 Office 下载步骤，然后再进行部署。然而 XML 里面看不见 SourcePath 和 Version 参数。

**Comment by ousugo** [comment]
> 最后一个看起来并不正常。如果 DownloadFirst 已启用，应该先触发 Office 下载步骤，然后再进行部署。然而 XML 里面看不见 SourcePath 和 Version 参数。

这是我还原当时的设置，因为我后面自己用 ODT 部署成功了，所以没有实际再下载了。

我刚又在Windows 沙盒里面测试了一下，XML 里是有 SourcePath 和 Version 参数的。同样的操作步骤没有碰到这个网络报错问题了。

不知道当时是哪里抽风了可能...

**Comment by YerongAI** [comment]
微软的报错不一定就是它所报错的内容。可以通过重新收集安装日志进行分析，安装日志在没有手动删除的情况下是永久保留的。通过 Office Tool Plus，转到工具箱页面，选择收集 Office 安装程序日志。

**Comment by ousugo** [comment]
[Office_Log.zip](https://github.com/user-attachments/files/16319164/Office_Log.zip)

日志上传了，主要尝试是在 17号，那麻烦帮忙看下能不能找到问题，感谢

**Comment by YerongAI** [comment]
> [Office_Log.zip](https://github.com/user-attachments/files/16319164/Office_Log.zip)
> 
> 日志上传了，主要尝试是在 17号，那麻烦帮忙看下能不能找到问题，感谢

是 v64_16.0.xxxxx.xxxxx.cab 文件无法打开，错误代码为 0x1c0，但并不知道此问题的具体情况，所以也不是很好分析。如果怀疑是文件损坏，可以在 Office Tool Plus 的部署页面中，通过安装文件管理面板校验 Office 安装文件。

**Comment by ousugo** [comment]
不是文件损坏应该，我每次下载完都进行了校验。

辛苦了。

**Comment by ousugo** [comment]
通过 OfficeSetup.exe 安装或者通过自己下载的 ODT 安装

**Comment by ousugo** [comment]
> 我也出现了这个报错，请问最后怎么解决的

通过 OfficeSetup.exe 安装或者通过自己下载的 ODT 安装

**Comment by Parahexen** [comment]
```
"{\"Crack URL failed\":\"message\",\"Url\":\"D:\\\\Tools\\\\Scoop\\\\scoop\\\\apps\\\\office-tool-plus\\\\current\\\\Office\\\\Data\\\\v64_16.0.17932.20252.cab\"}"}
```
不知道是什么原因导致文件地址```D:\\Tools\\Scoop\\scoop\\apps\\office-tool-plus\\current\\Office\\Data\\v64_16.0.17932.20252.cab```无法被解析。

**Comment by LaelLuo** [comment]
估计就是office的垃圾代码导致安装程序没办法正确读取带junction的路径咧
