### ISSUE TITLE
错误：读取安装文件时出现错误，请尝试重新读取，或者重新下载Office安装文件。

### ISSUE THREAD

**Issue by yea-sky** [YerongAI/Office-Tool#861]
![image](https://github.com/user-attachments/assets/7cc1f055-546e-4710-99bc-7a0f0b6a257a)

**Comment by YerongAI** [comment]
请按下 <kbd>Ctrl</kbd> + <kbd>Shift</kbd> + <kbd>P</kbd>，或点击右上方的命令按钮，输入 `/getlogs` 获取日志，查看日志中的报错信息。

**Comment by yea-sky** [comment]
> 请按下 Ctrl + Shift + P，或点击右上方的命令按钮，输入 `/getlogs` 获取日志，查看日志中的报错信息。

Time	Type	Action	Message
2024/7/24 18:52:12	Info	Init	Registering events.
2024/7/24 18:52:13	Info	Init	Loading application settings.
2024/7/24 18:52:13	Info	Init	Loaded 3 value(s).
2024/7/24 18:52:13	Info	Init	Updating application settings.
2024/7/24 18:52:13	Info	Check envs	OS version: Microsoft Windows 10.0.22000 X64.
2024/7/24 18:52:13	Info	Check envs	OS language: zh-CN.
2024/7/24 18:52:13	Info	Check envs	OS culture: zh-CN.
2024/7/24 18:52:13	Info	Check envs	OS region: CN.
2024/7/24 18:52:13	Info	Check envs	OS is 64-bit: True.
2024/7/24 18:52:13	Info	Check envs	Working directory is D:\Chrome Download\Office_Tool_with_runtime_v10.13.10.0_x64\Office Tool
2024/7/24 18:52:13	Info	Check envs	Screen resolution: 2736 x 1824.
2024/7/24 18:52:13	Info	Check envs	Primary resolution: 1563.4285714285713 x 1042.2857142857142.
2024/7/24 18:52:13	Info	Check envs	Virtual resolution: 1563.4285714285713 x 1642.2857142857142.
2024/7/24 18:52:13	Info	Check envs	Current window size: 1172.5714285714284 x 726.2857142857142.
2024/7/24 18:52:13	Info	Check envs	Current process ID: 10840.
2024/7/24 18:52:13	Info	Check envs	Current process architecture: X64.
2024/7/24 18:52:13	Info	Check envs	Current process is 64-bit: True.
2024/7/24 18:52:13	Info	Init	Binding commands.
2024/7/24 18:52:13	Info	Init	Commands binding done.
2024/7/24 18:52:13	Info	Init	Temp path is set to C:\Users\yausi\AppData\Local\Temp\OTP_5804
2024/7/24 18:52:13	Info	Init	Registering taskbar item.
2024/7/24 18:52:13	Info	Init	Permission is administrator.
2024/7/24 18:52:13	Info	Update	Checking updates.
2024/7/24 18:52:14	Warning	ClientUpdate	Cannot connect to server. Error (-2146233088): '<' is an invalid start of a value. Path: $ | LineNumber: 0 | BytePositionInLine: 0.. Inner exception (-2146233088): '<' is an invalid start of a value. LineNumber: 0 | BytePositionInLine: 0.
2024/7/24 18:52:14	Info	ClientUpdate	Application version is higher than required version, skip update.
2024/7/24 18:52:14	Info	ClientUpdate	Process architecture doesn't match the requirement, skip update.
2024/7/24 18:52:15	Warning	ClientConfig	Cannot connect to server. Error (-2146233088): '<' is an invalid start of a value. Path: $ | LineNumber: 0 | BytePositionInLine: 0.. Inner exception (-2146233088): '<' is an invalid start of a value. LineNumber: 0 | BytePositionInLine: 0.
2024/7/24 18:52:15	Info	Update	Application is up to date.
2024/7/24 18:52:19	Info	Deploy	Loading Office information.
2024/7/24 18:52:19	Info	Deploy	Office is not detected on system.
2024/7/24 18:52:19	Info	Deploy	Successfully obtaining C2R releases information.
2024/7/24 18:52:19	Info	Deploy	Successfully obtaining Office version information.
2024/7/24 18:52:58	Info	Deploy	Initiating download task, save path is: D:\Chrome Download\Office_Tool_with_runtime_v10.13.10.0_x64\Office Tool
2024/7/24 18:52:58	Info	Downloader	Init download tasks.
2024/7/24 18:52:59	Info	Downloader	Chunk count: 4.
2024/7/24 18:52:59	Info	Downloader	ParallelDownload: True.
2024/7/24 18:53:00	Error	CheckInstallation	Error occurred while checking Office installation files. Error (-2146232800): Cabinet file does not have the correct format. Error code: 0

**Comment by YerongAI** [comment]
从日志中能够看出如下信息：

- 读取 CAB 文件时出现了错误，可能是 CAB 文件损坏了，尝试重新下载。
- Windows 不是最新版本，尝试用 Windows Update 检查更新。

**Comment by yea-sky** [comment]
> 从日志中能够看出如下信息：
> 
> * 读取 CAB 文件时出现了错误，可能是 CAB 文件损坏了，尝试重新下载。
> * Windows 不是最新版本，尝试用 Windows Update 检查更新。

Windows 已经更新好了，但是还是报错，请问下CAB文件损坏是重新下载OTP就好了吗？

**Comment by YerongAI** [comment]
> > 从日志中能够看出如下信息：
> > 
> > * 读取 CAB 文件时出现了错误，可能是 CAB 文件损坏了，尝试重新下载。
> > * Windows 不是最新版本，尝试用 Windows Update 检查更新。
> 
> Windows 已经更新好了，但是还是报错，请问下CAB文件损坏是重新下载OTP就好了吗？

不是，CAB 文件损坏需要删除并重新下载 Office 安装文件。如无法确定是否是安装包出了问题，可以前往 [OneDrive](https://otp.landian.vip/redirect/download.php?site=onedrive) 或[云图小镇](https://otp.landian.vip/redirect/download.php?site=yuntu)获取 Office ISO 文件。

**Comment by YerongAI** [comment]
您好，经过排查已经确认是 Office 2024 安装包包含错误，而不是程序识别失败。此问题只能等待微软进行解决，但看起来巨硬并没有。

**Comment by YerongAI** [comment]
似乎微软已经修复了此问题。我这边测试已经一切正常。
