### ISSUE TITLE
Launch Microsoft Store APPs instead of launching the web page.

### ISSUE THREAD

**Issue by szw0407** [YerongAI/Office-Tool#865]
**Feature description:**
The Todo, Sway and Loop links on the home page is opening the web browser. However, many users have installed these programs via Microsoft store. They can be launched instead.

**How it work?**
Click on the icons of, for example Todo, then the Todo App opens.

Technical Reference (if possible):
Call the relavant URLs, like `ms-to-do:` to open the links. Or, detect the installed APPs and open them if possible. If not installed, the link can direct the user to the Microsoft store to install it via `ms-store://` or the original URL to open the browser.

**Comment by YerongAI** [comment]
Done. Also added Power BI Desktop and Teams. Please wait for the new version released.

**Comment by YerongAI** [comment]
The Sway doesn't have desktop app. The Loop desktop app is a PWA application. Use Loop web is a better choice.

**Comment by szw0407** [comment]
In fact sway also has a PWA APP on Microsoft store. Anyway, personally I prefer PWA as the App launches without opening a browser with all tabs. It is just a window with no extra element.

**Comment by YerongAI** [comment]
> In fact sway also has a PWA APP on Microsoft store. Anyway, personally I prefer PWA as the App launches without opening a browser with all tabs. It is just a window with no extra element.

Anyway, I have already finished working on this part of the code. We can make changes later if needed.

Also, I don’t think Office Tool Plus needs to be a launcher, using the Start menu is a better choice.
