### ISSUE TITLE
Detect installed Microsoft Office version on Home page

### ISSUE THREAD

**Issue by szw0407** [YerongAI/Office-Tool#866]
**Feature description:**
On the home page you can just Install Office and use some web Apps. I wish the installed version of Microsoft Office shown here, the version and the channel.

Moreover, buying Microsoft 365 can be redirected to Microsoft store APP so that purchase and installation can be done there.

**How it work?**
Detect the version by checking installed Microsoft Office.

Technical Reference (if possible):
Call the relavant URLs.

**Comment by YerongAI** [comment]
Thanks for your suggestion.

Currently the information for installed Office is show on the deploy page. Also you can view the information on Office Apps (such as Word) -> File -> Account page. We don't have any ideas to make them displayed on home page.

To buying the Microsoft 365, simply go to Microsoft Store and pay for it. After that, you can install Office via Office Tool Plus.
