### ISSUE TITLE
Command Line Switches / Uses In Powershell One Liner

### ISSUE THREAD

**Issue by kendi182** [YerongAI/Office-Tool#867]
**Feature description:**
> Run Office-Tools using PowerShell with an automation script for installation automatically using the unattended response file, similar to how it is done in MASSGRAVE.

**How it work?**
> https://massgrave.dev/command_line_switches

Technical Reference (if possible):
> This command below even works, but it asks 2 questions to download the program.

`& ([ScriptBlock]::Create((irm https://otp.landian.vip/get)))`

**Comment by YerongAI** [comment]
For command-line usage, you can view our [help docs](https://otp.landian.vip/docs/commands/build-in.html).

If you are looking for a batch which can download, install and activate Office automated, let us know. We will make it as you want.

**Comment by kendi182** [comment]
hello!
Yes, I wanted a /s or /silent setting to add to autounattend to download and install office 365 x64 in the pt-br language

**Comment by YerongAI** [comment]
> hello! Yes, I wanted a /s or /silent setting to add to autounattend to download and install office 365 x64 in the pt-br language

For installation, you can follow the [help docs](https://otp.landian.vip/docs/commands/deploy.html) to run Office Tool Plus and install Office automated.
