### ISSUE TITLE
[BUG] 安装时总是卡在92%

### ISSUE THREAD

**Issue by nssiwi** [YerongAI/Office-Tool#870]
**Office Tool Plus Version, e.g. 8.1.0.0:**
> 10.13.10.0

**Operating System, e.g. Windows 10 20H2 or Windows 7 SP1:**
> Windows 11 23H2 22631.3880

**Error description (required):**
> 安装时总是卡在92%的位置，持续时间

*Reproduction steps (suggested):*
安装的是个人及家庭版2019，部署产品排除掉了OneDrive和OneNote，部署模式选择生成ISO，然后打开生成的ISO进行安装，总是卡在92%的位置，最终会报错提示忽略或重试

*Screenshot (suggested):*
![PixPin_2024-08-08_21-06-49](https://github.com/user-attachments/assets/587dd82c-2fee-4328-a5c5-f2a8ba03a8e0)

*Additional information (optional):*

**Comment by YerongAI** [comment]
这是 Office 安装程序的问题，出现此问题大概率会与系统有关系，我们无法提供可靠帮助，也没有现成的、完美的解决方案。

目前为止唯一可靠的就是重装系统。当然，在此之前，您可以尝试卸载任何可能阻止或者干扰 Office 安装的程序，例如 WPS Office 或 360 系列安全软件。
