### ISSUE TITLE
[BUG] 无法部署，提示无法建立SSL连接

### ISSUE THREAD

**Issue by LxnChan** [YerongAI/Office-Tool#871]
**Office Tool Plus Version, e.g. 8.1.0.0:**
10.13.10.0

**Operating System, e.g. Windows 10 20H2 or Windows 7 SP1:**
Windows Server 2012 R2

**Error description (required):**
使用Office部署工具无法部署，这个是已知问题，按文档切换了Office Tool Plus，但是提示`The SSL connection could not be established, see inner exception`，感觉像无法建立SSL连接？会不会是缺证书？

*Reproduction steps (suggested):*

*Screenshot (suggested):*
![image](https://github.com/user-attachments/assets/16cccec9-3c90-4075-9de4-460043c14b15)

*Additional information (optional):*

**Comment by YerongAI** [comment]
按照 [这里](https://otp.landian.vip/docs/zh-cn/commands/build-in.html) 所说，打开命令框，输入 `/getlogs` 获取日志。

**Comment by han121381** [comment]
您好，想问一下，最后解决了吗，我最近也遇到这样的问题
