### ISSUE TITLE
[BUG] 不懂算不算bug.....

### ISSUE THREAD

**Issue by matocool** [YerongAI/Office-Tool#873]
WIN7系统        版本是 7601.27216

问题1：

从官网https://otp.landian.vip/zh-cn/download.html 下载最新版的软件，打开提示不支持win7 但是实际上还是可以打得开。。 不懂这算不算bug

问题2：因为是win7 ，百度了下最高支持2016  于是乎我选择 2016专业增强版。。但是不知为何下载成为2019专业增强版，并且在win7可以运行........我选择是的下载好之后再安装

希望大佬解惑下，谢谢大佬。。。膜拜ing

**Comment by YerongAI** [comment]
1. 不支持不意味着不能运行，但使用过程中所出现的任何问题都将得不到官方支持。
2. 产品和许可证不是一一对应的，可以分开安装不同的。
