### ISSUE TITLE
[BUG] 已安装dotNET但仍提示缺少dotNET，可能是由于hotfxr.dll引起

### ISSUE THREAD

**Issue by StonePick** [YerongAI/Office-Tool#876]
**Office Tool Plus Version, e.g. 8.1.0.0:**
> 10.14.21.8

**Operating System, e.g. Windows 10 20H2 or Windows 7 SP1:**
> Windows 11 家庭中文版 23H2

**Error description (required):**
> 从某个旧版本更新后，运行，提示缺少dotNET。安装.Net 60.0.33(x86)、8.0.8(x86和x64)后，依旧提示缺少.Net。

*Reproduction steps (suggested):*
1. 计算机内无.Net。
2. 从某个旧版本升级。此时运行，提示需要.Net。
3. 安装.Net，但报错仍未消除。
4. 将主程序所在目录下的hotfxr.dll删除后，才可以正常运行。

*Screenshot (suggested):*
略。

*Additional information (optional):*
再下载一个Office Tool（由于无hotfxr.dll，可以正常运行），将老OT的hotfxr移动到新OT中，新OT无法启动，并且不会弹出缺失.Net的信息（此时计算机内已安装.Net）。但是当hotfxr在老OT中时，老OT仍然会提示缺失。该情况可能是由于该hotfxr是由老OT生成导致。

**Comment by YerongAI** [comment]
这种情况已知晓，根本原因是有程序在持续清空 Temp 而导致 runtimes 拷贝不完全。

**Comment by YerongAI** [comment]
已更改临时文件夹路径，之后应该就不会再有这种问题了。

**Comment by XDIOEZ** [comment]
确实 我删除后就可以进去了 但为啥26年了 这个问题还是在;)

**Comment by YerongAI** [comment]
> 确实 我删除后就可以进去了 但为啥26年了 这个问题还是在;)

请确保不是从很旧的 Office Tool Plus 升级到最新版，请确保升级过程中没有手动启动 Office Tool Plus。

出现该问题时，可选择删除 Office Tool Plus 后重新下载。
