### ISSUE TITLE
[BUG] 部署界面应用程序选择部分，鼠标悬停提示错位

### ISSUE THREAD

**Issue by StonePick** [YerongAI/Office-Tool#877]
**Office Tool Plus Version, e.g. 8.1.0.0:**
> 10.14.21.8

**Operating System, e.g. Windows 10 20H2 or Windows 7 SP1:**
> Windows 11 家庭中文版 23H2

**Error description (required):**
> 部署界面，产品栏中，“应用程序“一节下的程序，其鼠标悬停提示出现错位。如截图中，Groove的提示变成了Onedrive。

*Reproduction steps (suggested):*
略。

*Screenshot (suggested):*
![bug](https://github.com/user-attachments/assets/47e22b94-b8c6-4b57-b606-ecd8f8e233de)

*Additional information (optional):*
该现象似乎在各个版本中都有出现。

**Comment by YerongAI** [comment]
[Groove](https://learn.microsoft.com/zh-cn/microsoft-365-apps/deploy/office-deployment-tool-configuration-options#id-attribute-part-of-excludeapp-element) 指的就是 OneDrive for Business

**Comment by StonePick** [comment]
> [Groove](https://learn.microsoft.com/zh-cn/microsoft-365-apps/deploy/office-deployment-tool-configuration-options#id-attribute-part-of-excludeapp-element) 指的就是 OneDrive for Business

欸？？我的问题😢，我把这个issue关掉好了。
