### ISSUE TITLE
[BUG] 文档转换功能无法使用

### ISSUE THREAD

**Issue by 22858** [YerongAI/Office-Tool#878]
**Office Tool Plus Version, e.g. 8.1.0.0:**
> 10.14.21.8

**Operating System, e.g. Windows 10 20H2 or Windows 7 SP1:**
> Windows 11 23H2

**Error description (required):**
> 试图使用文档转换功能时，出现如下错误：

![图片](https://github.com/user-attachments/assets/d9544842-929e-4b93-9227-a61f486fcad3)

> 输入的是文件夹，ppt97-2003格式，按下“转换”按钮就会出这种问题

**Comment by YerongAI** [comment]
大概是没装最新版的 Office

**Comment by 22858** [comment]
装的是mondo，这个版本不行吗🤔
![图片](https://github.com/user-attachments/assets/8d1ba4d6-1176-482a-b140-7a70faf1d29e)

**Comment by YerongAI** [comment]
我说的是版本号

**Comment by 22858** [comment]
这个吗
![图片](https://github.com/user-attachments/assets/566bd58a-abfc-45cf-9407-ba1fb7c268ee)

**Comment by YerongAI** [comment]
尝试用 64 位的 Office Tool Plus，或者反着来尝试 32 位的。实在不行可能需要修复 Office
