### ISSUE TITLE
产品激活失败

### ISSUE THREAD

**Issue by Progress888** [YerongAI/Office-Tool#880]
<img width="452" alt="eaf50c9d5dc6ca945ee928e352bac56" src="https://github.com/user-attachments/assets/d669f73d-3966-4097-8ab9-7bc38abf0db6">

**Comment by YerongAI** [comment]
[https://www.officetool.plus/zh-cn/help/activation.html#_0x8007000d](https://www.officetool.plus/zh-cn/help/activation.html#_0x8007000d)

照做。
