### ISSUE TITLE
[IDEA] Custom autorun.inf

### ISSUE THREAD

**Issue by YoungReckless4** [YerongAI/Office-Tool#883]
**Feature description:**
> I would really like to add my own autorun.inf to the ISO image being created or to configure it in the office tool

**How it work?**
> At the moment, if you place your autorun.inf in a directory that will be added to the image, it will be ignored and generated by the program automatically. It would be very good if it were possible to set your own autorun.inf parameters when creating an image in the office tool. But it would be great even if the program determines that the autorun.inf is already in the directory, it will use it, and not generate a new one.

**Comment by YerongAI** [comment]
Done. The `autorun.inf` created by user will be used first. If not found, the program will create one.

After creating Office ISO, the `autorun.inf` will be deleted.

**Comment by YoungReckless4** [comment]
> Done. The `autorun.inf` created by user will be used first. If not found, the program will create a new one.
> 
> After creating Office ISO, the `autorun.inf` will be deleted.

Thank You so much! Works as it should!
