### ISSUE TITLE
[IDEA] 文档转换功能输出格式下拉菜单显示后缀名

### ISSUE THREAD

**Issue by PigeonP** [YerongAI/Office-Tool#884]
![Clip_2024-10-08_21-03-50](https://github.com/user-attachments/assets/96ed02d6-af72-4777-a4b6-65d6dd34ae0f)
如图，能否在文档转换功能中的输出格式项中增加相应文件名对应的扩展名，以便更好地识别目标格式

**Comment by YerongAI** [comment]
扩展名是有的，展开下拉框后，把鼠标放在对应项目上即可看到。

**Comment by YerongAI** [comment]
更新已发布。现在程序会根据系统设置自动显示文件扩展名。
