### ISSUE TITLE
[BUG] 

### ISSUE THREAD

**Issue by gh0stsp3ctre** [YerongAI/Office-Tool#887]
**Office Tool Plus Version, e.g. 8.1.0.0:**
> v10.16.15.0

**Operating System, e.g. Windows 10 20H2 or Windows 7 SP1:**
> Windows 11 24H2

**Error description (required):**
> Your administrator has blocked this action. 
This was blocked by Datto AV, and was detected as potential ransomware. 

*Reproduction steps (suggested):*
Have Datto AV installed, attempt to run the "Office Tools Plus.exe" on v10.16.15.0

*Screenshot (suggested):*
![Screenshot 2024-10-10 091402](https://github.com/user-attachments/assets/4adcb5ec-ed33-4c95-88fe-f31807806db0)

*Additional information (optional):*
This is not the case with previous versions of Office Tools Plus (e.g v10.14.21.8). The previous versions open quite fine with no issue.

**Comment by YerongAI** [comment]
It's better to contact the Datto AV support teams. But the company doesn't provide any services in my country.

**Comment by dekthaiinchina** [comment]
**_I tried scanning the file with virustotal and it didn't detect any alerts from many antiviruses. I'm not sure if you downloaded the file from the official project?_**

Office Tool Plus.exe // v10.16.15.0
Scan results:
https://www.virustotal.com/gui/file/f6db48c0b01f6b25b31b82c06abd7ab84dc135e11e9aa8f6660604df26d5baec/detection/f-f6db48c0b01f6b25b31b82c06abd7ab84dc135e11e9aa8f6660604df26d5baec-1728539960

**Comment by gh0stsp3ctre** [comment]
Yes I alwasy go to the Github link to download. I can open older versions of Office Tools Plus but this particular version gets flagged by Datto for some reason. Datto is provided by our MSP so we aren't able to see the logs or even disable antivirus momentarily. I dont think our MSP blocked Office Tools Plus seeing that it affects this particular version. Maybe there's something in the update that has been flagged.

**Comment by dekthaiinchina** [comment]
**_If so, you may need to configure datto so that it doesn't block office tool plus._**
