### ISSUE TITLE
[BUG] 无法安装旧指定版本的Microsoft 365

### ISSUE THREAD

**Issue by fuchanghao** [YerongAI/Office-Tool#888]
**Office Tool Plus Version, e.g. 8.1.0.0:**
> [v10.16.15.0](https://github.com/YerongAI/Office-Tool/releases/tag/v10.16.15.0)

**Operating System, e.g. Windows 10 20H2 or Windows 7 SP1:**
> Windows 10 LTSC 2021

**Error description (required):**
> 无法安装旧指定版本的Microsoft 365

*Reproduction steps (suggested):*
1. 下载一个旧版本的Microsoft 365 例如指定为16.0.16130.21094版本。
2. 进行部署，部署的时候报错，提示版本不一致，无法部署。

*Screenshot (suggested):*

![屏幕截图 2024-10-11 170127](https://github.com/user-attachments/assets/766427dd-5f2d-461e-86d6-32fa8fe93ebe)

*Additional information (optional):*

16.0.16130.21094是已经停止支持的半年度企业通道。

Semi-Annual Enterprise Channel: Version 2302 (Build 16130.21094)

XML为

```
<Configuration>
  <Add OfficeClientEdition="64" Channel="SemiAnnual" SourcePath="F:\" Version="16.0.16130.21094">
    <Product ID="MondoRetail">
      <Language ID="zh-cn" />
      <ExcludeApp ID="Groove" />
    </Product>
  </Add>
</Configuration>
```

**Comment by YerongAI** [comment]
可否将 `Office\Data` 文件夹下的 `v64_16.0.16130.21094.cab` 上传一下呢？

**Comment by fuchanghao** [comment]
> 可否将 `Office\Data` 文件夹下的 `v64_16.0.16130.21094.cab` 上传一下呢？

[v64_16.0.16130.21094.cab.zip](https://github.com/user-attachments/files/17340681/v64_16.0.16130.21094.cab.zip)

文件名删除zip后缀。

**Comment by YerongAI** [comment]
FFN: 89815e81-c82e-49a3-99dc-2b99229cf632
Branch: Production:DCEXT

这个通道已经被微软删除了，因此该通道上的旧版本 Office 不再有效，Office Tool Plus 也就无法再识别。

**Comment by fuchanghao** [comment]
> FFN: 89815e81-c82e-49a3-99dc-2b99229cf632 Branch: Production:DCEXT
> 
> 这个通道已经被微软删除了，因此该通道上的旧版本 Office 不再有效，Office Tool Plus 也就无法再识别。

这个通道已经被删除了，但是文件依旧可以下载，而且我用部署工具手动进行部署也部署成功了。（16.0.16130.21094这个是最后一个Windows 8.1支持的版本。）

**Comment by YerongAI** [comment]
> > FFN: 89815e81-c82e-49a3-99dc-2b99229cf632 Branch: Production:DCEXT
> > 这个通道已经被微软删除了，因此该通道上的旧版本 Office 不再有效，Office Tool Plus 也就无法再识别。
> 
> 这个通道已经被删除了，但是文件依旧可以下载，而且我用部署工具手动进行部署也部署成功了。（16.0.16130.21094这个是最后一个Windows 8.1支持的版本。）

1. 我尝试下载 https://officecdn.microsoft.com/pr/89815e81-c82e-49a3-99dc-2b99229cf632/Office/Data/16.0.16130.21094/i320.cab ，但是并不能成功下载。
2. 经调查，微软将 `89815e81-c82e-49a3-99dc-2b99229cf632` 回退到了 `7ffbc6bf-bc32-4f92-8982-f9dd17fd3114`，即从 `Production:DCEXT` 映射到了 `Production:DC`。我们将会在后期中做类似的处理，但仍然需要更多的考虑。

**Comment by YerongAI** [comment]
[更新](https://github.com/YerongAI/Office-Tool/releases/tag/v10.17.9.0)已发布，该问题应该得到了解决。
