### ISSUE TITLE
[BUG] Unable to start downloading Office

### ISSUE THREAD

**Issue by Shaocw** [YerongAI/Office-Tool#889]
**Office Tool Plus Version, e.g. 8.1.0.0:**
>v10.16.15.0 (X64)

**Operating System, e.g. Windows 10 20H2 or Windows 7 SP1:**
> Windows 11 23H2

**Error description (required):**
> After clicking the Start Deploy button, an error message appears: "startIndex cannot be larger than length of string. (Parameter 'startIndex')" and unable to start downloading Office.

*Reproduction steps (suggested):*
Add products
chose Visio 2021 pro
start deploy
fail to download

*Screenshot (suggested):*
![image](https://github.com/user-attachments/assets/d506275f-3a42-4d53-a4d3-7015faa7000d)

*Additional information (optional):*

**Comment by YerongAI** [comment]
Does the error always happen?

And what is the languages that you have added?

**Comment by Shaocw** [comment]
Thx! I found that English was already in my language installation list, so I ignored this step. It's available after adding language.

**Comment by YerongAI** [comment]
New release is out, check [here](https://github.com/YerongAI/Office-Tool/releases/tag/v10.17.9.0).
