### ISSUE TITLE
[BUG] Cannot download office

### ISSUE THREAD

**Issue by Branislav84** [YerongAI/Office-Tool#890]
**Office Tool Plus Version, e.g. 8.1.0.0:**
> Office Tool v10.16.15.0 x64

**Operating System, e.g. Windows 10 20H2 or Windows 7 SP1:**
> Windows 11 24H2
**Error description (required):**
> Cannot download office

*Reproduction steps (suggested):*
Download office
Select Products
Select language
Deploy

*Screenshot (suggested):*

![Capture](https://github.com/user-attachments/assets/5803f371-6df0-4492-875b-a2ca9e69d4e6)

*Additional information (optional):*
Cannot download any version of office with Office Tool v10.16.15.0 x64, old version Office Tool v10.14.28.0 x64 works without issues

**Comment by YerongAI** [comment]
New release is out, check [here](https://github.com/YerongAI/Office-Tool/releases/tag/v10.17.9.0).
