### ISSUE TITLE
[Bug] 创建ISO文件，选择office部署工具，生成的iso中依然是office tools 部署工具

### ISSUE THREAD

**Issue by purezhang** [YerongAI/Office-Tool#895]
### What is the version of Office Tool Plus?

v10.17.9.0

### What is the version of your Operating System?

win 11 24h2

### What is the error?

[Bug] 创建ISO文件，选择office部署工具，生成的iso中依然是office tools 部署工具

### How does this problem occur?

[Bug] 创建ISO文件，选择office部署工具，生成的iso中依然是office tools 部署工具

**Comment by YerongAI** [comment]
对啊，要不然呢？

**Comment by purezhang** [comment]
请问下，创建iso的时候的选择：office部署工具，office tools 部署工具 的区别是什么？
在选择 的时候，工具中的帮助说明 也是有区别的描述的，所以我理解选择，“office部署工具”  实现的是类似与 微软官方的 iso 中部署的 样子。

**Comment by YerongAI** [comment]
> 请问下，创建iso的时候的选择：office部署工具，office tools 部署工具 的区别是什么？
> 在选择 的时候，工具中的帮助说明 也是有区别的描述的，所以我理解选择，“office部署工具”  实现的是类似与 微软官方的 iso 中部署的 样子。
> 

你要理解前面四个字：“安装模块”。

这里只是决定了装 Office 的时候用什么装，跟创建 Office ISO 长什么样没有关系。

**Comment by purezhang** [comment]
> > 请问下，创建iso的时候的选择：office部署工具，office tools 部署工具 的区别是什么？
> > 在选择 的时候，工具中的帮助说明 也是有区别的描述的，所以我理解选择，“office部署工具”  实现的是类似与 微软官方的 iso 中部署的 样子。
> 
> 你要理解前面四个字：“安装模块”。
> 
> 这里只是决定了装 Office 的时候用什么装，跟创建 Office ISO 长什么样没有关系。

明白了，你是产品经理+研发经理，你说的就是正确的。

目前创建ISO不支持使用office安装工具么？
建议把安装和创建iso分开描述，避免这样的误会。

**Comment by purezhang** [comment]
这个应该修改不是bug，应是issue

**Comment by YerongAI** [comment]
那你还需要知道的是没人可以做出来你认为的官方的那种 ISO。

你可以自己去网上求证，看看谁能自己做。我反正是不行。

**Comment by purezhang** [comment]
> 那你还需要知道的是没人可以做出来你认为的官方的那种 ISO。
> 
> 你可以自己去网上求证，看看谁能自己做。我反正是不行。

了解了，谢谢
