### ISSUE TITLE
[IDEA] Rub a .bat or .ps1 Script after Deploying

### ISSUE THREAD

**Issue by gh0stsp3ctre** [YerongAI/Office-Tool#897]
### Feature description

Ability to automatically open a .bat or .ps1 script after deployment is completed.

### How does it work?

Currently the only options are None, Sign Out, Reboot, Power Off, or Close Office Tools Plus. 
Having an option to run a .bat  .ps1 cript may help automating tasks post-installation.
![Request](https://github.com/user-attachments/assets/3f2b9a67-c69f-4a2f-9b9a-5781961be4f4)

**Comment by YerongAI** [comment]
For security reasons, we do not intend to do this.

If you want to run custom commands after installation, you can call Office Tool Plus via [Office Tool Plus.Console](https://www.officetool.plus/usage/command/application.html#office-tool-plus-console-helper) to install Office.
