### ISSUE TITLE
[Bug] 查询错误代码会导致崩溃

### ISSUE THREAD

**Issue by 1357310795** [YerongAI/Office-Tool#899]
### What is the version of Office Tool Plus?

v10.17.9.0 (X86)

### What is the version of your Operating System?

Windows 10 专业版 22H2 (19045.5011) (X64)

### What is the error?

OTP 直接崩溃，无错误代码

### How does this problem occur?

查询错误代码 0xC004C004，崩溃。

**X64 的 OTP 运行正常**，X86 的 OTP 是不是要做一些额外的适配？

![image](https://github.com/user-attachments/assets/ae37c926-cc5a-4484-bdf8-1eddaadd6a49)

**Comment by YerongAI** [comment]
这不应该啊，如果从官网上重新下载 Office Tool Plus 呢？

**Comment by 1357310795** [comment]
抱歉回复晚了。今天下载了最新版 OTP(x86) 试了下，运行一切正常，然后又回到那个出问题的（从旧版本升级上来的）程序，仍然正常。

无法复现了，Close 吧。

**Comment by YerongAI** [comment]
我也遇到了这个问题，看起来是 ntdll 的问题。这个问题可能性与 Windows 更大一点，因为出现这个问题之后，只需要重启 Windows 就好了。如果是我代码写得有问题的话，应该是稳定复现才对。
