### ISSUE TITLE
[Bug] 为什么安装Project和Visio 2024版显示的是 Preview 版

### ISSUE THREAD

**Issue by cethink** [YerongAI/Office-Tool#901]
### What is the version of Office Tool Plus?

v10.17.9.0 (x86)

### What is the version of your Operating System?

Windows 11 23H2 build 22631.4391 (x64)

### What is the error?

Project和Visio 2024版显示的是 Preview 版

### How does this problem occur?

安装完在软件中查看版本

**Comment by YerongAI** [comment]
因为你需要重新安装 Visio 和 Project 的许可证，这是微软的问题，我们没法从根源上解决。

**Comment by cethink** [comment]
https://bbs.pcbeta.com/viewthread-2016528-1-1.html

刚从这里解决了，谢谢

**Comment by cethink** [comment]
https://github.com/YerongAI/Office-Tool/blob/main/doc/Tech%20Articles/Products.md

备注一下：从这里找个Key替换一下就可以了

**Comment by YerongAI** [comment]
不需要自行寻找产品密钥并记住它，安装许可证时 Office Tool Plus 会自动安装对应的产品密钥，此时会被替换为正式版密钥。或者通过程序命令 [/getkey](https://www.officetool.plus/usage/command/application.html#in-application-commands) 获取产品密钥。
