### ISSUE TITLE
[Bug] 无法正常安装部署 “孔卡尼语-印度(kok-IN)” 语言

### ISSUE THREAD

**Issue by fuchanghao** [YerongAI/Office-Tool#903]
### What is the version of Office Tool Plus?

v10.17.9.0

### What is the version of your Operating System?

WIndows 10 LTSC 2021

### What is the error?

选择kok-IN作为部署语言的时候无法正常部署

### How does this problem occur?

部署选择kok-IN作为部署语言，会出现正常下载完毕文件之后报错。
文件丢失：i641111.cab

我尝试过通过永久链接来下载这个文件

例如这是可以正常下载的：
https://officecdn.microsoft.com/pr/492350f6-3a01-4f97-b9c0-c7c6ddf67d60/Office/Data/16.0.18025.20160/i640.cab

但是这个链接确实没有：

https://officecdn.microsoft.com/pr/492350f6-3a01-4f97-b9c0-c7c6ddf67d60/Office/Data/16.0.18025.20160/i641111.cab

报错截图如下：

![屏幕截图 2024-10-24 183915](https://github.com/user-attachments/assets/0c414fad-091e-4a34-9704-6b84f5bd31e8)

**Comment by YerongAI** [comment]
确实是个问题，kok-in 被错误标记为完整类型的语言，所以会检查 i641111.cab 是否存在。将会在下次更新中解决此问题。

**Comment by YerongAI** [comment]
更新已发布。
