### ISSUE TITLE
[Bug] 通过Scoop安装的OTP，在部署时会安装失败， error code：30182-2016

### ISSUE THREAD

**Issue by zuilintan** [YerongAI/Office-Tool#905]
### What is the version of Office Tool Plus?

10.17.9.0

### What is the version of your Operating System?

Win11 24H2

### What is the error?

30182-2016

### How does this problem occur?

必现问题

### Anything else you want to tell us

改为解压版运行部署，已正常安装

**Comment by zuilintan** [comment]
scoop安装方式
`scoop install extras/office-tool-plus`

**Comment by YerongAI** [comment]
scoop 不是我们官方在管理。
