### ISSUE TITLE
[Bug] win7下运行，部署选下载为iso  提示校验故障

### ISSUE THREAD

**Issue by pope-L** [YerongAI/Office-Tool#906]
### What is the version of Office Tool Plus?

10.17.9.0_x64

### What is the version of your Operating System?

window7

### What is the error?

下载校验错误

### How does this problem occur?

无论这个最新版 还是9.x版 都是 下载完了，提示校验出错，不能生成 iso

**Comment by YerongAI** [comment]
校验出错就是文件有问题了，尝试重新下载 Office 安装文件。

**Comment by pope-L** [comment]
应该不是， 或许是校验部分 win7 环境是返回错误的值
因为不应该，同样网络环境win7下载几次都校验出错

**Comment by YerongAI** [comment]
> 应该不是， 或许是校验部分 win7 环境是返回错误的值 因为不应该，同样网络环境win7下载几次都校验出错

如果有条件，你可以把有问题的文件复制到另一个 Windows 上进行检查。

**Comment by pope-L** [comment]
确实对比win10下 运行下载的文件有差异，奇怪了几乎同一时间下载，win7下载的文件总有校验不过的，win7里的虚拟机win10下载的就没错污，
对了：9.0那个版说适合win7系统，通道里没得2024的选

**Comment by YerongAI** [comment]
我刚才下载了一遍 16.0.12527.22286 - 64 位带 简体中文 语言包的测试，并没有发现异常。

以及 Office 2024 无法安装在 Windows 7 中。

**Comment by pope-L** [comment]
下载那个看来我这里有点玄学啊啊
是的2024装不了win7，我只是想用otp 下载回来再生成iso而已，不过这个请求也不是什么大不了，当您哪天贤者时间无聊了在考虑搞不搞吧。
