### ISSUE TITLE
[Bug] 不知道这样的主机

### ISSUE THREAD

**Issue by YasonGF** [YerongAI/Office-Tool#908]
### What is the version of Office Tool Plus?

v10.17.9.0

### What is the version of your Operating System?

版本	Windows 10 家庭中文版 版本号	22H2	

### What is the error?

不知道这样的主机。 (officecdn.microsoft.com:80)

### How does this problem occur?

部署ProPlus2021Retail时，发生这个错误

### Log output

```shell
2024/11/12 19:46:41	Error	Downloader	Download failed. Error (-2146233088): One or more errors occurred. (不知道这样的主机。 (officecdn.microsoft.com:80)). Inner exception (-2147467259): 不知道这样的主机。 (officecdn.microsoft.com:80). Inner exception (-2147467259): 不知道这样的主机。 (officecdn.microsoft.com:80). Inner exception (-2147467259): 不知道这样的主机。
```

**Comment by YerongAI** [comment]
自查网络，这种问题只能是网络问题。

**Comment by YasonGF** [comment]
嗯嗯，谢谢老哥。确实是网络问题，现在激活好了
