### ISSUE TITLE
斗胆请求开源UI代码

### ISSUE THREAD

**Issue by ahdung** [YerongAI/Office-Tool#912]
这套UI真的很先进、很现代，想学习，能否指缝里漏一点点让我等观摩、敬仰？

**Comment by YerongAI** [comment]
可以去看别人用 Win UI 做的项目，一样的。

https://github.com/microsoft/PowerToys/tree/main/src/settings-ui

**Comment by ahdung** [comment]
谢谢回应，但你这个我猜是WPF，可以跑在win7，他那个WinUI不行吧

**Comment by YerongAI** [comment]
确实。

**Comment by ahdung** [comment]
所以~可否~
