### ISSUE TITLE
[Bug] 在同时有32位和64位安装镜像时删除32位会残留v32.cab文件，反过来也是如此。

### ISSUE THREAD

**Issue by fuchanghao** [YerongAI/Office-Tool#913]
### What is the version of Office Tool Plus?

v10.18.11.0

### What is the version of your Operating System?

WIndows 10 LTSC 2021

### What is the error?

在同时有32位和64位安装镜像时删除32位会残留v32.cab

### How does this problem occur?

1. 下载Office的64位版本安装文件（我是当前通道）。
2. 可以看到只有 Office\Data\v64.cab和Office\Data\v64_{$Version}.cab
3. 再切换下载32位版安装文件。
4. 删除32位版安装文件。发现会有Office\Data\v32.cab文件残留。
5. 反过来删除64位安装文件，发现会有Office\Data\v64.cab文件残留。

**Comment by YerongAI** [comment]
已修复，下个月发布新版本。
