### ISSUE TITLE
[Bug] 使用 Office 部署工具模块安装失败，Office Tool Plus 模块正常

### ISSUE THREAD

**Issue by PriceHu** [YerongAI/Office-Tool#916]
### What is the version of Office Tool Plus?

v10.18.11.0

### What is the version of your Operating System?

Windows 11 24H2 (26100.2314)

### What is the error?

Setup Failed: A newer version of Setup is required to install this product

### How does this problem occur?

选择产品 O365ProPlusRetail 及 VisioPro2024Retail，选择当前通道，以 Office 部署工具作为安装模块进行任意安装操作时，会出现安装程序错误，提示 `A newer version of Setup is required to install this product`。该问题在切换至 Office Tool Plus 模块后消失。

以移除现有安装的 Publisher 为例，软件设置如图：
![image](https://github.com/user-attachments/assets/55a556ff-915b-4f01-b499-2ef1e5020a2e)
以下为配置代码：
```xml
<Configuration>
  <Add OfficeClientEdition="64" Channel="Current">
    <Product ID="O365ProPlusRetail">
      <Language ID="zh-cn" />
      <ExcludeApp ID="Access" />
      <ExcludeApp ID="Bing" />
      <ExcludeApp ID="Groove" />
      <ExcludeApp ID="Lync" />
      <ExcludeApp ID="OneDrive" />
      <ExcludeApp ID="OneNote" />
      <ExcludeApp ID="Publisher" />
      <ExcludeApp ID="Teams" />
    </Product>
  </Add>
</Configuration>
```
安装预览如下：
![image](https://github.com/user-attachments/assets/5b944af3-bec9-43b1-ae10-c29484eb8aa9)
点击安装后，部署工具错误如下：
![image](https://github.com/user-attachments/assets/72648bb6-bad1-45ee-ae8a-c6334e38204e)

切换使用 Office Tool Plus 安装模块，所有安装过程可正常完成。

### Log output

```shell
2024/11/26 17:28:11	Info	Deploy	Loading Office information.
2024/11/26 17:28:11	Info	Deploy	Office is installed on C:\Program Files\Microsoft Office
2024/11/26 17:28:11	Info	Deploy	Office version: 16.0.18129.20158
2024/11/26 17:28:11	Info	Deploy	Office architecture: x64.
2024/11/26 17:28:11	Info	Deploy	Office branch: Production::CC.
2024/11/26 17:28:11	Info	Deploy	Successfully obtaining Office version information.
2024/11/26 17:28:11	Info	Deploy	Successfully obtaining C2R releases information.
2024/11/26 17:37:28	Info	LaunchInstaller	Installer started. Process ID: 10212
2024/11/26 17:38:14	Info	LaunchInstaller	Installer exited with code: 1603
2024/11/26 17:40:09	Info	Exiting	Saving all settings.
2024/11/26 17:40:10	Info	Exiting	Settings saved.
```

**Comment by YerongAI** [comment]
暂时复现不出来。

**Comment by arshcaria** [comment]
同样遇到此问题，新安装的windows 11 24h2，office选择和配置如下：

![image](https://github.com/user-attachments/assets/49c63c69-ea0e-4e51-b075-29ad0aec81d6)

报错如下：

![image](https://github.com/user-attachments/assets/28013652-5a74-4cee-81f2-dcb5ba11e720)

**Comment by YerongAI** [comment]
> 同样遇到此问题，新安装的windows 11 24h2，office选择和配置如下：
> 
> ![image](https://private-user-images.githubusercontent.com/3211106/395827490-49c63c69-ea0e-4e51-b075-29ad0aec81d6.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzQyNzE3MTQsIm5iZiI6MTczNDI3MTQxNCwicGF0aCI6Ii8zMjExMTA2LzM5NTgyNzQ5MC00OWM2M2M2OS1lYTBlLTRlNTEtYjA3NS0yOWFkMGFlYzgxZDYucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MTIxNSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDEyMTVUMTQwMzM0WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9OTRjMDk0NmJiMmJmNjgxNmQzOGY1OTg2NGJlNTJmZmJhMDY5Yzg3OGQ3YjI3MjZmYjE0ODRmZWU5YTUxZTY1NSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QifQ.HCvBPWwmjISUG_DO7cf9L4u9cLZPBllVNcUOpLBD5t0)
> 
> 报错如下：
> 
> ![image](https://private-user-images.githubusercontent.com/3211106/395827502-28013652-5a74-4cee-81f2-dcb5ba11e720.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzQyNzE3MTQsIm5iZiI6MTczNDI3MTQxNCwicGF0aCI6Ii8zMjExMTA2LzM5NTgyNzUwMi0yODAxMzY1Mi01YTc0LTRjZWUtODFmMi1kY2I1YmExMWU3MjAucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MTIxNSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDEyMTVUMTQwMzM0WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9NWJiODFiZTQ5ZTM0NWM1ZWFmZTQ2NTUxMGZhYzhhMWQwNTQ5MTA5ZmRjZWY2ZjYwZGY3NmU4M2ZlY2U0ODJjOSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QifQ.J0d0MSXsY6vzPIsobKP26rfZnBImN4lvi2KLI-LOtdc)

依然无法复现，我安装了 24H2 之后检查系统版本是 26100.2605

**Comment by PriceHu** [comment]
**跟进：**

我尝试手动下载并使用官方 Office 部署工具在终端中进行安装项修改，使用的是 Office Tool Plus 输出的 XML，结果安装正常。使用同样来源的 XML，在终端中手动调用 Office Tool Plus 文件夹中包含的 `setup.exe` 进行安装，结果同样正常。对比两者的 Hash，显示一致，为同一文件。由于目前系统里有多个微软账户，重新部署会导致许可证错乱，暂时没有继续测试直接使用 Office Tool Plus GUI。

这个问题似乎已经存在了很长一段时间，而且是跟官方部署工具相关的，在其他地方能够找到直接使用官网工具进行部署发生相同错误的报告。我目前的一个猜想是与 Windows 预装的 Office 软件相关。在安装 24H2 时使用微软账户联网登录可以在开始菜单看到预装的 Office App，`Program Files` 中存在 `Microsoft Office 15` 文件夹，虽然我已经通过设置卸载了。但这个猜想需要进一步验证。暂不清楚本地账户以及离线安装是否有相同表现。后续将继续在别的系统尝试复现

**Comment by YerongAI** [comment]
在我看来，这个问题应该不是 Office Tool Plus 造成的。在创建 XML 配置之后，OTP 的操作也是运行 `setup.exe /configure xxx.xml`，这个问题看起来更像是系统和 Office 部署工具之间的问题，目前只有 Windows 11 24H2 有报告，别的系统没有报告，我自己测试的环境也没有复现这个问题。

**Comment by PriceHu** [comment]
同意。如果没有针对官方工具的修复计划可以考虑关闭 Issue。
