### ISSUE TITLE
[Bug] XXH128 Wrong Value and SHA-3 Issue

### ISSUE THREAD

**Issue by lelik107** [YerongAI/Office-Tool#924]
### What is the version of Office Tool Plus?

v10,19.8.0 x64

### What is the version of your Operating System?

Windows 10 22H2 x64 Pro

### What is the error?

The calculation of XXH128 and inability to calculate SHA-3

### How does this problem occur?
This a bug report.
The calculation of XXH128 gives a wrong value. You can check it with the reference utility from here:
https://github.com/Cyan4973/xxHash/releases/tag/v0.8.2
https://github.com/Cyan4973/xxHash/releases/download/v0.8.2/xxhsum_win64_v0_8_2.zip
XXH128 contains XXH3, for example:
XXH128
xxhsum -H2 file
4a742de7c95d9b6a**625ac5f9deb088c9**
XXH3
xxhsum -H3 file
**625ac5f9deb088c9**

This is a suggestion.
And I can't calculate SHA-3, error is "Operation is not supported on this platform".
I think it's for Windows 11 only because its API is used. 
You could use an independent code for the older systems at some point.
https://github.com/XKCP/XKCP
Keccak Team official repository, Keccak algo tuned by NIST is FIPS-202 SHA-3.

**Comment by YerongAI** [comment]
Thank you for your info. The XXH128 value was fixed. I just checked [NanaZip](https://github.com/M2Team/NanaZip) and followed it. Maybe there is a same issue on NanaZip, you can make a new issue to them.

The SHA-3 functions is provided by Windows 11 24H2. I don't plan on adding third-party implementations.

**Comment by lelik107** [comment]
Thank you for great software!
As for NanaZip I know what it is but I have never used it, I wouldn't like to bug report something I can't check later.
As for SHA-3 I don't need them that much to make a FR directly, so my suggestion is or to separate them with "Windows 11 Only" mark or if OTP detects a system where it's at to disable them if it's not Windows 11.

**Comment by lelik107** [comment]
@YerongAI Thank you, I checked XXH3 and it's OK now. And the addition about SHA-3 which are only available with the certain Windows 11 versions is very nice.
