### ISSUE TITLE
[IDEA] Modify program to load external language files to test UI translation

### ISSUE THREAD

**Issue by bovirus** [YerongAI/Office-Tool#926]
### Feature description

Add option to load external language files

### How does it work?

@YerongAI 

Please consider if you can modify your program to load language files (as example .xaml file available on Github) to test/revise the translation in place.

Thanks.

**Comment by YerongAI** [comment]
You can use `/loaddict` command to do that.

When Office Tool Plus is running, press <kbd>Ctrl</kbd> + <kbd>Shift</kbd> + <kbd>P</kbd> to open command box, then enter `/loaddict <path to xaml file>` to load the new translations. Or you can enter `/cldict` to remove all the loaded files.

Some strings may not updated after loading file. Such as product name and channel name.

**Comment by bovirus** [comment]
Thanks.
Ticket closed.
