### ISSUE TITLE
[IDEA]之前otp工具箱里有remove by office 365这一选项，直接运行一个脚本，非常方便，现在移除了？变得不方便了

### ISSUE THREAD

**Issue by EA-DICE** [YerongAI/Office-Tool#94]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by YerongAI** [comment]
旧的功能已被新功能替代，请使用 All Office via official tool 以移除 Office
