### ISSUE TITLE
[IDEA] 日期显示对应语言文化进行格式适配

### ISSUE THREAD

**Issue by yaeyaya** [YerongAI/Office-Tool#97]
**Is your feature request related to a problem? Please describe.**
![image](https://user-images.githubusercontent.com/9144748/73625500-1af14880-4680-11ea-8709-4dd16973acf7.png)
设置页面》程序信息》更新日期
比如，美国常用2/3/2020格式，中国常用2020-02-03，韩国常用2020.2.3等，目前此处日期信息没有与Culture信息进行适配

**Comment by YerongAI** [comment]
这个是根据系统自动适配的，不会说因为更改了 OTP 的语言就会跟着变，除非系统原生是英语、韩语 etc.
