### ISSUE TITLE
[ASK] Parallels 虚拟机内的 Windows 10 无法打开软件

### ISSUE THREAD

**Issue by JMwill** [YerongAI/Office-Tool#98]
如题，在虚拟机内安装了最新版的 Windows 10，无法打开软件，只显示加载的圆圈，还有就是双击运行程序时在任务管理器中能看到进程数多了两个，加载图标消失后，进程数就恢复原来的数量了。

确定已经安装了最新的 .NET Framework

![office-tool](https://user-images.githubusercontent.com/11496449/73644432-59066080-46b0-11ea-8e97-b14dcca57eb9.gif)

**Comment by YerongAI** [comment]
建议检查安装的系统是否正常。

**Comment by JMwill** [comment]
> 建议检查安装的系统是否正常。

是正常的安装，系统应该也是正常的。其他软件可以正常安装，免安装的软件：屏幕截图等都可以使用。

**Comment by YerongAI** [comment]
> > 建议检查安装的系统是否正常。
> 
> 是正常的安装，系统应该也是正常的。其他软件可以正常安装，免安装的软件：屏幕截图等都可以使用。

虚拟机内不确定的因素太多，建议自行排查问题

**Comment by JMwill** [comment]
那可不可以给个方向呢？我不太熟悉 Windows 下的软件要怎么排查，进程有被调起，但后续就是不显示，连个错误都不弹出来 😂，实在是不知道要怎么弄

**Comment by YerongAI** [comment]
> 那可不可以给个方向呢？我不太熟悉 Windows 下的软件要怎么排查，进程有被调起，但后续就是不显示，连个错误都不弹出来 😂，实在是不知道要怎么弄

可我用的时候从没出过问题啊，我也不知道啊

**Comment by JMwill** [comment]
OK，那只能这样了

**Comment by JMwill** [comment]
感谢 522809359（mo_22）提供的进程监视器软件的帮助建议，通过使用 [这个工具](https://docs.microsoft.com/en-us/sysinternals/downloads/procmon)，帮忙定位到了问题所在。这里描述一下，帮助有同样问题的人。

-  **环境：** Parallels 15、Mac Pro 18 年版、根据 Parallels 软件提供的方式在线安装的 Windows 10
-  **问题：** 拖动 Office tool plus 到虚拟机内运行无反应，只有一段时间的加载图案出现，无错误提示
-  **定位问题：** 原因是因为 Parallels 建立的虚拟机与 Mac 共享了桌面以及下载等文件夹，导致当拖动的 Office tool plus 处于桌面文件夹中双击运行时，其执行路径是以 `\\Mac` 开头的。估计是程序无法找到正确的系统路径而静默退出。
-  **解决办法：** 将 Office tool plus 拖到 C 盘内的任意空间内再执行程序即可。
